README.md

@kensimon @timothysc PTAL, just a quick change that @kstewart wanted.
(I need to rebase all of the history for my original fork, re-forking was just fastest for now).

[docs] Minor readme edits

---

README.md
docs/configuration.md

Updated README to be more consistent with our summary elsewhere; fixed broken link.
@timothysc @kensimon PTAL thanks!

[docs] Update readme blurb

---

CHANGELOG.md

[docs] Update changelog

---

Makefile

Makefile: tag with git describe output

---

docs/snapshot.md
pkg/discovery/discovery.go
pkg/discovery/pods.go
pkg/discovery/queries.go
pkg/discovery/queryrecorder.go

This shifts some of the layout based on the doc changes in #43.
Also adds some docs explaining the auto-extraction of plugin tar files

Initial stab at changing snapshot layout

---

Makefile

Drop old gcloud line from make push

---

docs/plugins.md

Signed-off-by: Andy Goldstein <andy.goldstein@gmail.com>

Fix "Available Plugins" link

---

README.md

Add slack channel and mailing list links

---

examples/ksonnet/components/10-configmaps.jsonnet
examples/quickstart/aggregate.yaml
examples/quickstart/components/10-configmaps.yaml

Due to reported experience #82
However I was not able to repro a bug that was reported there. 

Update to disable collecting PodLogs by default & rev Conformance versions

---

CONTRIBUTING.md

[license] Fix typo in contributing.md

---

README.md
examples/ksonnet/components/10-configmaps.jsonnet
examples/quickstart.yaml

Update to pull in kube 1.8.1+ container for tests.

---

CONTRIBUTING.md

@timothysc PTAL, based on discussion with Joe and Andy

[license] Reword authors in contributing.md

---

README.md
docs/README.md

Fixes: https://github.com/heptio/sonobuoy/pull/117 
Fixes: https://github.com/heptio/sonobuoy/issues/120

Minor fixes from inbound docs issues filed.

---

Makefile
examples/ksonnet/components/10-configmaps.jsonnet
examples/quickstart.yaml
pkg/config/loader_test.go
plugins.d/e2e.jsonnet
plugins.d/heptio-e2e.jsonnet
plugins.d/heptio-e2e.tmpl
plugins.d/systemd_logs.jsonnet
plugins.d/systemd_logs.tmpl

Adds a plugin for heptio-e2e tests

---

pkg/discovery/queries.go

/cc @chuckha  - just going to self merge b/c I tested and it's trivial

Fix bug caused by cleanup on node collection.

---

pkg/discovery/queries.go

Only try old APIs if current ones cannot be found

---

README.md
examples/conformance.yaml
examples/ksonnet/components/10-configmaps.jsonnet

Version bump for 0.10.0

---

docs/plugins.md

Signed-off-by: Brad Geesaman <bradgeesaman+github@gmail.com>

Add bulkhead plugin to listing table

---

Makefile
examples/ksonnet/components/01-e2e.libsonnet
examples/ksonnet/components/10-configmaps.jsonnet

* Makefile updates
* Move some jsonnet to a libsonnet file
Related to work on #76

Example generation updates

---

docs/snapshot.md

Closes #170
* Alphabetizes the structure
* Adds a section for `servergroups.json`

Updates snapshot documentation

---

docs/enhancements/v2-worker-master.md

SEP is Sonobuoy Enhancement Proposal.
I know I was all gung-ho about grpc for this, but having read the code I no longer think that makes sense.
No rush in reviewing this, ofc!

SEP: V2 Worker/Master communication protocol proposal

---

pkg/plugin/aggregation/aggregator_test.go
pkg/plugin/aggregation/run.go
pkg/plugin/aggregation/server.go
pkg/plugin/aggregation/server_test.go
pkg/plugin/aggregation/stress_test.go
pkg/worker/worker_test.go

Factors responsibility for starting the HTTP server out of aggregater/server. This both gets us closer to #154 and allows the tests to be greatly simplified

refactor-aggregator-server

---

pkg/discovery/pods.go

Skip evicted pods

---

cmd/sonobuoy/app/results.go

This wraps `kubectl` for now.
Related to #27

Implement results command

---

docs/plugins.md
examples/conformance.yaml
examples/ksonnet/components/10-configmaps.jsonnet
examples/quickstart.yaml

Cleanup from walking through and minor issues filed.

---

README.md

Update follows upstream deprecation cycle. 
I'm updating this b/c I've been poked by folks asking questions.

Update supported versions on master to align with upstream

---

pkg/results/reader.go

Detect type to decode

---

README.md

Small update to the example tar extraction process.
Closes #192 
Signed-off-by: wadeholler <wade.holler@ndatum.net>

Update README with working archive and results directory instructions

---

docs/enhancements/streamlined-templates.md

Sonobuoy Enhancement Proposal for new Plugin format

---

examples/quickstart.yaml

Signed-off-by: Jeremiah Wuenschel <jeremiah.wuenschel@gmail.com>

Adding a missing space to the quickstart yaml

---

pkg/backplane/ca/authtest/testserver.go
pkg/backplane/ca/ca.go
pkg/backplane/ca/ca_test.go

This PR has been spun out of #190, because that PR was wayyy to big.
@chuckha I tried to follow your requests in the previous PR.
Doesn't add any new functionality, but lays an important foundation for #154

Sonobuoy CA

---

cmd/sonobuoy/app/logs.go
cmd/sonobuoy/app/operations/logs.go
cmd/sonobuoy/app/utils/client.go

Implements logs subcommand

---

pkg/worker/worker.go

Logic reduction

---

pkg/results/reader.go

Wrap errors in results library

---

cmd/sonobuoy/app/cp.go
cmd/sonobuoy/app/gen.go
cmd/sonobuoy/app/logs.go
cmd/sonobuoy/app/master.go
cmd/sonobuoy/app/run.go
cmd/sonobuoy/app/status.go
cmd/sonobuoy/app/version.go
cmd/sonobuoy/app/worker.go

Have Cobra enforce arg numbers

---

cmd/sonobuoy/app/args/mode.go
cmd/sonobuoy/app/gen_plugin.go

List available Sonobuoy modes

---

docs/enhancements/status-reporting.md

SEP-4: Status reporting

---

docs/enhancements/e2e-command-line.md

SEP-e2e-commandline proposal

---

cmd/sonobuoy/app/args.go
cmd/sonobuoy/app/cp.go
cmd/sonobuoy/app/gen.go
cmd/sonobuoy/app/kubeconfig.go
cmd/sonobuoy/app/logs.go
cmd/sonobuoy/app/operations/logs.go
cmd/sonobuoy/app/operations/mode.go
cmd/sonobuoy/app/operations/run.go
cmd/sonobuoy/app/run.go
cmd/sonobuoy/app/status.go
pkg/plugin/driver/daemonset/template.go

My proposal for how arguments could work in the future.
Doesn't work 100% yet (mode fails)

Refactor and consolidate command arguments

---

pkg/plugin/aggregation/run.go

Make sure all plugins are complete before ending status updates

---

cmd/sonobuoy/app/args.go
cmd/sonobuoy/app/cp.go
cmd/sonobuoy/app/gen.go
cmd/sonobuoy/app/logs.go
cmd/sonobuoy/app/run.go
cmd/sonobuoy/app/status.go
pkg/client/cp.go
pkg/client/gen.go
pkg/client/interfaces.go
pkg/client/logs.go
pkg/client/mode.go
pkg/client/run.go
pkg/client/status.go
pkg/config/config.go

I changed cmd/ops -> pkg/client 
Then it can be client.Interface.Fn
/cc @chuckha @liztio

Adds TODO comments from walk through, lots of cleanup and shuffling 

---

cmd/sonobuoy/app/gen.go
cmd/sonobuoy/app/master.go
cmd/sonobuoy/app/root.go
cmd/sonobuoy/app/run.go
cmd/sonobuoy/app/status.go
pkg/discovery/discovery.go

Cleanup safe Exit(0) scenarios

---

cmd/sonobuoy/app/args.go
cmd/sonobuoy/app/gen.go
cmd/sonobuoy/app/kubeconfig.go
cmd/sonobuoy/app/run.go
cmd/sonobuoy/app/sonobuoyconfig.go
pkg/client/gen.go
pkg/client/interfaces.go
pkg/client/mode.go
pkg/templates/manifest.go

Allow config and e2e-focus and e2e-skip overrides

---

cmd/sonobuoy/app/retrieve.go
pkg/client/interfaces.go
pkg/client/retrieve.go

Rename `cp` to `retrieve`.

---

pkg/client/gen.go

Override the WorkerImage with SonobuoyImage

---

pkg/client/run.go

fix typo in function name

---

cmd/sonobuoy/app/args.go
cmd/sonobuoy/app/run.go
pkg/client/interfaces.go
pkg/client/run.go

Preflight check for a DNS pod

---

pkg/client/logs.go

Fix log streaming

---

cmd/sonobuoy/app/kubeconfig.go
cmd/sonobuoy/app/master.go
cmd/sonobuoy/app/run.go
pkg/config/config.go
pkg/config/loader.go
pkg/config/loader_test.go

and eliminates the kubeconfig settings in sonobuoys config struct.
I still need to finish my testing on it and am breaking up commits to each part. 
/cc @liztio

The following PR changes how the master kubeconfig is loaded

---

pkg/config/config.go

Fix default resultsdir for aggregator.

---

pkg/client/run.go

Bugfix for preflight check

---

README.md
cmd/sonobuoy/app/args.go

Cleanup doc and cmd-line flags

---

cmd/sonobuoy/app/master.go
cmd/sonobuoy/app/worker.go

Hide master/worker from the main UX as they are used internally.

---

cmd/sonobuoy/app/retrieve.go

Improve retrieve command usage

---

pkg/client/run.go

Closes #291 
```
$ sonobuoy run --mode quick -n liz-test
INFO[0000] created object                                name=liz-test namespace= resource=namespaces
INFO[0000] created object                                name=sonobuoy-serviceaccount namespace=liz-test resource=serviceaccounts
INFO[0000] created object                                name=sonobuoy-serviceaccount namespace= resource=clusterrolebindings
INFO[0000] created object                                name=sonobuoy-serviceaccount namespace= resource=clusterroles
INFO[0000] created object                                name=sonobuoy-config-cm namespace=liz-test resource=configmaps
INFO[0000] created object                                name=sonobuoy-plugins-cm namespace=liz-test resource=configmaps
INFO[0000] created …
```

Non-namespaced objects can already exist for `sonobuoy run`.

---

cmd/sonobuoy/app/status.go
cmd/sonobuoy/app/status_test.go

--show-all for status

---

cmd/sonobuoy/app/args.go
cmd/sonobuoy/app/delete.go
cmd/sonobuoy/app/e2e.go
cmd/sonobuoy/app/gen.go
cmd/sonobuoy/app/logs.go
cmd/sonobuoy/app/master.go
cmd/sonobuoy/app/retrieve.go
cmd/sonobuoy/app/run.go
cmd/sonobuoy/app/status.go

This should make it easier to add flags to commands that "depend" on other commands

Refactor flag handling

---

cmd/sonobuoy/app/delete.go
cmd/sonobuoy/app/e2e.go
cmd/sonobuoy/app/gen.go
cmd/sonobuoy/app/logs.go
cmd/sonobuoy/app/rbac.go
cmd/sonobuoy/app/retrieve.go
cmd/sonobuoy/app/run.go
cmd/sonobuoy/app/status.go
pkg/client/delete.go
pkg/client/interfaces.go
pkg/client/logs.go
pkg/client/retrieve.go
pkg/client/run.go
pkg/client/status.go

Updates NewSonobuoyClient to take *rest.Config to prevent passing in

---

cmd/sonobuoy/app/args.go
cmd/sonobuoy/app/gen.go
cmd/sonobuoy/app/imagepullpolicy.go
pkg/client/gen.go
pkg/client/interfaces.go
pkg/config/loader.go
pkg/plugin/driver/base.go
pkg/plugin/driver/daemonset/daemonset.go
pkg/plugin/driver/daemonset/daemonset_test.go
pkg/plugin/driver/daemonset/template.go
pkg/plugin/driver/job/job.go
pkg/plugin/driver/job/job_test.go
pkg/plugin/driver/job/template.go
pkg/plugin/interface.go
pkg/plugin/loader/loader.go
pkg/plugin/loader/loader_test.go
pkg/templates/manifest.go

ImagePullPolicy flag

---

main.go

Return exit code 1 when command not found

---

cmd/sonobuoy/app/args.go
pkg/client/defaults.go
pkg/client/gen.go
pkg/config/config.go
pkg/config/loader.go
pkg/discovery/discovery.go
pkg/discovery/queries.go

Also s/PluginNamespace/Namespace/
`time="2018-03-07T22:17:55Z" level=info msg="Filtering namespaces based on the following regex:.*|liz-test"`
Closes #333

Fix namespace bug

---

cmd/sonobuoy/app/delete.go
pkg/client/delete.go
pkg/client/interfaces.go
pkg/client/logs.go
pkg/client/retrieve.go
pkg/client/run.go
pkg/client/status.go

Cache clients for future use

---

pkg/client/retrieve.go

Fix nil pointer dereference

---

Gopkg.lock
cmd/sonobuoy/app/e2e.go
cmd/sonobuoy/app/run.go
pkg/buildinfo/version.go
pkg/client/defaults.go
pkg/client/interfaces.go
pkg/client/preflight.go
pkg/client/run.go
vendor/github.com/hashicorp/go-version/.travis.yml
vendor/github.com/hashicorp/go-version/LICENSE
vendor/github.com/hashicorp/go-version/README.md
vendor/github.com/hashicorp/go-version/constraint.go
vendor/github.com/hashicorp/go-version/version.go
vendor/github.com/hashicorp/go-version/version_collection.go

API Version preflight check for sonobuoy run

---

pkg/buildinfo/version.go

Update to v0.11.0-alpha.1

---

pkg/client/logs.go
pkg/client/logs_test.go

Fix race condition in sonobuoy logs

---

README.md

/cc @rbankston @liztio @Bradamant3

Update README.md to add prereqs for building the CLI.

---

.goreleaser.yml
.travis.yml

This will (hopefully) use Gorelease to create binaries for the sonobuoy cli.
It's really hard to test this stuff locally, so hopefully it works!
Part of (but not all of) #100

Create Sonobuoy CLI binaries for tags

---

Makefile
pkg/buildinfo/version.go

Commit is also to test other automation.
xref: #100 

Removes DockerImage b/c it's the tag'd version.

---

pkg/client/doc.go
pkg/client/example_interfaces_test.go
pkg/client/interfaces.go
pkg/client/results/doc.go
pkg/client/results/junit_utils.go
pkg/client/results/reader.go
pkg/client/results/reader_test.go

Adds examples to client and results packages.
Closes #356

Improves godoc

---

README.md

Signed-off-by: JENNIFER RONDEAU <jrondeau@heptio.com>
Change summary:
- Fixes: #351 
- copyedit for clarity and succinctness
- fix links for publishing to docs site
DO NOT MERGE UNTIL IMMEDIATELY BEFORE RELEASE. (contains link to new docs site, which does not yet exist and won't until release time.)

[do-not-merge] update readme for upcoming release

---

pkg/config/config.go

Default config.DefaultImage to cite buildinfo.Version

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

I'm a process person, and this will force my hand to write the details. 
This will should hopefully make @liztio and @chuckha happier.

Adds submission templates to make sure we are consistent.

---

pkg/client/preflight.go

Since now [coredns](https://github.com/coredns/coredns) it is a real alternative for DNS server in Kubernetes I would like to be able to run sonobuoy without modifying default labels. This PR replace #366
Signed-off-by: Fernando Ripoll <pipo02mix@gmail.com>

Consider core dns in the preflight DNS check

---

pkg/worker/worker.go

Fixes a signal handling bug.
No issue created
This is what I wanted to do originally.
When the worker gets a shutdown signal, it waits for $GRACEFUL_SHUTDOWN_PERIOD and then actually cleans up.
What it did before was simply sleep and block the main thread then exit.
```
release-note
```

fixes signal handling bug

---

docs/conformance-testing.md
docs/plugins.md
docs/snapshot.md

Signed-off-by: JENNIFER RONDEAU <jrondeau@heptio.com>
This PR copyedits doc changes for the 0.11 release: standardizes terminology, clarifies explanations, fixes markup.
@liztio @timothysc @chuckha

copyedits for 0.11 release

---

cmd/sonobuoy/app/worker.go
pkg/worker/worker.go
pkg/worker/worker_test.go

* Adds a test to the cleanup case.
Closes #372
I think this simplifies the logic for the worker.
- Fixes #372
It's ok if you don't think this actually makes the code easier to read/follow. I'm happy to close it without merging.
```
release-note
```

Refactors worker waiting function

---

cmd/sonobuoy/app/run.go

Closes #378
- Fixes #
```
release-note
```

Fixes plugin message bug

---

docs/plugins.md
pkg/plugin/driver/base.go
pkg/plugin/driver/daemonset/daemonset_test.go
pkg/plugin/driver/daemonset/template.go
pkg/plugin/driver/job/job_test.go
pkg/plugin/driver/job/template.go
pkg/plugin/interface.go
pkg/plugin/manifest/manifest.go
pkg/plugin/manifest/serializer.go
pkg/plugin/manifest/serializer_test.go
pkg/plugin/manifest/testdata/extravolumes.yaml

Allows plugin authors to add extra volumes to all containers
- Fixes #387 
```
Allow plugin authors to add additional mounts
```

Extra volumes

---

pkg/buildinfo/version.go

Set version for release 
none
```
NONE
```

Update to v0.11.0

---

pkg/buildinfo/version.go

i ran this command `git tag -a v0.11.1`
- Fixes #
```
release-note
```

Version bump for release

---

_includes/header.html
_includes/nav.html
_layouts/default.html
assets/css/style.scss
assets/img/icon-menu.svg
assets/js/scripts.js

Adds responsive layout and scrollbar for TOC to docs site
- Fixes #408
Test site available at https://bradamant3.github.io/sonobuoy/latest/
```
Docs site now responsive at narrower screen sizes. Navigation is scrollable.
```

Add responsive layout to docs site

---

pkg/buildinfo/version.go

Patch bump to v0.11.3

---

README.md
docs/conformance-testing.md

Fixes old and dead links 
```
NONE
```

Fix old, and dead links

---

pkg/client/mode.go

This PR removes the extended tests in a minimal way as possible.
```
NONE
```

Remove Exteneded as a valid mode

---

pkg/client/run.go
pkg/dynamic/client.go

Fixes #470
Fixes a bad bug.
```
NONE
```

Use the REST mapper to get an obj's resource

---

README.md

Fixes a stale link on the main readme
- Fixes #495
```
NONE
```

Updates the readme to remove an old statement

---

docs/plugins.md

Signed-off-by: Levi Blackstone <levi.blackstone@RACKSPACE.COM>
Update outdated links in plugin overview doc
- None
```
None
```

Update links in plugin overview doc

---

Makefile

Fix the deployer Makefile line
```
```

Fix tagging

---

Makefile

Actually push the minor tags we're creating
- Fixes #499 
```
```

Fix pushing minor version tags

---

pkg/buildinfo/version.go

Bump to v0.12.1

---

docs/release.md

Signed-off-by: Ruben Orduz <rubenoz@gmail.com>
Add checks/steps to release document.

Added checks to release document

---

Makefile

This change will keep the existing make settings in place
but will fix a problem where `make build_sonobuoy` wouldn't
apply the correct GOOS/GOARCH for the host.
This means that anyone can run `make build_sonobuoy` and get
just their sonobuoy binary created and that `make sonobuoy`
creates the 2 linux binaries (always generated) and the
correct sonobuoy binary (in the cwd).
Fixes #590
```
Fixed host build chain for non-linux/amd64 GOOS/GOARCH
```

Fix problem for building locally on non-Linux OS

---

pkg/discovery/discovery.go

These lines were not meant to be checked in. Removing them.

Remove debug lines

---

travis-deploy.sh

This process is no longer done in Travis.
Fixes: #613

Remove image pushing from Travis

---

Makefile

Our new build/release process goes through Jenkins
so the agent/auth requirements are a bit different.

Push images in Jenkins

---

pkg/buildinfo/version.go

Bump versions for v0.14

---

.gitignore
.travis.yml

The skipping of validation failed for one reason
or another. In theory the validation is a good
thing anyways so this time I just tried adding the
items to the .gitignore so it won't impact the
release.

Clean up a few artifacts for clean state

---

.travis.yml
Makefile

If we want to improve code coverage, we need to monitor/track it.
Relates to #651 
WIP at the moment; seeing what happens on this PR.
```
Begin tracking code coverage in each PR.
```

Add CodeCov reports

---

pkg/discovery/discovery.go

The benefit of doing this is that the pod will
respond to status requests more quickly and
if we try and patch the status (being careful
to not overwrite plugin results) we don't have
to worry about it not yet existing on the pod.
Fixes #696
```
Fixed an issue where the aggregator may fail to annotate the pod as complete if no plugins are run.
```

Add initial annotation to the pod when starting

---

README.md
site/docs/latest/README.md
site/docs/master/README.md

The versions were hardcoded, meaning it would have to be updated
on every release. Instead I explained the versioning/support
scheme and how to opt-out of it if desired. This will not have
to change unless we change those larger schemes.
Fixes #736
I want to make sure that the website properly updates when we update the readme. It is a bit unique since it is the only page _not_ in the docs/site that needs to be a part of the website.
```
NONE
```

Adjust README description of support matrix

---

pkg/plugin/driver/daemonset/daemonset.go
pkg/plugin/driver/daemonset/daemonset_test.go
pkg/plugin/driver/job/job_test.go

- Extracts logic from daemonset.Monitor to another function
that doesnt involve polling for easier testing
- Use fake client to mock different cluster situations
- Add tests for each return path
- Touch up a job.Monitor test for clarity/consistency
Related to #651 
Related to #667 (expanding testing of those methods so that we can test the higher level fix in the next PR more easily)
```
NONE
```

Add daemonSet monitoring tests

---

cmd/sonobuoy/app/gen.go
cmd/sonobuoy/app/worker.go

This PR just applies changes resulting from running `gofmt`.
These changes were included in another branch I'm working on
but I thought it would be better to separate them into their own PR.
```
None
```

Apply changes from running gofmt

---

pkg/buildinfo/version.go
pkg/image/manifest.go
pkg/image/v1.15.go

Increase the version number and include the new images from the
Kubernetes 1.15 release.

Prepare v0.15.0 release

---

kind-config.yaml

Pin images used in kind config and reduce number of workers

---

site/Gemfile
site/_config.yml
site/_includes/head-docs.html
site/_includes/head.html
site/blog.html
site/community.md
site/docs/index.md
site/index.html
site/resources.md

These changes should enable the SEO plugin functionality on the site, leading to better search results.
Signed-off-by: Jonas Rosland <jrosland@vmware.com>

Add SEO functionality to the site

---

site/_posts/2019-09-16-customizing-plugin-podspecs.md

Add blog post for Custom PodSpecs

---

.travis.yml
Makefile
travis-deploy.sh

I know we're moving away from Travis but I'm working out the
details of getting our scripts to push appropriately. Moving
this to CircleCI probably wont add much overhead.
Related to #914

Get dockerhub image pushing to work on Travis

---

Makefile
travis-deploy.sh

Failed to have a necessary flag to read password from stdin.

Fixup to docker image push

---

.circleci/config.yml

Fixup to path to script

---

site/_posts/2019-04-02-isolated-to-conformant.md
site/_posts/2019-04-30-custom-testing.md
site/_posts/2019-06-26-Env-vars-on-the-fly.md
site/_posts/2019-08-07-simplified-results-reporting-with-sonobuoy.md
site/_posts/2019-09-16-customizing-plugin-podspecs.md
site/_posts/2019-09-25-Summary-of-improvements.md
site/_posts/2019-10-01-new-github-org.md
site/_posts/2019-10-09-Custom-E2E-Image.md

Add older blog posts as noted in #955 , and add images/links for the authors.

Add older blog posts and author images

---

pkg/plugin/driver/utils/utils.go
pkg/plugin/driver/utils/utils_test.go

Previously, we would treat any image pull error as a final error and it
would result in a plugin being marked as failing. In this change, we now
allow a window of 5 minutes from when the pod started to allow recovery
from these errors as they may be transient.
- Fixes #969 
I initially was going to check against the pod phase and expect that the pod moved out of `Pending` within the window of time. However, I realised that could impact a pod being slow to start if, for example, it was taking a long time to pull an image. Instead, this value is only being used if a container is in `ErrImagePull` or `ImagePullBackOff` after the …

Add wait period to allow image pull error recovery

---

site/_posts/2019-11-18-cis-benchmark-plugin.md

Fix formatting of commands in CIS blog post

---

site/index.html

Signed-off-by: rbankston <ralph.l.bankston@gmail.com>
Updates the github site to point to the latest version of the sonobuoy docs
- Fixes #1012 
Docs update

Updated docs link to point to latest

---

site/_posts/2019-12-06-Conformance-Testing-With-Progress-Updates.md

Add blog post describing progress updates from e2e plugin

---

README.md
site/_data/shortlinks.yml
site/docs/master/README.md

Add results to shortlinks and update link to remove .md suffix

---

site/docs/master/release.md

Draft PR for now as it will include a link to a commit for the v0.17.0 release.
We introduced a new command to output the default image registry configs
for the version of Kubernetes being tested. The release process docs
did not include instructions on how to update this for a minor release
so this change includes those details.

Update release docs

---

site/_config.yml
site/_includes/plugins.html
site/_includes/site-header.html
site/_plugin-list/01-cis-benchmark.md
site/_plugin-list/02-e2e-testing.md
site/_plugin-list/03-systemd.md
site/_plugin-list/04-kube-hunter.md
site/_plugin-list/05-who-can.md
site/plugins.md

This will add a new "Plugins" page on the Sonobuoy landing page.

Add Sonobuoy plugins page

---

site/_contributors/04-michael-michael.md

Simple rename of the role M2 has.
Signed-off-by: Jonas Rosland <jrosland@vmware.com>

Change M2 from project to product mgr

---

Makefile

Don't error if build directory already exists

---

site/_plugin-list/05-who-can.md
site/_posts/2020-05-15-who-can-plugin.md

Also update the plugins page to provide a link to the project and remove the in-progress status.

Add blog post for who-can plugin

---

README.md
site/docs/master/README.md

Fixes broken link in README.md

README.md: Fix broken link to docker

---

README.md
site/docs/master/README.md

John's webinar from last year covers a lot of the more recent features
that have been added such as the newer plugin format and the results
feature.

Use latest Sonobuoy webinar as the overview video

---

.github/workflows/codeql-analysis.yaml

Run CodeQL analysis to be alerted on security issues
None
None
```
NONE
```

CodeQL analysis weekly + pushes + PRs

---

README.md
site/docs/master/README.md
site/docs/v0.19.0/README.md

Signed-off-by: Wilson E. Husin <whusin@vmware.com>
Add documentation guide for workaround on Docker Hub rate limit issues.
None
None
```
NONE
```

Add Docker Hub rate limit workaround

---

site/_contributors/01-john-schnake.md
site/_contributors/01-vladimir-vivien.md
site/_contributors/02-bridget-mcerlean.md
site/_contributors/02-steve-sloka.md
site/_contributors/02-wilson-husin.md
site/_contributors/03-lucy-shang.md
site/_contributors/03-tim-hinderliter.md
site/_contributors/04-eddie-dinel.md
site/_contributors/04-michael-michael.md
site/index.html

Contributors

---

pkg/plugin/driver/job/job.go

- Fixes #1187 
```
support for running on heterogenous clusters (linux tests only)
```

Support mixed windows/linux by default via scheduling to linux

---

site/content/posts/2021-03-08-establishing-reliability-as-code-via-sonobuoy.md

**What this PR does / why we need it**: Blog post for reliability scanner
- Fixes # n/a
**Special notes for your reviewer**: n/a
**Release note**: n/a

Reliability-As-Code blogpost

---

README.md
site/content/docs/master/_index.md
site/content/docs/v0.50.0/_index.md

Signed-off-by: Wilson E. Husin <whusin@vmware.com>
```
```

Replace outdated version with placeholder

---

site/content/docs/master/faq.md

FAQ doc was referring to invalid hyperlink to the conformance test link
- NA
```
update/correction in Documentation
```

Update Correct conformance test link ref

---

.github/workflows/ci-lint.yaml
.github/workflows/ci-test.yaml
scripts/build.sh
scripts/build_funcs.sh
scripts/ci/check_go_modules.sh
scripts/ci/check_readme_in_sync.sh
scripts/ci/publish.sh
scripts/sync_readme.sh
scripts/update_docs.sh

- Adds a step in github actions to run shellcheck
- Fixes lots of quoting issues in bash scripts

Add shellcheck and fix issues

---

site/content/docs/v0.13.0/_index.md

Fixes #1242
Only impacted one file actually; I thought it would be more throughout the versions but it wasnt.

Remove old scanner link

---

site/content/posts/2021-06-07-Windows-Support.md

Just waiting for a few PRs to merge and the next release to drop. Wanted to get the markdown fixed so it was ready to go.

Windows blog post

---

.github/workflows/ci-test.yaml
go.mod
go.sum
pkg/client/testdata/custom-systemd-logs-image.golden
pkg/client/testdata/default-plugins-via-nil-selection.golden
pkg/client/testdata/default-pod-spec.golden
pkg/client/testdata/default.golden
pkg/client/testdata/e2e-default.golden
pkg/client/testdata/e2e-progress-custom-port.golden
pkg/client/testdata/e2e-progress-vs-user-defined.golden
pkg/client/testdata/e2e-progress.golden
pkg/client/testdata/envoverrides.golden
pkg/client/testdata/goRunnerRemoved.golden
pkg/client/testdata/imagePullSecrets.golden
pkg/client/testdata/manual-custom-plugin-plus-e2e.golden
pkg/client/testdata/manual-custom-plugin-plus-systemd.golden
pkg/client/testdata/manual-custom-plugin.golden
pkg/client/testdata/manual-e2e.golden
pkg/client/testdata/multiple-node-selector.golden
pkg/client/testdata/no-plugins-via-selection.golden
pkg/client/testdata/plugins-and-pluginSelection.golden
pkg/client/testdata/single-node-selector.golden
pkg/client/testdata/ssh.golden
pkg/client/testdata/systemd-logs-default.golden
pkg/client/testdata/use-existing-pod-spec.golden
pkg/templates/gen.tmpl.yaml
pkg/templates/template.go

Using the new embed package here allows the IDE to use
language aware coloring/tools/etc. Also makes it easy
to swap copy the file and swap out with a different one
for dev/testing.

Use embed to improve readability

---

site/content/posts/2021-06-21-windows-e2e.md

Adds windows e2e blog post

---

site/content/posts/2021-06-21-windows-e2e.md

Milage may vary but I want to provide a free alternative to Azure
and also start working more with this project. Ideally we'll
eventually typically run our smoke tests for Windows using this
project.

Add K8sOnWindows alternative to Azure

---

pkg/client/logs.go

The retryWatcher in client go seems to be broken and results
in the logs being restarted from the same spot each time despite
the version info being set.
Using a typical watch seems to fix the issue.
```
Fixed a bug where following logs (sonobuoy logs -f) would result in the same log messages being repeated.
```

Prevent logs -f from repeating

---

scripts/build_funcs.sh

Add convenience function for updating goldenfiles

---

.github/workflows/ci-test.yaml

Ran into a problem where it wasnt clear if the action
was checking out the expected commit. Adds this log line
to the unit tests and integration tests just to have
an extra debug point.
A few points of formatting touched up as well.

Update github actions workflows to show history

---

cmd/sonobuoy/app/args.go
cmd/sonobuoy/app/gen.go
pkg/client/gen.go
pkg/client/gen.tmpl.yaml

This allows the `gen` logic to be even more simple
and avoid e2e specific logic.

Ssh path flag

---

cmd/sonobuoy/app/args.go
cmd/sonobuoy/app/gen.go
cmd/sonobuoy/app/images.go
pkg/client/gen.go
pkg/client/gen_test.go
pkg/client/interfaces.go
pkg/client/testdata/default-plugins-via-nil-selection.golden
pkg/client/testdata/default-plugins-via-selection.golden
pkg/client/testdata/default-pod-spec.golden
pkg/client/testdata/default.golden
pkg/client/testdata/e2e-default.golden
pkg/client/testdata/e2e-progress-custom-port.golden
pkg/client/testdata/e2e-progress-vs-user-defined.golden
pkg/client/testdata/e2e-progress.golden
pkg/client/testdata/envoverrides.golden
pkg/client/testdata/goRunnerRemoved.golden
pkg/client/testdata/imagePullSecrets.golden
pkg/client/testdata/manual-custom-plugin-plus-e2e.golden
pkg/client/testdata/manual-custom-plugin-plus-systemd.golden
pkg/client/testdata/manual-custom-plugin.golden
pkg/client/testdata/manual-e2e.golden
pkg/client/testdata/multiple-node-selector.golden
pkg/client/testdata/plugin-configmaps.golden
pkg/client/testdata/plugins-and-pluginSelection.golden
pkg/client/testdata/single-node-selector.golden
pkg/client/testdata/systemd-logs-default.golden
pkg/client/testdata/use-existing-pod-spec.golden
pkg/config/config.go
pkg/image/imageversion.go

Waiting for some of the other PRs to merge since it needs transforms and also a change to `sonobuoy gen plugin e2e`

Plugin image flag

---

site/content/posts/2021-07-06-understanding-kubernetes-tests.md
site/themes/sonobuoy/assets/scss/_base.scss

Clarifies a major/reoccuring question we get about why
certain tests are skipped, how/when certain tests are needed,
and how to run certain tests.
Fixes #1306
No rush on this one; going to wait a while so the Windows E2E one gets merged and settles. Maybe a week or two and this one can go in.

Blog describing Kubernetes suite

---

site/content/posts/2021-07-06-understanding-kubernetes-tests.md

Blog update regarding quick mode

---

site/config.yaml
site/themes/sonobuoy/layouts/partials/docs-right-bar.html

- Removes button to edit docs. Would work well since we have master
docs and versioned docs that we have to reconcile. In addition it was failing
to get the user email address anyways.
- Fixes the link for reporting issues
- Fixes the body/title for the issue being reported
Fixes: #1365

Update sonobuoy.io button to edit docs and report issues

---

cmd/sonobuoy/app/args.go
cmd/sonobuoy/app/gen_config.go
cmd/sonobuoy/app/gen_plugin_def.go
cmd/sonobuoy/app/images.go
cmd/sonobuoy/app/logs.go
cmd/sonobuoy/app/root.go
cmd/sonobuoy/app/run.go
pkg/client/gen_test.go
pkg/config/config.go

Misc changes to CLI help/messages to clarify behavior or make
it more consistent with current descriptions of what Sonobuoy
does and how.
Fixes #1172

Tweak CLI language

---

site/content/docs/master/faq.md
site/content/docs/master/gen.md
site/content/docs/master/plugins.md
site/content/docs/master/pullsecrets.md
site/content/docs/master/snapshot.md
test/integration/sonobuoy_integration_test.go

Just a quick update to some language in the site docs to
reflect recent changes to Sonobuoy.

Update site docs

---

cmd/sonobuoy/app/root.go
test/integration/sonobuoy_integration_test.go
test/integration/testdata/gen-issue-1376.golden

May consider a different approach to this, but at the moment
we want to atleast recognize that setting these flags together
may cause unintended consequences.
Partially fixes: #1376

Warn if k8s-version and set with conflicting flags

---

site/data/docs/master-toc.yml
site/data/docs/v0-52-0toc.yml
site/data/docs/v0-53-0toc.yml
site/themes/sonobuoy/layouts/partials/docs-sidebar.html

Fix broken link after plugins moved

---

README.md
site/content/docs/master/_index.md
site/content/docs/v0.53.0/_index.md
site/content/docs/v0.53.0/issue1388.md
site/content/docs/v0.53.1/_index.md
site/content/docs/v0.53.1/issue1388.md

This makes it easier to document it as a known issue and point
3rd parties to the issue description and solution.

Add documentation about issue 1388

---

site/content/contributors/03-eleanor-millman.md
site/content/contributors/03-wilson-husin.md
site/content/contributors/04-lucy-shang.md
site/content/contributors/05-eddie-dinel.md

Update contributors on site

---

pkg/client/results/item.go
pkg/client/results/junit.go
pkg/client/results/manual.go
pkg/client/results/manual_test.go
pkg/client/results/processing.go
pkg/client/results/processing_test.go

Exporting this so that another package (in sonobuoy-plugins) can
import them and make a plugin helper.

Export and tweak some of the manual results methods/values

---

site/content/docs/main/e2eplugin.md
site/content/docs/main/plugins.md
site/content/docs/v0.19.0/e2eplugin.md
site/content/docs/v0.19.0/plugins.md
site/content/docs/v0.20.0/e2eplugin.md
site/content/docs/v0.20.0/plugins.md
site/content/docs/v0.50.0/e2eplugin.md
site/content/docs/v0.50.0/plugins.md
site/content/docs/v0.51.0/e2eplugin.md
site/content/docs/v0.51.0/plugins.md
site/content/docs/v0.52.0/e2eplugin.md
site/content/docs/v0.52.0/plugins.md
site/content/docs/v0.53.0/e2eplugin.md
site/content/docs/v0.53.0/plugins.md
site/content/docs/v0.53.1/e2eplugin.md
site/content/docs/v0.53.1/plugins.md
site/content/docs/v0.53.2/e2eplugin.md
site/content/docs/v0.53.2/plugins.md
site/content/docs/v0.54.0/e2eplugin.md
site/content/docs/v0.54.0/plugins.md
site/content/docs/v0.55.0/e2eplugin.md
site/content/docs/v0.55.0/plugins.md
site/content/plugins/list/05-who-can.md
site/content/posts/2019-10-09-Custom-E2E-Image.md

Git markers were accidentally left in docs.

Remove junk from docs

---

site/content/posts/2021-11-09-E2E-Skeleton-Plugin.md
site/themes/sonobuoy/assets/scss/_base.scss

Add blog for e2e-skeleton plugin

---

pkg/buildinfo/version.go
scripts/update_docs.sh

- bumps version in code
- modifies script for bumping the docs to also bump the version in code
- Fixes #1520

Manually bump version to v0.55.0 for library code

---

README.md
site/content/docs/main/_index.md

Just added KinD as a local option; that is what devs working
on Sonobuoy use and what large parts of the community does as well.
Fixes #1554

Adjust cluster suggestions for starting with Sonobuoy

---

README.md
site/content/docs/main/_index.md
site/content/docs/main/strategy.md
site/content/docs/v0.55.1/_index.md
site/content/docs/v0.55.1/strategy.md

Add strategy doc

---

pkg/worker/worker.go

In order to facilitate interception and modification of results
by sidecars, wait some amount of time before consuming the done
file and sending results.
This allows sidecars to remove the done file, modify them as necessary,
and then rewrite the done file when appropriate.
- Fixes #1530
I used a modified e2e plugin to test this; notice the sidecar I added. The net result will be that results never get submitted to the aggregator. When we build/publish post-processors we can have better integration tests that this functionality works.
```
The Sonobuoy worker (sidecar to the plugin images) will now wait 5s before submitting results. If the done file is removed during that time, it will begin polling …
```

Add a delay before consuming done file for postprocessing window

---

cmd/sonobuoy/app/status.go
cmd/sonobuoy/app/testdata/expectedShowAll.golden
cmd/sonobuoy/app/testdata/expectedSummary.golden
pkg/client/run.go
pkg/plugin/interface.go
pkg/plugin/interface_test.go

Issue1595
Some plugins do not declare the total number of tests, so the progress update is confusing
- Fixes #1595

Issue1595: deal with plugins with unknown total tests count

---

kind-config.yaml

Update kind images

---

.github/ISSUE_TEMPLATE/weekly-release.md
site/content/docs/main/dryRun-listGenerator.md

- update data for e2e command
- move commands to harbor registry
Fixes #1624

Add extra steps for release

---

.github/ISSUE_TEMPLATE/weekly-release.md
site/content/docs/main/dryRun-listGenerator.md

Tweak docs for release and dryrun test lists

---

GOVERNANCE.md
design/README.md

Add governance document and design folder

---

pkg/plugin/aggregation/run.go

The help documentation states that a `--timeout 0` will wait indefinitely. This PR changes the type of `context` used when timeout is zero such that a timeout will not occur. 
Note that if `--timeout 0` is set right now (without this PR change) then the aggregator instantly times out waiting for workers.
https://github.com/vmware-tanzu/sonobuoy/blob/bbc49da2ac20431b76a0aa5d6a17fe5331bf0161/cmd/sonobuoy/app/args.go#L317-L323
**What this PR does / why we need it**: To match documentation and wait indefinitely for underlying jobs to complete. 
**Special notes for your reviewer**: I'm not familiar with Sonobuoy's set of tests and am not sure if this timeout==0 situation is covered. Any guidance would be appreciated. 
```
none
```

Fix aggregator to wait forever when timeout is zero.

---

cmd/sonobuoy/app/gen_plugin_def.go
cmd/sonobuoy/app/pluginCache.go

Signed-off-by: DiptoChakrabarty <diptochuck123@gmail.com>
adds a flag to set a plugin description and underlying function logic to set description
- Fixes #1647 
```
release-note
```

add description flag and function to set description

---

test/integration/sonobuoy_integration_test.go

FailNow if Must... fails as expected

---

pkg/client/retrieve.go

The logic takes a path and a file; if the file has path values in it
that do not exist, then os.Create was failing but the MkdirAll logic
wasn't looking for paths in that.
To fix this, I just reconcile the directory/filename to get the full path
and process it accordingly sooner.
Fixes #1689
No tests really hit this but its a pretty trivial change. Just going forward with it having been tested manually. In my opinion this isn't worth a big test setup to check at this time.
```
Fixed a bug where `sonobuoy retrieve -f <filename>` fails if the filename contains path elements that do not exist. 
```

Fix bug where 'retrieve' fails if filepath diectories DNE

---

Makefile
README.md
scripts/build_funcs.sh
site/content/docs/main/_index.md

This will make it easier for people new to the project to figure
out how to contribute or test changes locally.
We should update some of the documentation accordingly as well.
Fixes: #1720

Adds a simple Makefile with the most commonly used options

---

site/content/posts/2022-07-01-july-drumbeat.md

Add July drumbeat

---

site/content/contributors/01-john-schnake.md
site/content/contributors/01-vladimir-vivien.md
site/content/contributors/02-eleanor-millman.md
site/content/contributors/03-eleanor-millman.md

Update Sonobuoy team

---

README.md
site/content/docs/main/_index.md
site/content/docs/v0.56.7/_index.md

Fix link to roadmap wiki

---

pkg/worker/worker.go

Currently we allow a postprocessor to modify the results but this will
allow redirecting to a different file as well. Important if you want
to do something like include extra files, therefore need to tar up
files and update from a single file result to a tarfile.
Fixes #1775

Allow postprocessors to modify done file contents

---

pkg/client/results/processing.go

Preperatory PR for another related to manual results.

Tweak to function to allow multiple args

---

.github/ISSUE_TEMPLATE/weekly-release.md
scripts/gather_e2e_data.sh
scripts/gathere2e/Dockerfile
scripts/gathere2e/gathere2e.yaml
scripts/gathere2e/run.sh
site/content/docs/main/dryRun-listGenerator.md

Created a plugin that does all the e2e data gathering. You'll just
need to run the new script in order to get the updated data.
Fixes #1791

Automate e2e data gathering

---

scripts/build_funcs.sh

Was checking for the file instead of that the file DNE.

Fix check for kubectl

---

cmd/sonobuoy/app/e2e.go
cmd/sonobuoy/app/e2e_test.go

By allowing reference to other test results (and adding/removing
a few tests from them) we can drastically reduce the amount
of space we dedicate to this feature.
Partially addresses: #1650

Allow e2e results to refer to one another

---

pkg/plugin/aggregation/handler_test.go

Signed-off-by: Abirdcfly <fp544037857@gmail.com>
- Fixes #
```
None
```

delete minor unreachable code caused by t.Fatal

---

.github/ISSUE_TEMPLATE/weekly-release.md
.github/workflows/blogDrumbeat.yaml
.github/workflows/blogTopical.yaml

Fix auto-issues to use new label names

---

.github/ISSUE_TEMPLATE/weekly-release.md

Update weekly-release template with better instructions.
```
NONE
```

Update weekly-release issue template

---

site/content/docs/main/pullsecrets.md
site/content/docs/v0.19.0/pullsecrets.md
site/content/docs/v0.20.0/pullsecrets.md
site/content/docs/v0.50.0/pullsecrets.md
site/content/docs/v0.51.0/pullsecrets.md
site/content/docs/v0.52.0/pullsecrets.md
site/content/docs/v0.53.0/pullsecrets.md
site/content/docs/v0.53.1/pullsecrets.md
site/content/docs/v0.53.2/pullsecrets.md
site/content/docs/v0.54.0/pullsecrets.md
site/content/docs/v0.55.0/pullsecrets.md
site/content/docs/v0.55.1/pullsecrets.md
site/content/docs/v0.56.0/pullsecrets.md
site/content/docs/v0.56.1/pullsecrets.md
site/content/docs/v0.56.10/pullsecrets.md
site/content/docs/v0.56.11/pullsecrets.md
site/content/docs/v0.56.12/pullsecrets.md
site/content/docs/v0.56.13/pullsecrets.md
site/content/docs/v0.56.14/pullsecrets.md
site/content/docs/v0.56.15/pullsecrets.md
site/content/docs/v0.56.16/pullsecrets.md
site/content/docs/v0.56.17/pullsecrets.md
site/content/docs/v0.56.2/pullsecrets.md
site/content/docs/v0.56.3/pullsecrets.md
site/content/docs/v0.56.4/pullsecrets.md
site/content/docs/v0.56.5/pullsecrets.md
site/content/docs/v0.56.6/pullsecrets.md
site/content/docs/v0.56.7/pullsecrets.md
site/content/docs/v0.56.8/pullsecrets.md
site/content/docs/v0.56.9/pullsecrets.md

Quick docs fix
- Fixes #
```
release-note
```

use correct file suffix in documentation

---

scripts/build_funcs.sh

- Fixes #
```
release-note
```

use tar output for build func

---

pkg/client/retrieve_test.go
pkg/client/version_test.go

This PR adds unit tests to improve code coverage for retrieval and version functions. 
Dev verified test-runs.
No user-facing change.

Add unit tests for functions
