vmware-tanzu/sonobuoy

build/kube-conformance/Makefile
build/sonobuoy/Makefile

When we build sonobuoy with the docker container we need the output binary to
end up in the Dockerfile context for sonobuoy. In otherwords, we need to put
the built sonobuoy binary in the build/sonobuoy directory.

Fix the build

---

.gitignore
build/sonobuoy/Makefile

- Run the container build with `build/sonobuoy` as the working directory
- Fix the `local` target to not depend on `sonobuoy` already existing
(fixes running `make` on a freshly cloned repo)
- Drop old outputs from gitignore

Makefile fixes

---

docs/configuration.md
pkg/config/loader.go

Allow the environment variable RESULTS_DIR to take precedence over the configuration file.
This is an infrastructure change to move along the `done` file work.

Customizable resultsDir

---

build/sonobuoy/run_master.sh
pkg/config/loader.go

Once Sonobuoy is finished running it writes the path of the results tarball
into a done file located in the results directory (as configured via
the config file or an env var).
The goal of this is to be able to react to a finished sonobuoy run and
do something interesting with the results. For instance, one could
upload the results to S3 for permanent storage and need not create a long
lived volume for sonobuoy specifically.

Implement the done file interface

---

README.md
docs/build-from-scratch.md
docs/conformance-testing.md
examples/quickstart/10-configmaps.yaml
examples/quickstart/20-pod.yaml

@timothysc @kensimon PTAL
This PR:
* Updates the build status button to `tag-deployer` instead of `master-deployer`. Let me know if this doesn't make sense.
* Attempts to clarify the YAML/`kubectl apply` issue around https://github.com/heptio/sonobuoy/issues/30.
* Attempts to clarify conformance tests configs in the Quickstart, based on feedback in https://github.com/heptio/sonobuoy/issues/26.
* Fixes some typos.

[docs] Clarify Quickstart conformance tests and potential error after kubectl apply

---

docs/configuration.md
examples/quickstart/20-pod.yaml

We're encouraging using `kubectl cp` in the meantime, using host mounts
was a temporary measure.
This fixes an issue where the documented `kubectl cp` command is
bringing in tarballs from previous runs.

Don't mount /tmp as host volume in example pod

---

README.md
docs/plugins.md

@kensimon @timothysc PTAL This is meant to address the confusion raised in https://github.com/heptio/sonobuoy/issues/42.
Please see the [formatted markdown](https://github.com/abiogenesis-now/sonobuoy/blob/20870e11b922b0f6d07beb55f1c7b825d4303a93/README.md#2-run)! I'm not 100% sure that the quote block works----I wanted to visually highlight some important points and also show that they weren't "part of the steps". Let me know your thoughts.

[docs] README clarifications for error handling and sonobuoy no-exit

---

pkg/plugin/aggregation/aggregator.go
pkg/plugin/aggregation/aggregator_test.go
pkg/plugin/aggregation/server.go
pkg/plugin/aggregation/server_test.go
pkg/plugin/driver/daemonset/daemonset.go
pkg/plugin/driver/job/job.go
pkg/plugin/driver/utils/utils.go
pkg/plugin/interface.go
pkg/worker/worker.go
pkg/worker/worker_test.go

This makes it so plugins upload to a path like:
```
/api/v1/results/global/e2e.tar.gz
```
And it will show up in:
```
/results/plugins/e2e/results/<contents>
```
(For single-node plugins, this would map to:)
```
/results/plugins/systemd_logs/node1/<contents>
```
This needs to be documented along with the snapshot documentation that
is already under review.
Since the upload path is now expected to have a file extension in it, In
case for some reason the sonobuoy master launches with an old version
of the sonobuoy worker (or for plugins not using `sonobuoy worker` that
upload their own contents), if the path has no file extension, it is
guessed to be `.json` or `.tar.gz`, same as before.

Implicitly extract tar.gz files from plugins that upload them

---

pkg/plugin/loader/loader.go

Sonobuoy looks at the extensions of the files the configmap defines
and uses a loader implementation to Unmarshal the bytes into a struct.
Both YAML and JSON are supported with respective file extensions of .yaml and .json.

Supports JSON configs

---

Godeps/Godeps.json
cmd/sonobuoy/app/master.go
cmd/sonobuoy/app/root.go
cmd/sonobuoy/app/worker.go
pkg/config/loader.go
pkg/discovery/discovery.go
pkg/discovery/pods.go
pkg/discovery/queries.go
pkg/discovery/utils.go
pkg/errlog/errlog.go
pkg/plugin/aggregation/aggregator.go
pkg/plugin/aggregation/run.go
pkg/plugin/aggregation/server.go
pkg/plugin/driver/daemonset/daemonset.go
pkg/plugin/driver/job/job.go
pkg/plugin/interface.go
pkg/plugin/loader/loader.go
pkg/worker/config.go
pkg/worker/request.go
pkg/worker/worker.go
vendor/github.com/pkg/errors/.travis.yml
vendor/github.com/pkg/errors/errors.go
vendor/github.com/pkg/errors/stack.go

Goals:
- All errors are either handled and logged, or returned (not both.)
- When we log the errors, the real source line of the actual error can be emitted with a stack trace if --debug is enabled
Whereas before, we would build up an array of errors for any time we could proceed, now we just log them and return nil.  For errors where we can't proceed, we return the error immediately.  Errors making resource queries are serialized into the tarball same as before.
Here's the strategy or how to construct/wrap/forward errors:
- Our own errors are constructed with `errors.Errorf()` to keep track of the stack trace if we need it
- Errors from non-sonobuoy code are wrapped with `errors.Wrap()` if we want to add a context message, or `errors.WithStack()` if we don't.  This guarantees that the …

Improve error handling with pkg/errors lib

---

README.md

- There's always one tarball now that we switched to emptyDir for the
example
- Link to the snapshot docs

Fix snapshot docs in README

---

README.md

Super small fix---as Joe mentioned in the product review, it's a better UX to be able to just copy and paste the tarball extract command without googling.
PTAL @kensimon @timothysc

[small][docs] Add tar command

---

Makefile

Makefile: fix docker tagging when branches have slashes

---

config.json
docs/configuration.md
examples/ksonnet/components/10-configmaps.jsonnet
examples/quickstart/aggregate.yaml
examples/quickstart/components/10-configmaps.yaml
pkg/config/config.go
pkg/discovery/queries.go
pkg/discovery/queryrecorder.go

We're storing them in /servergroups.json for now, may move this to
/server/groups.json later (and move /serverversion.json to
/server/version.json as well)

Query ServerGroups to see supported API versions

---

docs/conformance-testing.md

This just changes the documentation so the link points to the line that actually contains E2E_FOCUS in the quickstart example.

Fix link for E2E_Focus so it points to the right line

---

pkg/worker/worker.go

Fixes #75 - Cleanup stale file handle

---

docs/plugins.md

PTAL @timothysc Just a quick fix.
----
**Additional Notes**:
*This is not the ideal fix*---ideally we'd be using some sort of `include` functionality so that the docs would be pulling from actual code (rather than this manual copy-paste job which gets out of date).
I'm punting on that for now because there are two possible solutions:
1. Adding a build process and validation process with the `npm` package [`markdown-include`](https://www.npmjs.com/package/markdown-include)
2. Just porting docs to a static site generator like Jekyll/Hugo
Because we might end up doing (2) soon, I don't want to put in the effort for (1) yet. Let me know if you think otherwise.

[docs] Fix plugin example

---

pkg/plugin/loader/loader.go

Adds more logging to debug #30.  Right now nothing in the control-flow stands out as a potential issue.  I'm hoping @gamename might have some cycles to repro once this patch has merged.  
I have not seen this issue on my cluster(s).  

Adds more logging at different points of plugin loading

---

examples/ksonnet/components/20-pod.jsonnet
examples/quickstart.yaml

Fixes: #30 
We we able to repro the issue that was reported and this should fix the problem.  
Don't cross the streams, or overlap the mounts. 

Fixes the overlapping mount issue of plugins

---

README.md

Attempts to address https://github.com/heptio/sonobuoy/issues/101, PTAL @timothysc 
Let me know if this is what you were thinking of, and if this is the appropriate place in the README to put it.

[docs] Add supported version table

---

Makefile

@chuckha this will fix the build artifacts to have proper tagging, eg - :v0.9.0

Fix tagging for build artifacts

---

docs/configuration.md
examples/ksonnet/components/10-configmaps.jsonnet
examples/quickstart.yaml
pkg/config/config.go

We have learned that the default timeout was too low after seeing a variety of
sonobuoy runs across many clusters.
Closes #112

Increase timeout to 90 minutes

---

.travis.yml
Makefile

Add travis support

---

.travis.yml
Makefile
pkg/config/loader_test.go
pkg/discovery/queryrecorder.go
pkg/errlog/errlog.go
pkg/plugin/aggregation/aggregator_test.go
pkg/plugin/aggregation/run.go
pkg/plugin/interface.go

Our tests should vet, lint, and otherwise verify the hygiene of our code before we allow it into master

Add vet to tests

---

Dockerfile
Makefile

Fixes: #71 
/cc @liztio for review.

Update targets and images to use our internal golang 1.9 images

---

Dockerfile

Update working directory to be / by default

---

.gitignore
Makefile
examples/ksonnet/components/20-pod.jsonnet
examples/ksonnet/dev.jsonnet

Refactor 20-pod.jsonnet to take a few parameters
Closes #107

Add a `make dev` to output a development manifest

---

Makefile
README.md

By default, this change does nothing. But f you run the tests with `VERBOSE=""`, you can quiet most of the test output down to the bare essentials.
Before:
```
make test | tee >(wc -l)
docker run --rm -v /Users/liz/src/github.com/heptio/sonobuoy:/go/src/github.com/heptio/sonobuoy -w /go/src/github.com/heptio/sonobuoy gcr.io/heptio-images/golang:1.9-alpine3.6 /bin/sh -c 'go build -o sonobuoy "-v" -ldflags "-X github.com/heptio/sonobuoy/pkg/buildinfo.Version=v0.9.0-12-g1951106 -X github.com/heptio/sonobuoy/pkg/buildinfo.DockerImage=gcr.io/heptio-images/sonobuoy:19511061" github.com/heptio/sonobuoy/cmd/sonobuoy'
github.com/heptio/sonobuoy/pkg/buildinfo
github.com/heptio/sonobuoy/vendor/github.com/gogo/protobuf/proto
github.com/heptio/sonobuoy/vendor/github.com/c2h5oh/datasize …
```

Optionally make the tests quieter.

---

.travis.yml
Makefile
README.md

By default, `make test` should be quiet. But verbose logging is enabled on Travis, to make errors easier to spot.

Testing should be quiet by default.

---

docs/conformance-testing.md

The conformance testing docs linked to incorrect lines in the quickstart yaml file. This corrects the references.

Fix some line-specific doc references

---

CHANGELOG.md
README.md

(Was doing this for ksonnet, and noticed that we're using Github's releases feature instead of a `CHANGELOG.md` file).
Updated the README to match.
@timothysc fyi

[docs] Update releases link in README

---

Makefile
pkg/config/config.go
pkg/config/config_test.go
pkg/discovery/discovery.go
pkg/discovery/queries.go

This helps when diagnosing issues that arise on failed/wedged tests
Fixes: #81 
I'm still testing this atm, but comments welcome.

Updates sonobuoy to always collect data for it's namespace.

---

pkg/discovery/queries.go

Fixes #149
This will cause a fallback to previous api-groups on 1.7, default check is for 1.8  
/cc @rosskukulinski 

Updates to try latest then previous api versions, for different queries

---

examples/ksonnet/components/10-configmaps.jsonnet
examples/quickstart.yaml
plugins.d/e2e.jsonnet
plugins.d/e2e.tmpl
plugins.d/heptio-e2e.jsonnet
plugins.d/heptio-e2e.tmpl
plugins.d/systemd_logs.jsonnet
plugins.d/systemd_logs.tmpl

By adding the Exists operator to the toleration we ensure
that we will schedule a systemd pod on the master node in cases
when the master label actually has a value. `...=true:NoSchedule`.
Using the quickstart on an azure cluster I get this output:
```
$ k get po -n heptio-sonobuoy
NAME                                READY     STATUS              RESTARTS   AGE
sonobuoy                            1/1       Running             0          8s
sonobuoy-e2e-job-73ed9d10e8e84d56   0/2       ContainerCreating   0          5s
systemd-logs-1l2rd                  0/2       ContainerCreating   0          5s
systemd-logs-41q5c                  0/2       ContainerCreating   0          5s
systemd-logs-sqspn                  0/2       ContainerCreating   0          5s
$ k get nodes
NAME …
```

Make the toleration more flexible

---

pkg/discovery/queryrecorder.go

QueryData will be reused in the client library.
Related to #97

Export QueryData

---

docs/conformance-testing.md

This captures two changes:
1) A fix on the documentation to link to the .tmpl file instead of the non-existant .yaml file
2) A change to use relative paths in the markdown to allow for forks/branches to reference their own version of the document instead of linking to Heptio's master branch.

Documentation Fix

---

README.md

The previous command copies the result `.tar.gz` into a directory
called `./archive`, so we should extract it from there as well.
Signed-off-by: Christie Wilson <bobcatfish@gmail.com>

Fix README results extraction example

---

pkg/plugin/driver/daemonset/template.go
pkg/plugin/driver/job/template.go
pkg/templates/manifest.go
scripts/run_single_node_worker.sh

Single node workers need to have a long sleep because after they finish, regardless of their exit status, they are managed by a daemon set. A daemonset requires that pods always be restarted after they finish so we add a sleep. I think what we really want to do is add a taint to the node after they finish running and then clear taints after the whole thing is done. However, we'd need the alpha feature TaintBasedEvictions enabled so until that becomes GA we probably won't go down this road.
Anyway, this is some cleanup that will make my work with managing signals much nicer.
(running a command wrapped in `/bin/sh -c /cmd/to/run` doesn't pass signals down and therefore we can't intercept them and react to them.
* Wraps daemonset sleeps in a bash command
* Call sonobuoy directly so we can …

Cleanup of worker commands

---

cmd/sonobuoy/app/master.go
pkg/discovery/discovery.go
pkg/discovery/utils.go

Fixes #257 
```
Sonobuoy has to perform a couple of operations before actually starting
a test. Instead of panicking when one of these ops fails, return an
error and exit with a non-zero exit code.
Signed-off-by: Alexander Brand <alexbrand09@gmail.com>
```
Failure output sample:
```
INFO[0000] Scanning plugins in ./plugins.d (pwd: /Users/abrand/go/src/github.com/heptio/sonobuoy)
INFO[0000] unknown template type                         filename=e2e.jsonnet
INFO[0000] unknown template type                         filename=heptio-e2e.jsonnet
INFO[0000] unknown template type                         filename=systemd_logs.jsonnet
INFO[0000] Scanning plugins in /etc/sonobuoy/plugins.d (pwd: /Users/abrand/go/src/github.com/heptio/sonobuoy)
INFO[0000] Directory (/etc/sonobuoy/plugins.d) does not …
```

Exit with an error instead of panic

---

cmd/sonobuoy/app/worker.go
pkg/plugin/aggregation/run.go
pkg/plugin/constants.go
pkg/plugin/driver/job/job.go
pkg/worker/worker.go

* Handles a SIGTERM (pod deletion) more cleanly
* Increased job grace period to 60 seconds
* Tells plugins to cleanup 60 seconds before shutting down the aggregation server
fixes #214

Handle signals from kubernetes

---

cmd/sonobuoy/app/args.go
cmd/sonobuoy/app/gen.go
cmd/sonobuoy/app/operations/status.go
cmd/sonobuoy/app/status.go
pkg/plugin/aggregation/run.go
pkg/plugin/aggregation/update.go
pkg/plugin/aggregation/update_test.go

Example status:
```
+--------------+-----------------------------+----------+
|    PLUGIN    |            NODE             |  STATUS  |
+--------------+-----------------------------+----------+
| e2e          |                             | running  |
| systemd_logs | ip-10-0-18-159.ec2.internal | complete |
| systemd_logs | ip-10-0-22-130.ec2.internal | complete |
| systemd_logs | ip-10-0-22-8.ec2.internal   | complete |
+--------------+-----------------------------+----------+
|                                              RUNNING  |
+--------------+-----------------------------+----------+
```
closes #209

Sonobuoy status

---

pkg/templates/manifest.go

The YAML is missing a `---` without this change and with EnabledRBAC = false.

Adds YAML separator in generated YAML

---

pkg/discovery/discovery.go

Sonobuoy has captured everything interesting and has created the results.
No more logs should be written to disk at this point.
We are stuck referencing the standard logger as that's what we've been using across the rest of sonobuoy.

Remove logrus hooks at the end of the run.

---

cmd/sonobuoy/app/status.go

```
$ sonobuoy status
PLUGIN		NODE				STATUS
e2e						running
systemd_logs	ip-10-0-11-88.ec2.internal	complete
systemd_logs	ip-10-0-12-235.ec2.internal	complete
systemd_logs	ip-10-0-19-40.ec2.internal	complete
Sonobuoy is still running. Runs can take up to 60 minutes.
```

More friendly status messages

---

cmd/sonobuoy/app/version.go
pkg/buildinfo/version.go

Hardcodes version so `go get` has some state.

---

cmd/sonobuoy/app/status.go

@timothysc I can't remember if we're trying to do any dep limiting in cmd, but I think `sonobuoy master` is gonna pull in aggregation anyway.

Use constants for `sonobuoy status` to avoid completed errors

---

pkg/config/config.go
pkg/plugin/base.go
pkg/plugin/driver/base.go
pkg/plugin/driver/base_test.go
pkg/plugin/driver/daemonset/daemonset.go
pkg/plugin/driver/job/job.go
pkg/plugin/driver/utils/utils.go
pkg/plugin/interface.go

```
$ sonobuoy run --mode quick --sonobuoy-image gcr.io/liz-heptio/sonobuoy:imagepull
INFO[0000] created object                                name=heptio-sonobuoy namespace= resource=namespaces
INFO[0000] created object                                name=sonobuoy-serviceaccount namespace=heptio-sonobuoy resource=serviceaccounts
INFO[0000] created object                                name=sonobuoy-serviceaccount namespace= resource=clusterrolebindings
INFO[0000] created object                                name=sonobuoy-serviceaccount namespace= resource=clusterroles
INFO[0000] created object                                name=sonobuoy-config-cm namespace=heptio-sonobuoy resource=configmaps
INFO[0000] created object                                name=sonobuoy-plugins-cm …
```

Plugin refactor

---

cmd/sonobuoy/app/args.go
cmd/sonobuoy/app/rbac.go
pkg/client/mode.go

Decided to go with Title Case for things like RBAC Mode, that aligns more with the way the rest of Kubernetes works.
closes #309

Clean up help text and cases

---

cmd/sonobuoy/app/logs.go
pkg/client/interfaces.go
pkg/client/logs.go
pkg/client/logs_test.go

This change hides the concurrency from the client to
provide a familiar interface. Clients can now read
a merged stream of logs as if it were a synchronous io.Reader.

Rework logging code

---

cmd/sonobuoy/app/gen.go

here is some output from before and after
BEFORE
```
test salazar:sonobuoy cha$ go run main.go run --mode=quick
generating genconfig &{Conformance Alpha|Disruptive|Feature|Flaky|Kubectl}
mode config Quick
FOCUS!!!!!!! Conformance
^Csignal: interrupt
```
AFTER
```
test salazar:sonobuoy cha$ go run main.go run --mode=quick
generating genconfig &{Pods should be submitted and removed Alpha|Disruptive|Feature|Flaky|Kubectl}
mode config Quick
FOCUS!!!!!!! Pods should be submitted and removed
```

Fixes bug that ignored `--mode`

---

cmd/sonobuoy/app/retrieve.go
pkg/client/interfaces.go
pkg/client/retrieve.go

closes #274 and closes #313
The UX is much cleaner with no channels.
The errors from the command line no longer show extraneous information.

Improve Retrieve

---

cmd/sonobuoy/app/run.go

It's nice to know what is about to run on our cluster
so now the run command prints out the list of plugins
it is configured to tell sonobuoy to run.
Closes #317

Print out which plugins are running

---

cmd/sonobuoy/app/e2e.go
cmd/sonobuoy/app/run.go
pkg/client/interfaces.go
pkg/client/preflight.go

Checks to see if a Sonobuoy pod exists in this namespace already.
```
$ sonobuoy run
Running plugins: e2e, systemd-logs
INFO[0000] created object                                name=heptio-sonobuoy namespace= resource=namespaces
INFO[0000] created object                                name=sonobuoy-serviceaccount namespace=heptio-sonobuoy resource=serviceaccounts
INFO[0000] created object                                name=sonobuoy-serviceaccount namespace= resource=clusterrolebindings
INFO[0000] object already exists                         name=sonobuoy-serviceaccount namespace= resource=clusterroles
INFO[0000] created object                                name=sonobuoy-config-cm namespace=heptio-sonobuoy resource=configmaps
INFO[0000] created object …
```

Sonobuoy existing preflight check

---

pkg/client/gen.go
pkg/client/mode.go
pkg/templates/manifest.go

Signed-off-by: Jimmi Dyson <jimmidyson@gmail.com>
Current regexps for focus and skip were too loose and could have matched specs that they weren't supposed to match against. For example, old focus default was `Conformance` which would have matched any specs with `Conformance`, whereas this should match against `[Conformance]` as per conformance suite description:
> The standard set of conformance tests is currently those defined by the [Conformance] tag in the kubernetes e2e suite.
This also updates the default skip regexp, without changing the intended set of specs to be skipped.
- Sorry not created one.
Hope that this is self-explanatory. Note also the switch to single quotes in …

Fix up default focus/skip regexps

---

cmd/sonobuoy/app/args.go
cmd/sonobuoy/app/gen.go
pkg/client/gen.go
pkg/client/interfaces.go
pkg/client/mode.go
pkg/config/config.go
pkg/plugin/driver/base.go
pkg/templates/manifest.go

To speed up test runs by enabling option of parallelism via ginkgo (requires heptio/kube-conformance#17 to be merged and released before this to be functional).
This also enables specifying the kube-conformance image which I needed during development cycles, but could be useful for people running other e2e images.
Plus this switches to use single-quotes YAML strings in templates to fix using e.g. `\[Serial\]` in skip/focus (YAML doesn't like non-escaped backslashes in double quotes strings so easier to switch to single-quoted to not require escaping at all.
Um, I haven't raised one...
We'd love to get this in ASAP so we can start using it for all our CI needs. We currently have …

Parallel e2e

---

pkg/buildinfo/version.go

Bumps the default versions which are used by `go get` operations.
none
```
NONE
```

Version bump for rc.1

---

.goreleaser.yml

Fixes #383
Fixes broken release tagging
- Fixes #383 
```
```

Goreleaser no longer strips v in version

---

cmd/sonobuoy/app/run.go

Right now `sonobuoy run` outputs a message like:
`$ sonobuoy run 
Running plugins: e2e, systemd-logs`
But if you're using a config, this message doesn't take that into account: 
```
sonobuoy run --config sonobuoy.json
Running plugins: e2e, systemd-logs
...
$ cat sonobuoy.json
{
"Plugins": [ { "name": "systemd-logs" } ]
}
```
This fixes that issue. 
```
$ sonobuoy run --config sonobuoy.json
Running plugins: systemd-logs
```
Issue reported by @ivan4th in slack
```
fix bug in reported plugins for `sonobuoy run`
```

Get running plugins list out of config instead of mode

---

travis-deploy.sh

This ensures that we never tag a release that doesn't match the release version in `buildinfo`
- Fixes #
```
```

Don't create release unless the sonobuoy tag matches the travis tag

---

pkg/client/gen.go
pkg/client/gen_test.go

Start with sensible defaults instead of zero values. If a config
is passed in it will merge into the default config instead of
a zero-value config.
Also tests said bugfix.
Fixes #390
- Fixes #390
```
release-note
```

Use provide defaults to a partially customized config

---

pkg/plugin/loader/loader.go

We were not actually passing extra-volumes through to the plugins loader/template filler.
- Fixes #387, hopefully
```
```

Fix bug in extra volumes handling

---

cmd/sonobuoy/app/sonobuoyconfig.go
cmd/sonobuoy/app/sonobuoyconfig_test.go
pkg/client/gen.go
pkg/client/gen_test.go
pkg/config/config.go
pkg/config/config_test.go
pkg/plugin/loader/loader.go
pkg/plugin/loader/loader_test.go

* Adds lots of tests for merging behavior
* Adds tests to some other parts of the code relating to configuration manipulation.
* Removes duplicate search paths in the default case.
- Fixes #
```
release-note
```

Fixes duplicate runs

---

README.md

I was confused when I went to submit another pull request to find the link to the contributing document actually links to the code of conduct. Looks like they just got switched around. This PR makes the CoC link point to the code of conduct, and the contrib link point to the contributing document.
Signed-off-by: Dan Miller <dmiller@windmill.engineering>

Fix CoC and contributing links

---

cmd/sonobuoy/app/rbac.go

`groups` is not a boolean (`%t`), but a pointer. I think this was meant
to print the type (`%T`).
Without this change you get the following error when running `go vet` in Go 1.10:
```
cmd/sonobuoy/app/rbac.go:108: Errorf format %t has arg groups of wrong type *github.com/heptio/sonobuoy/vendor/k8s.io/apimachinery/pkg/apis/meta/v1.APIGroupList
```
Signed-off-by: Dan Miller <dmiller@windmill.engineering>

Fix format string type error

---

Dockerfile
Makefile

This PR updates the Docker base images used for building and running Sonobuoy. It switches away from internal `gcr.io/heptio-images/golang` images to the upstream `golang` image.
These internal `gcr.io/heptio-images/golang` images are deprecated. It looks like `bash` was the only thing that the Sonobuoy runtime image needed that wasn't in the upstream `golang:1.9-alpine3.6` image.

Switch to upstream Go build images.

---

.goreleaser.yml

CGO is enabled for the linux binary because the travis env is linux/amd64 so that build is not technically cross compiled and doesn't disable cgo.
See https://github.com/goreleaser/goreleaser/issues/225
and https://github.com/goreleaser/goreleaser/blob/master/.goreleaser.yml

Disable cgo for go relesaer

---

travis-deploy.sh

I saw an error in the releaser output. My linter says there needs to be a space here. Bash.

Add missing space in bash releaser

---

cmd/sonobuoy/app/e2e.go
cmd/sonobuoy/app/gen.go
pkg/client/e2e.go
pkg/client/gen.go

**What this PR does / why we need it**
Earlier `kubeconfig` was needed to use the sub-commands `e2e` and `gen`
which is unnecessary since using these sub-commands does not require
communication to Kubernetes server.
This commit removes that necessity.
- Fixes #370 
Signed-off-by: Suraj Deshmukh <surajd.service@gmail.com>

Skip requirement of kubeconfig for e2e & gen

---

cmd/sonobuoy/app/status.go

fixes spelling in cli status command
- Fixes #
```
release-note
```

fixes spelling in status command

---

.github/bug_report.md
.github/feature_enhancement_request.md

The PR adds standardized bug and feature-enhancement templates. Starting with sonobuoy we will apply these to all repos.
- Fixes #
N/A
I will start a document to track which repos have been updated with these templates.
None
```
release-note
None
```

Added new templates.

---

pkg/discovery/queries.go

Fixes #455
But adds technical debt addressed by SEP defined in #464
When the pod logs fail to query, we were bailing early. We don't want to do that. We want to finish the function.
```
NONE
```

Log error; do not bail early

---

cmd/sonobuoy/app/status.go

Fixes #404
I can't really write a test for this, so it's kind of a best effort deal.
This returns a non-zero exit code for `sonobuoy status` when the status is that a plugin has failed.
- Fixes #404 
```
NONE
```

Return a non-zero status code for failed plugins

---

Gopkg.lock
Gopkg.toml
cmd/sonobuoy/app/retrieve.go
pkg/client/interfaces.go
pkg/client/retrieve.go
vendor/golang.org/x/sync/AUTHORS
vendor/golang.org/x/sync/CONTRIBUTORS
vendor/golang.org/x/sync/LICENSE
vendor/golang.org/x/sync/PATENTS
vendor/golang.org/x/sync/errgroup/errgroup.go

Right now `sonobuoy retrieve` provides very bad error handling. This improves it:
```
$ sonobuoy retrieve
error retrieving results: error sending request: Post https://liz-k8s-liz-d22b5dmgmt.eastus.cloudapp.azure.com/api/v1/namespaces/heptio-sonobuoy/pods/sonobuoy/exec?command=%2Fusr%2Fbin%2Fenv&command=bash&command=-c&command=tar+cf+-+%2Ftmp%2Fsonobuoy%2F%2A.tar.gz&container=kube-sonobuoy&container=kube-sonobuoy&stdout=true: dial tcp: lookup liz-k8s-liz-d22b5dmgmt.eastus.cloudapp.azure.com: no such host
zsh: exit 2     sonobuoy retrieve
```
```
$ sonobuoy retrieve
Results not ready yet. Check `sonobuoy status` for status.
zsh: exit 1     sonobuoy retrieve
```
- Fixes #407 …

Retrieve error handling

---

pkg/config/config.go

Along with the scanner update this Fixes #468
```
The default timeout increases to 3 hours
```

Bump default to 180 minutes (3 hours)

---

pkg/client/results/reader.go

Fixes #476
This PR adds a default so our results reader is making a guess instead of erroring.
```
Improved robustness for results reader
```

Default version for results reader

---

pkg/discovery/nodes.go
pkg/discovery/pods.go
pkg/discovery/queries.go

Fixes #465
The proxy subresource was moved in k8s v1.10
This fixes the configz and healthz outputs. They were null as of k8s 1.10. However, no one really noticed so I wonder how many people use or need this feature.
```
NONE
```

Updates node configz and healthz endpoints

---

cmd/sonobuoy/app/args.go
cmd/sonobuoy/app/gen.go
cmd/sonobuoy/app/imageversion.go
cmd/sonobuoy/app/imageversion_test.go
cmd/sonobuoy/app/run.go
pkg/config/config.go

Sonobuoy will now detect the server's version and try to run the appropriate conformance container
- Fixes #444 
```
sonobuoy run automatically detects server version, gen uses latest
--kube-conformance-image-version has several possible arguments:
auto queries the server version and uses that
latest uses the `latest` tag
a literal version (e.g. v1.10.2) always uses that
```

Autodetect version

---

pkg/worker/request.go
pkg/worker/request_test.go

PesterClient wasn't being used for success retries, only for failure
- Fixes #225 
```
```

Use pester for callback requests

---

cmd/sonobuoy/app/imageversion.go
cmd/sonobuoy/app/imageversion_test.go

Bug fix on run b/c we don't release *.patch versions
See https://github.com/heptio/kube-conformance/issues/25
```
None
```
/assign @chuckha @liztio

Sets version image to use vMajor.Minor b/c we don't match all .Patch releases

---

cmd/sonobuoy/app/rbac.go

The usage information for `--rbac` is incorrect. It specifies `Enable` instead of `Enabled` as the correct argument value. This updates the `EnabledRBACMode` value from `Enabled` to `Enable` to maintain consistency with the `Disable` and `Detect` RBAC modes.

use 'Enable' vs 'Enabled' for RBAC mode

---

README.md
docs/conformance-testing.md
pkg/buildinfo/version.go
pkg/config/config.go
pkg/plugin/aggregation/run.go
pkg/plugin/aggregation/update.go

Fixes annotation updater issue(s).
- Fixes #488
I still need to run some tests on this to verify.   
```
Will try to always update annotations on every exit condition. 
```
/assign @liztio

bugfix for annotation updater.

---

cmd/sonobuoy/app/common.go

Fixes a condition where getSonobuoyClient(cfg *rest.Config) can be called with a nil cfg 
Which is a normal condition that can occur for offline tarball analysis.
- Fixes #498
none
```
None
```
/assign @chuckha 
/cc @scottslowe

Quick fix for an empty config SEGV on nil rest.Config bug

---

cmd/sonobuoy/app/imageversion.go
cmd/sonobuoy/app/imageversion_test.go

GKE has a weird version: `version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.5-gke.3", GitCommit:"6265b9797fc8680c8395abeab12c1e3bad14069a", GitTreeState:"clean", BuildDate:"2018-07-19T23:02:51Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}`
The `10+` breaks running tests. To avoid this, we use the segments from the GitVersion. 
- Will eventually solve #501 
```
```

Support GKE's weird 10+ versions

---

Dockerfile
Makefile

Signed-off-by: Bin Lu <bin.lu@arm.com>
add arm64 support 
- Fixes #181
```
release-note
```

push images with multi-arch to support amd64/arm64

---

pkg/discovery/queries.go
pkg/plugin/driver/daemonset/daemonset.go
pkg/plugin/driver/daemonset/daemonset_test.go
pkg/plugin/driver/daemonset/template.go

Our internal daemonset templates are really old, and I was surprised it worked.  
This partially addresses overlaps with #507 as well.
I need to test this some more to verify. 
```
NONE
```
/assign @liztio

When inspecting another changeset I found our internal template to be old

---

Makefile

Adds a vMajor.Minor tag to reference in things like scanner to prevent PRs on shifts. 
- Fixes #499
```
NONE
```
/assign @liztio @chuckha

Adds a mutable Major.Minor tag for scanner

---

.travis.yml
travis-deploy.sh

Travis CI has suggested a fix for the git pull issue

---

pkg/buildinfo/version.go

Updates the latest revision to v0.11.5 
```
NONE
```

Update to v0.11.5

---

pkg/config/loader.go

This change adds brackets around the ip address when it is learned. This
is compatible with ipv4 and ipv6 setups.
Before this change if you ran sonobuoy in an ipv6 cluster the
aggregation mechanism would break with logs like:
```
13:10 $ sonobuoy e2e ipv4_with_ipv6_fix.tar.gz --show passed
passed tests
[k8s.io] Pods should be submitted and removed [NodeConformance] [Conformance]
```
preventing the sonobuoy pod from marking any plugin complete.
After this change the url passed to the aggregator handler will have the
ip address bracketed.
This was tested with kubeadm-dind in both ipv4 and ipv6 configurations.
An example sonobuoy container with this fix is located here:
quay.io/mauilion/sonobuoy:ipv6_fix
You can test this locally with:
```
wget …
```

Add ipv6 support to sonobuoy

---

pkg/templates/manifest.go

Some tests in the Kuberentes E2E suite require hitting
non-resource URLs which have to be listed as separate
rules in the ClusterRole definition.
There are some E2E tests that require access to non-resource URLs. Ticket #526 listed one of them which was the basis for choosing this set of URLs.
- Fixes #526
The ticket originally mentions needing just `/metrics` but when retesting with that added the tests would complain about `/logs` and after adding that it complained about needing `/logs/`.
I left the changes with this minimal set of added privileges but I would understand if we'd rather just add more to try and prevent other situations similar to this. I'm not sure how the team …

Add metrics and logs non-resource URLs to RBAC rules

---

pkg/plugin/driver/daemonset/template.go

This adds the sonobuoy serviceaccount to the daemonsets so they have same permission as jobs
- Fixes #551 
```
release-note
```

add the sonobuoy serviceaccount to daemonsets

---

README.md
cmd/sonobuoy/app/gen.go
cmd/sonobuoy/app/imageversion_test.go
docs/conformance-testing.md
pkg/buildinfo/version.go

Signed-off-by: Ruben Orduz <rubenoz@gmail.com>
It updates sonobuoy to support version 1.13
- Fixes #561 
```
Sonobuoy has been updated to support Kubernetes version 1.13.x. Support for Kubernetes version 1.10.x has been removed.
```

Version bump

---

docs/release.md

Adding instructions to release doc to watch for go releaser successful completion in Travis job

Release doc fix

---

latest/README.md

Last commit added front matter to the readme page which
broke the preprocessor. This change removes that.
It also moves the build status line below the header so that
the title in the browser does not include that markdown (a
jekyll plugin is creating the title from the first header).
So this gets the site up and fixes the title with the
cost of having the github pages build status shown in a
slightly different place than on the github repo page.

Fix front matter issue

---

cmd/sonobuoy/app/status.go
pkg/client/status.go
pkg/discovery/discovery.go
pkg/plugin/aggregation/status.go
pkg/plugin/aggregation/status_test.go
pkg/plugin/aggregation/update.go

If your plugin artifacts are large then it will take
a few seconds for the tarball to be created. However,
the aggregator marks the pod status as done and
therefore there can be a few seconds where the
status reports that results are ready for download
but you will wither get a "file does not exist" error
or a tarball locally that is only partially complete
and most likely corrupted.
Fixes #572
In order to repro this you need to have large artifacts (as if you had a multi-node cluster running tests for numerous hours. This can easily be repro'd by using a custom kube-conformance image I created which took a dryrun result and then repeated it 2^15 times (image is available publicly …

Acknowledge state between plugins complete and done

---

Makefile
cmd/sonobuoy/app/version.go
pkg/buildinfo/version.go

Fixes #518 by adding additional version information:
- MinimumKubeVersion supported by this version of Sonobuoy
- MaximumKubeVersion supported by this version of Sonobuoy
- GitSHA
- K8S version (if kubeconfig is passed)

Update version command to print GitSHA, Min/Max K8S Versions

---

cmd/sonobuoy/app/e2e.go
pkg/client/e2e.go
pkg/client/e2e_test.go

- when no tests reported, we make that clear by showing
the number in addition to the list
- when no tests reported, ensure we dont have an unnecessary
empty line
Fixes #380
```
Clarifies the output from `sonobuoy e2e`
```

Provide more clear output from sonobuoy e2e

---

cmd/sonobuoy/app/args.go
cmd/sonobuoy/app/delete.go
cmd/sonobuoy/app/run.go
pkg/client/delete.go
pkg/client/interfaces.go
pkg/client/run.go

Currently running a sonobuoy run takes significant time and
the user is left to poll the status on their own. In a
CI environment this is especially true.
Deleting, likewise, takes some time since cleaning up
namespaces in k8s is not always fast.
This PR introduces wait options to run/delete and allows
customizable timeouts to the wait behavior.
Fixes #568
Fixes #437
```
Adds --wait flag to run and delete commands.
```

Add wait flags to run and delete

---

pkg/plugin/driver/daemonset/daemonset.go

Fix small go vet issue which is being missed somehow with current `make test` logic. 

Fix go vet error in daemonset.go

---

cmd/sonobuoy/app/retrieve.go
pkg/client/retrieve.go

When the user calls sonobuoy retrieve they are given no output
and then left to figure out if they got any files and what their
name is.
As someone who runs this a lot I'd like to be able to know more
easily what files were created so that I can script around them
or more easily grep for the "new" file in a sea of older tarballs.
Fixes #594
Nothing greatly testable here; in the error case it doesnt print the names. Otherwise it prints the list, one file per line.
```
sonobuoy retrieve now prints the local files it creates to stdout
```

List files created by retrieve command

---

.gitignore
.travis.yml
Makefile
kind-config.yaml
travis-ci.sh

This PR now builds a kind cluster inside travis, runs the E2E tests and checks for a valid result. We'll need to see if this should be a 2nd job or have a bot only run occasionally since it will take some time to run. 
- Fixes #250 
```
release-note
```

Run E2E tests inside a kind cluster

---

.travis.yml
Makefile
README.md

Updates go with the new release of 1.12. Go 1.10 is no longer supported.
- Fixes #610
Not sure the exact reason CGO_ENABLED=0 needs set for `go vet` but I do know it was partially touched based on the release notes stating that `go tool vet` was now deprecated.
Also, I know #609 mentions building based on debian slim but I am assuming that it only matters for the actual images we are shipping, not this which is just for producing the artifacts. #609 will be addressed separately.

Update to go1.12

---

README.md
cmd/sonobuoy/app/args.go
cmd/sonobuoy/app/gen.go
pkg/client/gen.go
pkg/client/interfaces.go
pkg/templates/manifest.go

K8s 1.13 organized and allowed overrides for where to pull
e2e images from. The env var needed is KUBE_TEST_REPO_LIST.
To facilitate users providing this, the following changes
have been made:
- the user can specify a file path on the command line with
the proper contents
- the file is read
- the contents are used to create a configmap of the values
- the configmap is mounted as a volume for the kube-conformance
container
- the env var KUBE_TEST_REPO_LIST is set to point to this file
Fixes #160
Personally to test this I just pulled from `docker.io/library` (the nginx:1.14-alpine which is used by the quick mode test), tagged it as `schnake/nginx:1.14-alpine`, pushed to the public …

Add support for KUBE_TEST_REPO_LIST and custom registries

---

cmd/sonobuoy/app/gen.go
cmd/sonobuoy/app/gen_test.go
cmd/sonobuoy/app/imageversion.go
cmd/sonobuoy/app/imageversion_test.go
pkg/config/config.go

Transition to using the upstream conformance image. They started
publishing it after v1.13.0 so for versions before that we still
need to support the heptio/kube-conformance image.
This PR adds the conditional logic for choosing the right image
as well as extends the version-getting logic so that for versions
at/after v1.13 we provide all 3 segments of the semver since
we now track exactly with each release.
Fixes #593
```
This changes Sonobuoy to use the upstream Kubernetes conformance image if: the version requested is >= v1.13, latest, or auto and the server reports a version >= v1.13.
```

Use upstream conformance image when >= v1.13

---

cmd/sonobuoy/app/args.go
cmd/sonobuoy/app/gen.go
cmd/sonobuoy/app/gen_test.go
cmd/sonobuoy/app/imageversion.go
cmd/sonobuoy/app/run.go

There exists a bifurcation in the kube-conformance logic
which is unintuitive and potentially damaging to the user
experience.
Currently, if they use sonobuoy gen the kube-conformance
version is defaulted to `latest` but if they use sonobuoy run
it is defaulted to `auto`. The problem is that one may work
on a cluster while the other will not: leaving users in a
situation where run will work but gen -> kubectl apply will
not without an indication why.
This change causes the two to be in sync. The downside is that
there are cases where you may run sonobuoy gen without a
current KUBECONFIG, so now sonobuoy gen will fail.
The error is descriptive and the workaround is to provide the
image version you want explicitly rather than falling back to
latest …

Default to 'auto' for gen command

---

docs/airgap.md

The etcd registry was missing from the example so if users would use it as a base, the etcd image would not get updated properly. This just updates to make the examples whole. 

Add missing registry entry for airgap example

---

cmd/sonobuoy/app/args.go
cmd/sonobuoy/app/gen.go
cmd/sonobuoy/app/images.go
cmd/sonobuoy/app/root.go
pkg/client/version.go
pkg/image/imageversion.go
pkg/image/imageversion_test.go
pkg/image/manifest.go
pkg/image/v1.13.go

Allows users to see what images are used in upstream e2e tests by adding a new command: `images e2e`.
- Fixes #604
```
release-note: Adds a new command `images e2e` which shows all upstream images used for E2E plugin tests. 
```

Show list of images used for upstream Kubernetes E2E tests

---

Makefile
pkg/client/retrieve.go

Updates the images we use when building Sonobuoy.
For the build image this also updates go from
1.12.0 to 1.12.1.
Due to the fact that golang doesnt offer a
stretch-slim image, the 1.12.1 stretch image
is used.
Stretch slim seems to come with what it needs
so the dockerfile CMD1 can just be removed. For
ease of future changes I left the CMD1 in place and,
just like on arm64, we just remove the line rather
than replace it.
Fixes #609

Replace alpine with debian-slim

---

cmd/sonobuoy/app/gen_test.go
pkg/config/config.go

The worker's default image was using a hardcoded
value and not referencing the const that was
defined for that purpose leading to the
aggregator and worker using different images.
* Notes for reviewer
A seemingly minor problem, I worry about what some of the edge cases might be if we have different defaults there. It could lead to some awkward behavior if we have a few point releases.
I _know_ we need to also add more tests but this is a tiny bug with an obvious cause. We need to spike eventually on improving testing of gen input/output.
Fixes: #643

Use default image for worker

---

pkg/image/manifest.go
pkg/image/v1.14.go

Adds a list for v1.14 Kubernetes. Only
one change, the version for the liveness
image.

Add image list for v1.14 Kubernetes

---

cmd/sonobuoy/app/args.go
cmd/sonobuoy/app/version.go
travis-deploy.sh

Our release scripts hinged on checking a version
which recent changes complicated slightly. We
need this to have a sanity check we release
the right versions.
```
Adds a new --short flag to the version command to just see Sonobuoy's version.
```

Add a short version option for scripting

---

travis-deploy.sh

Testing that we've added leaves a few artifacts around
which mess up the porcelain state goreleaser wants.
For the time being we're just going to remove the
validation.

Skip goreleaser validation

---

docs/airgap.md
docs/plugins.md

In addition to the test images the users need
the conformance and sonobuoy images. Created a section
showing this and also an example script for how to pull,
tag, and push the images.

Add additional documentation about testing in airgap

---

cmd/sonobuoy/app/args.go
cmd/sonobuoy/app/args_test.go

When creating a run and using the focus/skip
flags it can be common to accidently provide
an invalid regexp such as improperly escaping
certain characters or using `*` instead of
`.*` This change ensures that we are validing
and failing early to create a better user
experience.
Currently, if the user does this the sonobuoy
run will get created and the e2e plugin will
fail but you have to retrieve the output and
inspect the logs manually to see the panic
from the framework.
Fixes #615
```
Added additional client-side validation of --e2e-focus and --e2e-skip flags in order to fail earlier for the user rather than having to see the plugin fail and manually find the problem in the logs.
```

Add validation to focus/skip regexp flags

---

cmd/sonobuoy/app/master.go
pkg/discovery/discovery.go
pkg/discovery/queries.go

The CRD query did not have a properly formed
rest client leading to the wrong URLs being
used to query for CRDs. This resulted in an
error every Sonobuoy run on the aggregator.
This change fixes the issue in a backwards
compatible way by introducing a wrapper function
which properly handles the crdClient. The legacy
method is kept for 2 k8s release cycles just
in case someone is integrating against it. The
legacy method acts as if they had just passed
nil, or no crdClient, which will just err as
it did before.
Fixes #640
** Special note for reviewer **
No test added here since it is just a matter of integrating correctly with the k8s API.
To manually test this you can do the following (assuming you have a cluster up):
```
sonobuoy run …
```

Fix CRD query

---

cmd/sonobuoy/app/gen.go
cmd/sonobuoy/app/gen_test.go
pkg/image/imageversion.go
pkg/image/imageversion_test.go

Any cluster earlier than v1.14.1 that has failing e2e tests would crash and not give feedback to the user. The heptio kube-conformance image is used by default for these clusters. Starting with any cluster v1.14.1 the upstream conformance image will be used by default. 
- Fixes #655 
```
release-note: Any cluster earlier than v1.14.1 that has failing e2e tests would crash and not give feedback to the user. The heptio kube-conformance image is used by default for these clusters. Starting with any cluster v1.14.1 the upstream conformance image will be used by default. 
```

Use heptio kube-conformance image for any cluster < v1.14.1

---

cmd/sonobuoy/app/args.go
cmd/sonobuoy/app/kubeconfig.go

Some users may have multiple clusters in their config;
adding support for context is very minimal and helps
simplify their Sonobuoy integration.
Fixes #421
```
Added a `--context` flag support for passing a KUBECONFIG context whenever a `--kubeconifg` flag is supported.
```

Add context flag whenever kubeconfig flag is added

---

Makefile

With the ':=' assignment in the Makefile, the SECRET was
evaluated at the start, regardless of whether it was needed
or not to complete the recipe.
This causes an issue if you don't have the necessary
docker-credential-gcr tool which is expected to be there
for Jenkins.
This change defers the evaluation by using '=' instead and
avoids confusing error messaages when building locallly.

Defer assignment of Docker gcr.io secret

---

cmd/sonobuoy/app/common.go
cmd/sonobuoy/app/delete.go
cmd/sonobuoy/app/images.go
cmd/sonobuoy/app/logs.go
cmd/sonobuoy/app/retrieve.go
cmd/sonobuoy/app/run.go
cmd/sonobuoy/app/status.go
cmd/sonobuoy/app/version.go

This logic is repeated throughout nearly every command; this
tries to further centralize it.
The goal is to DRY up the codebase slightly making way for
further refactors to increase testability and test coverage
of the entire project.
Related to #651
Small change but I just wanted to keep it very focused for an easy review. More refactor/testability changes will be coming.

Centralize the process of going from kubeconfig to sonobuoy client

---

cmd/sonobuoy/app/envvars.go
cmd/sonobuoy/app/gen_plugin_def.go
cmd/sonobuoy/app/gen_plugin_def_test.go
cmd/sonobuoy/app/plugindriver.go
cmd/sonobuoy/app/root.go
cmd/sonobuoy/app/testdata/pluginDef-container.golden
cmd/sonobuoy/app/testdata/pluginDef-env.golden
cmd/sonobuoy/app/testdata/pluginDef-quotes.golden
cmd/sonobuoy/app/testdata/pluginDef-sonoconfig.golden
pkg/plugin/loader/loader.go
pkg/plugin/manifest/manifest.go

When creating a plugin there are two main steps:
- generating the plugin manifest
- putting that manifest into the `sonobuoy gen` YAML to run it
This addresses the first point. Using this command we can generate
the boilerplate YAML for most standard plugins. It allows
customizing the plugin type, name, image, command, and env vars.
Fixes #665
```
Added `gen plugin` command to generate plugin manifest for custom plugins.
```

Add `gen plugin` command to generate boilerplate for plugins

---

pkg/client/gen.go
pkg/client/gen_test.go
pkg/client/testdata/default.golden
pkg/client/testdata/e2e-default.golden
pkg/client/testdata/ssh.golden
pkg/client/testdata/systemd-logs-default.golden
pkg/plugin/manifest/manifest.go
pkg/templates/manifest.go

Currently, the template for the initial YAML (via sonobuoy gen)
has it hardcoded that both the e2e and systemd-logs plugin are
configured. This is 1) misleading to users who might see this and
think both are going to be run and 2) brittle.
With upcoming changes wanting to make the plugin list more
variable, it makes sense to put this change first: go ahead and
track a plugin list and adjust the template to iterate over the
plugins, inserting their YAML each time.
This makes the YAML more clear, flexible, and in some cases shorter.
Fixes #672
```
`sonobuoy gen` output will now reflect only the set of plugins you are selecting to run instead of always generating the e2e and systemd-logs …
```

Change logic in template to use a list of plugin manifests

---

cmd/sonobuoy/app/gen_plugin_def_test.go
cmd/sonobuoy/app/testdata/pluginDef-env.golden
cmd/sonobuoy/app/testdata/pluginDef-quotes.golden

The ordering of YAML lists is not well defined and so this passed
tests locally and in CI by chance. Even trying to repeat the
flakiness failed at first because I was hitting the testing cache.
Removing the 2nd end var does little to limit the value of the test
and we also have functional tests (e2e integration tests) which
will hit this flow.

Fix flaky unit test

---

cmd/sonobuoy/app/root_test.go

The CLI code has very low code coverage which indicates
that it has lots of areas potentially containing bugs.
However, a large chunk of the code in the CLI is just
boilerplate that sets up cobra commands and doesn't
execute much actual logic.
The point of this test is to have a code flow go through
those so that code coverage better reflects actual,
substantive code.
Relates to #651
```
N/A
```

Add test that will run through command creation

---

pkg/plugin/loader/loader.go
pkg/plugin/loader/loader_test.go
pkg/plugin/loader/testdata/onlyvalid/daemonset.yaml
pkg/plugin/loader/testdata/onlyvalid/job.yml

The aggregator has a plugin filtering mechanism that
seems to actually complicate things for most users. Beyond
adding their plugin to the config map, they also have to
adjust the plugin selection.
This seems to have originated due to a desire for
flexibility (before knowing we needed it or not) and also
ease of testing.
This change just introduces special handling for the nil
selection (not empty, completely nil). In that case, all
plugins are run which are loaded.
ref #405
I copied some plugin manifests in the testing directory because otherwise, you get an error when you try and run the invalid manifest.
```
The aggregator pod will now run all plugins found in …
```

Run all loaded plugins by default

---

pkg/client/preflight.go
pkg/client/preflight_test.go

The typical flow for Sonobuoy involves creating a new namespace
and it is uncommon to need to put it into an existing namespace.
When that occurs, cleanup must be manual since Sonobuoy by default
just deletes the namespace.
This tightens the precheck to error on the existing namespace. In
situations where that is still desired, preflight checks can be
skipped.
Refactored the logic some so that tests could be added for preflight
checks.
Fixes #677
```
Preflight checks will not fail if the namespace Sonobuoy is targeting already exists. This helps avoid a situation where a user must manually cleanup a Sonobuoy run in order to avoid destroying the namespace.
```

Tighten preflight check to err on existing namespace

---

README.md
cmd/sonobuoy/app/gen_config.go
cmd/sonobuoy/app/root.go
docs/sonobuoy-config.md

The Sonobuoy config file is a little mysterious to most
users since the values are only really defined in code
and not well documented.
This change adds a command to output the default config
so that users might tweak the values they need more
easily.
In addition, I updated the documentation to make it more
clear for everyone what the configuration file is and
how each of the fields are used.
Fixes #661
```
Added "sonobuoy gen config" command to see the default config that is passed to the server and added documentation about each field. This helps any user utilize the customizability that already exists.
```

Add sonobuoy gen config file and documentation

---

cmd/sonobuoy/app/args.go
cmd/sonobuoy/app/gen.go
cmd/sonobuoy/app/gen_test.go
cmd/sonobuoy/app/testdata/sonobuoy.conf
pkg/config/config.go
pkg/plugin/aggregation/run.go

One of the most common config settings that may change between
different environments and test cases is the amount of time
Sonobuoy will wait for results. Currently, this value is configurable
but it is in a nested config structure and not terribly well
documented at this time.
Personally, in the past, I had projects where we had to start
using a sonobuoy config-based flow instead of flags due solely
to this field.
This change adds the flag to make it more easy to set.
Fixes #482
```
Added --timeout flag to set the number of seconds Sonobuoy will wait for plugins to complete.
```

Add CLI flag for aggregation timeout

---

cmd/sonobuoy/app/gen_plugin_def.go

The value was being set in the config, but for the flag
logic to work properly, this also needed set.

Properly set default for plugin job driver

---

cmd/sonobuoy/app/gen_plugin_def.go

This is a key way in which people may customize their plugins.
Minor fixup to some language on other flags too.
Ref #405
```
Added --arg flag to `sonobuoy gen plugin` to set args on the plugin container.
```

Add ability to set args when defining a plugin

---

pkg/discovery/queries.go

In the dynamic query PR that merged recently there was a
copy/paste error which caused servergroups to get lost.
This fixes the issue and returns this functionality to its
original state.
To confirm this you can just run the master locally:
```
./sonobuoy master
```
```
NONE
```
Marking as none since it was never broken in a release.

Fix servergroups query

---

.gitignore

Goreleaser fails again because the coverage.txt file makes it think
changes have been made.
Ignores this file.

Add coverage profile to gitignore to ensure clean state after tests

---

examples/plugins/cmd-runner/Dockerfile
examples/plugins/cmd-runner/README.md
examples/plugins/cmd-runner/run.sh

With the new plugin generation/runner capabilities we needed
a new example to show users what they can do/how to do it.
This example just takes all the arguments it is given and
runs them with /bin/sh, saves the output, tars it up, and
tells the Sonobuoy worker where to find the results.
This example includes:
- the code for the plugin (a single bash script)
- the Dockerfile to build the script
- a README.md to explain what it does and how to use it
```
NONE
```

Add example for command runner plugin

---

cmd/sonobuoy/app/gen.go
pkg/client/defaults.go
pkg/client/example_interfaces_test.go
pkg/client/gen.go
pkg/client/gen_test.go
pkg/client/interfaces.go
pkg/client/run.go
pkg/client/testdata/default-plugins-via-nil-selection.golden
pkg/client/testdata/default.golden
pkg/client/testdata/e2e-default.golden
pkg/client/testdata/manual-custom-plugin-plus-e2e.golden
pkg/client/testdata/manual-custom-plugin-plus-systemd.golden
pkg/client/testdata/manual-custom-plugin.golden
pkg/client/testdata/manual-e2e.golden
pkg/client/testdata/no-plugins-via-selection.golden
pkg/client/testdata/plugins-and-pluginSelection.golden
pkg/client/testdata/systemd-logs-default.golden

Removes the redundant fields from GenConfig struct and uses the fields in Config to generate manifest.
- Fixes #691 
```
release-note
```

remove redundant fields from GenConfig

---

docs/pullsecrets.md

The process to use a private Sonobuoy image is non-trivial since
you have to create a secret in the same namespace.
In the future, if this is common, we can simplify the process but
currently, this documentation should clarify it for the few people
who need to use this flow.
Fixes #692
```
NONE
```

Add documentation about how to pull private Sonobuoy image

---

.travis.yml

Recently moved to modules and removed the vendor directory. In
order to get `go get` to work we need to ensure we are using
the modules as intended.
Fixes #713
```
NONE
```

Use go modules when getting KinD

---

docs/conformance-testing.md

Linked to a quickstart template that doesn't exist any more.
Updated it to refer to an existing example and referred the user
to how to update env vars on plugins using the sonobuoy gen command.
Fixes #711
```
NONE
```

Fix broken link in conformance doc

---

pkg/image/imageversion.go
pkg/image/imageversion_test.go

When using flags to set the kube-conformance-image-version
the `Set` method ends up stripping the `v` prefix which it
requires the user to provide.
This causes a problem because the rest of the codebase assumes
the version will start with that prefix due to the fact that that
is how images are tagged (for Sonobuoy, Heptio kube-conformance,
and for upstream conformance images).
This change just adds the prefix back after validating the version
and updates the tests to actually check for the version that
gets persisted.
Fixes #716
A simple test:
```
$ ./sonobuoy gen --kube-conformance-image-version=v1.14.0|grep conform
$ ./sonobuoy gen --kube-conformance-image-version=v1.14.1|grep …
```

Ensure conformance image version is prefixed with 'v'

---

pkg/client/logs.go

There existed an issue where if there was a problem reading the logs
of a pod it would try to put a message onto the error channel of
the logReader which was unbuffered. As a result it would block but
the problem was that the reading routine was trying to drain the
message channel first before reading errors.
The solution to this was to ensure that we sufficiently buffered the
error channel to handle these bad-reader cases. Trying to stream
from both the channels introduced issues where the messages wouldn't
be drained yet but the error would short circuit the logic causing
the logs to not get fully read.
Fixes #708
Note on the solution: I am generally highly skeptical when the …

Fix race/deadlock issues with logs when a pod is not ready

---

cmd/sonobuoy/app/args.go
cmd/sonobuoy/app/envvars_plugin.go
cmd/sonobuoy/app/envvars_plugin_test.go
cmd/sonobuoy/app/gen.go
pkg/client/gen.go
pkg/client/gen_test.go
pkg/client/interfaces.go
pkg/client/testdata/envoverrides.golden

Added a new flag and backing type in order to gather and
set env vars on any plugin from the command line which
makes it easier to iterate on plugins/tests.
This PR does the following:
- adds new flag --plugin-env and backing type
- adds new field on GenConfig in order to pass this to
pkg/client/gen/GenerateManifest(...) in order to apply
the changes after the dynamic plugins have been generated.
- adds logic to sort the env var to ensure a stable order
for testing/use
On the command line the values are of the form:
--plugin-env pluginName.env=val
Fixes #639
```
Added new flag --plugin-env allowing users to specify env var values on any plugin from the command line.
```

Set any plugin env vars from the CLI

---

pkg/plugin/aggregation/run.go
pkg/plugin/driver/job/job.go

Currently the logic of the aggregator short circuits when a
plugin fails to `Run` without error. It exits abruptly and does
not launch other plugins or report the failure on the plugin
status.
This commit changes the following behavior:
- ensures we can create all the auth certs needed before launching
any plugins, ensuring we don't fail to generate some certs after
other plugins are already running.
- when a plugin fails to Run without error, we send a failing
result so that the aggregator properly reports the status of
the plugin as an error and the results tarball shows the error
as expected.
Fixes #559
No good test for the entire logic here, I can attach some screenshots of …

Properly report error when a plugin fails to run

---

pkg/discovery/queries.go

Ordering issue in the logic caused the paths to be created even
if the queries were noops. This adds an empty-check before
creating the directories at all.
Related to #721
```
Fixed an issue which caused some query directories to be created even if queries were not run on the namespaces corresponding to those directories.
```

Don't create resource directories if not querying for resources

---

cmd/sonobuoy/app/gen_plugin.go
pkg/client/gen.go
pkg/config/config.go
pkg/config/loader.go
pkg/plugin/driver/base.go
pkg/plugin/driver/daemonset/daemonset.go
pkg/plugin/driver/daemonset/daemonset_test.go
pkg/plugin/driver/daemonset/template.go
pkg/plugin/driver/job/job.go
pkg/plugin/driver/job/job_test.go
pkg/plugin/driver/job/template.go
pkg/plugin/loader/loader.go
pkg/plugin/loader/loader_test.go
pkg/templates/manifest.go

In some cases it may be necessary to add custom annotations
to the sonobuoy pods (aggregator and plugins). Most notably,
this helps facilitate kiam permissions.
This change adds the fields to the necessary types so that it
can be passed around appropriatly and fill in the different
templates where it should be used.
Fixes #567
To review the changes, you mainly just need to look at the modifications to the tests/templates I made.
They are not exactly the most idiomatic tests; they hard-code a single test case and then check each part of the result manually. I'd like to improve those sorts of tests but this PR is not the place for it; instead, I just opted to focus on the feature …

Add ability to specify custom annotations

---

cmd/sonobuoy/app/status.go
pkg/client/interfaces.go
pkg/client/run.go
pkg/client/status.go

Increases consistency of our method signatures for the interface.
Fixes #337
```
The GetStatus method on the pkg/Interface (and SonobuoyClient type) will now take a struct which wraps the namespaces to increase in consistency and future extensibility.
```

Use a struct for GetStatus to be consistent

---

pkg/plugin/aggregation/aggregator.go

We have two flows for this logic: one for the
HTTP server and one for the channel monitoring
results.
This change places all the logic into a central
method so that it can be modified/tested more
confidently/succinctly.
Related to #728 
No logical changes in this PR; only doing this in prep of my next change to simplify the diffs. This way we can more easily test the logic used throughout.
```
NONE
```

Unify http/non-http result handling

---

pkg/plugin/aggregation/aggregator.go
pkg/plugin/aggregation/aggregator_test.go
pkg/plugin/aggregation/testdata/fakeLogData.txt

Will be rebased/tweaked after #729 merges which simplifies this update/testing since it puts all the logic in one place.
In the case where a connection gets reset or other
processing errors occur, the client is already
coded to automatically retry submission of the
results.
However, the server was marking the results as 'seen'
and would not reprocess them.
This change allows reprocessing results only if there
were errors processing before.
Fixes #728
FWIW, with the centralized code I think some other tests _could_ be fixed up and made to read a bit better but it's not really worth it to go and rework older tests.
```
Fixed a bug which led to partial results for …
```

Retry results

---

pkg/plugin/aggregation/aggregator.go
pkg/plugin/aggregation/aggregator_test.go
pkg/plugin/aggregation/run.go
pkg/plugin/aggregation/run_test.go
pkg/plugin/driver/daemonset/daemonset.go
pkg/plugin/driver/job/job.go
pkg/plugin/driver/job/job_test.go
pkg/plugin/driver/utils/utils.go
pkg/plugin/driver/utils/utils_test.go
pkg/plugin/interface.go
pkg/time/time.go
pkg/time/timetest/helpers.go

In some cases, a plugin's main container may terminate without
reporting results. If this is the case, the sonobuoy worker
hangs forever (until the aggregator times out) because it thinks
the plugin is still running.
This change modifies the logic of the aggregator/plugin monitoring
logic in order to not only check for restarts/failure to schedule,
but also for if containers terminate without submitting results.
To ensure that we do not race with the normal plugin terminate and
result reporting, we wait 1 minute after the pod terminates to submit
the error result. In the normal flow, this would give plenty of time
for the plugin to send its results the server in which case this error
result would be tossed out.
Fixes …

Add checks for if a container has terminated

---

site/_posts/2019-05-13-Sonobuoy-101.md
site/_posts/2019-05-15-Certifying-Kubernetes-with-Sonobuoy.md

Remove the excerpt separator ``, as it is being show in the blog posts:
Fixes the issue mentioned here: https://github.com/heptio/velero/issues/1575

Fix excerpt separator being shown in blog posts

---

.gitignore
.travis.yml
Makefile
pkg/plugin/aggregation/run_test.go
travis-ci.sh

A few files were left around preventing goreleaser from working.
The following changes were made:
- kubectl removed from deps since we didnt use it any more
- kind binary was downloaded instead of using go get. This way
we dont end up with creating go.mod and go.sum files and we also
pin the version and prevent changes if they update/break
- Updated a test to use and cleanup a tmp directory

Fix build and cleanup test to ensure clean state for release

---

.goreleaser.yml

The makefile sets this flag but goreleaser was not configured
to do so.
Fixes #748
If you download/install https://github.com/goreleaser/goreleaser you can run the following goreleaser command to test it out (for darwin; you can specify the linux path if you need that version):
```
goreleaser --skip-publish --skip-validate --rm-dist && ./dist/darwin_amd64/sonobuoy version
```
```
Fixed a bug which caused releases to not list the GitSHA they were built from.
```

Set GitSHA when using goreleaser

---

travis-ci.sh

The sonobuoy binary is in the cwd but not the path; fixup the
call to it here.

Fixup to travis debug lines

---

pkg/client/gen_test.go
pkg/client/testdata/default-plugins-via-nil-selection.golden
pkg/client/testdata/default.golden
pkg/client/testdata/e2e-default.golden
pkg/client/testdata/no-plugins-via-selection.golden
pkg/client/testdata/plugins-and-pluginSelection.golden
pkg/client/testdata/systemd-logs-default.golden

When bumping release versions we don't want to have to update tests.
By making this change we ensure the values would have matched the
build versions, but we no longer require the tests to be updated
when we modify that value.
Fixes #745
You could test this by:
- run the tests (confirm they pass)
- modify the buildinfo.Version value manually
- rerun tests (confirm they still pass)
Also, fyi, lots of these changes are due to `gofmt -s` simplifying some of the syntax.
```
N/A
```

Update golden file tests to use static versions

---

.gitignore
.travis.yml
travis-ci.sh

If someone fails to add a dep then the build will fail but
if they remove one and dont run it then it can lead to
deps hanging around unnecessarily and a future dev/PR getting
a surprising diff.
Fixes #244
dep _says_ that the command is supposed to exit non-zero if it would write something but that is just not true if you try it out/look at the code. Just checking that something gets written to stdout which seems (by looking into the code) to the only way to tell.
I am trying not to hinge on an exact wording like `Would have written` just in case that gets tweaked at some point. We are also pinning the version here though so it should be fine.
```
NONE
```

Ensure dep has been run in CI

---

Makefile

This adds a new target which can be used in the Sonobuoy Formula for
Homebrew. Homebrew formulae typically build from source. We are
currently using Docker when building and this is not available when
building for Homebrew. To ensure that we use the same build parameters
for our own builds and builds on Homebrew, we are providing a new make
target (`native`) which which runs `go build` on the host machine. This
build command is shared across the `native` target and our other build
targets.
Fixes #715
- Fixes #715 
I've tested this build on both Linux and macOS, and the existing targets are producing the output in the same …

Add "native" Makefile target

---

travis-ci.sh

Fixes #761 
Unable to reproduce the problem on any number of images; though the workaround is just to clearly find only the regular files.
```
NONE
```

Fixup debug line to target regular files and print file name

---

cmd/sonobuoy/app/delete.go
cmd/sonobuoy/app/logs.go
cmd/sonobuoy/app/retrieve.go
pkg/client/defaults.go
pkg/client/delete.go
pkg/client/delete_test.go
pkg/client/gen.go
pkg/client/gen_test.go
pkg/client/interfaces.go
pkg/client/interfaces_test.go
pkg/client/logs.go
pkg/client/logs_test.go
pkg/client/preflight.go
pkg/client/preflight_test.go
pkg/client/retrieve.go
pkg/client/retrieve_test.go
pkg/client/run.go
pkg/client/run_test.go
pkg/client/status.go
pkg/client/status_test.go

This adds basic checking and validation of configs passed to some of the
interface function implementations in the Sonobuoy client. It is primarily
being added to prevent panics caused by passing nil configs to these
functions. It could be expanded in future to provide more comprehensive
validation of configuration objects.
Fixes #394
- Fixes #394
This does not include comprehensive validation for some of the more
complex configuration objects (e.g. `GenConfig`). It primarily focuses on
the nil checks. A lot of the added tests in the client don't test the
"successful" case, where the execution of the function would proceed …

Add basic validation of configs

---

pkg/plugin/aggregation/aggregator.go
pkg/plugin/aggregation/run.go
pkg/plugin/driver/daemonset/daemonset.go
pkg/plugin/driver/job/job.go
pkg/plugin/driver/utils/utils.go
pkg/plugin/driver/utils/utils_test.go
pkg/worker/request.go
pkg/worker/request_test.go

If we are too aggressive with the timeframe, the main plugin container
may terminate and, while the sidecar is reporting the results and
the aggregator is reading them, the aggregator may instead too quickly
decide to consider the plugin a failure (because it hasn't seen the
final results yet).
This change just tries to extend some timing windows to give the
aggregator more time to see these results.
Lastly, it also adds logging into the worker when using retries. This
helps us better track what is happening on the worker's side.
Mitigates #759
```
Timeframe extended (from 1m to 5m) for the aggregator to see results from a plugin before considering it to have …
```

Tweak the timing of considering pod as failing to be more permissive

---

docs/release.md

This change adds more detail to some of the steps in the release process
documentation. It includes steps that must be performed specifically for
releases that correspond to new Kubernetes releases such as modifying
the list of test images and updating the minimum and maximum supported
versions of the Kubernetes API.
- Fixes #765 
This branch does not include instructions for how to add a new version
to the documentation.
```
None
```

Update release process documentation

---

README.md
scripts/update_docs.sh
site/docs/master/README.md
site/docs/master/conformance-testing.md
site/docs/master/gen.md
site/docs/master/plugins.md
site/docs/v0.15.0/README.md

- Fixes a small formatting issue
- Links to master docs on site, not github
- Updated script to ensure the docs link gets updated on future releases
- Updated the new v0.15.0 docs with the same change
```
NONE
```

Update README to point to docs site

---

site/_layouts/posts.html
site/_posts/2019-05-13-Sonobuoy-101.md
site/_posts/2019-06-26-Env-vars-on-the-fly.md

This feature went into release v0.14.3, the release
right before the v0.15.0 release. This blog post
expands on that new feature and how to use it on
custom plugins as well as the e2e plugin to utilize
dry-run mode.
```
NONE
```

Add new blog post for dry-run and --plugin-env flag

---

cmd/sonobuoy/app/images.go

Most of the background is described here: https://github.com/heptio/sonobuoy/issues/780
TLDR: I would like to enable the --e2e-repo-config flag for the sonobuoy images pull command to validate that all required images are in place.
- Fixes #780 
```
sonobuoy images pull supports now the "--e2e-repo-config" flag
```

Add e2e-repo-config flag to images pull command

---

cmd/sonobuoy/app/images.go

This PR ensures that `sonobuoy images pull` will return an exit code 1 if it can't pull all required images for the e2e tests. This is a follow up on https://github.com/heptio/sonobuoy/pull/781 and allows users to integrate a CI test in their pipelines to check if all images are present in the Docker registry (without any grep).
- Fixes #
```
sonobuoy images pull will return an exit code 1 if some images are not available.
```

Return exit code 1 if sonobuoy can't pull all images required

---

pkg/discovery/discovery.go
pkg/plugin/aggregation/status.go
pkg/plugin/aggregation/update.go

Currently sonobuoy always expects it's pod name to be sonobuoy.
So if you run sonobuoy with a CronJob, the controller will create a pod name
something like `sonobuoy-1561584180-zrwjf` and sonobuoy will fail to update
it's own status.  Also the sonobuoy CLI will not find the pod if you
check status or try to retrieve results.
This change removes the statically-set sonobuoy master pod name and
looks up the pod name based on the label given to that pod:
'run=sonobuoy-master`.
This assumes that this label is always set and will fail if more than
one pod exists in the namespace with that label.
- https://github.com/heptio/sonobuoy/issues/782
This PR is an alternative implementation to: …

Look up sonobuoy master pod name by label

---

pkg/client/retrieve.go

The `sonobuoy retrieve` command currently uses a hard-coded pod name
when attempting to retrieve scan results.  This change uses the same
mechanism as `sonobuoy status` to look up the sonobuoy master pod by
label.
- N/A
This is related to this PR that introduced the ability to use dynamic pod names:
https://github.com/heptio/sonobuoy/pull/787
N/A
Signed-off-by: Richard Lander <landerr@vmware.com>

Fix retrieve command when using dynamic pod name

---

pkg/client/preflight.go
pkg/client/preflight_test.go

It fixes a confusing error message in the preflight checks. It's not strictly
needed, but it is nice as a user when error messages make sense.
There is currently no issue for this problem.
```
Fix dns preflight test error message
```

Fix preflight test error message

---

README.md
site/docs/master/README.md

When linking from github->sonobuoy.io the links shouldn't put
`.md` suffix on the files or else it will actually render the
markdown instead of the webpage.
Fixes #793 
```
NONE
```

Fix links to doc pages on new site

---

README.md
site/_config.yml
site/_data/shortlinks.yml
site/_includes/site-header.html
site/_layouts/redirect.html
site/_plugins/data_page_generator.rb
site/docs/index.md

This fixes the need to specify `master` or `v0.15.0` or similar when linking to the latest docs from the README and other sources.
It will automatically redirect https://sonobuoy.io/docs to the latest version, as specified in _config.yml.
It also redirects any links specified in _data/shortlinks.yml, to their latest counterpart.
For example, https://sonobuoy.io/docs/gen will redirect to the latest version, currently https://sonobuoy.io/docs/v0.15.0/gen.
This also fixes the need to specify the latest version in the navigation header.

Add redirect for docs

---

pkg/plugin/aggregation/run.go
pkg/plugin/aggregation/run_test.go
pkg/plugin/driver/base.go
pkg/plugin/driver/base_test.go
pkg/plugin/interface.go
pkg/plugin/loader/loader.go
pkg/plugin/loader/loader_test.go
pkg/plugin/loader/testdata/skip-cleanup/not-set.yml
pkg/plugin/loader/testdata/skip-cleanup/set-false.yml
pkg/plugin/loader/testdata/skip-cleanup/set-true.yml
pkg/plugin/manifest/manifest.go

This PR Introduces a new field to the plugin definition which allows
cleanup for a given plugin to be skipped. This can be used in the
case where a user wants to inspect the resources after a plugin
has finished running.
If this field is set to true, cleanup for that plugin will be skipped.
If it is omitted or set to false, cleanup will happen as usual.
- Fixes #299 
This change will also require documentation to be updated
which I haven't yet done.
```
Introduced a new plugin configuration option which allows clean up of resources for that plugin to be skipped.
```

Allow cleanup to be skipped on a per plugin basis

---

site/docs/master/conformance-testing.md
site/docs/v0.15.0/conformance-testing.md

This PR fixes a broken link on [Conformance Testing](https://sonobuoy.io/docs/v0.15.0/conformance-testing/).

Fix a broken link on "Conformance Testing" page

---

pkg/client/testdata/no-plugins-via-selection.golden
pkg/templates/manifest.go

If the Sonobuoy config specified that no plugins should be run (by
overriding `Plugins` with an empty array), the ConfigMap which holds the
YAML for the plugins would not be created. The Sonobuoy aggregator would
then attempt to mount a non-existent ConfigMap and the container would
fail to start.
This change ensures that the ConfigMap is always created. In the case
where there are no plugins, no data is added.
- Fixes #784
```
Fixed a bug where the Sonobuoy aggregator container would fail to start if the config specified no plugins to run.
```

Generate Plugins ConfigMap if no plugins specified

---

README.md
site/docs/master/README.md

This PR updates the Readme and adds Docker as a requirement for the `sonobuoy images` command. Also I did some clean up and fixed some markdownlint errors/warnings.
```
NONE
```

Add Docker to requirements for sonobuoy images

---

pkg/config/loader.go
pkg/config/loader_test.go

When loading a config without a UUID, we don't generate one and it
remains empty. It is necessary for the config to have a UUID as it is
used to create a uniquely named directory for storing results. Without
this, we don't correctly create a child directory to store the results.
We create a tarball within a directory that we also try to add to that
tarball, effectively adding the created tarball to itself resulting in a
write error.
- Fixes #806
```
Fixed a bug where a config without a UUID would result in an error when writing results
```

Create a UUID for loaded configs if necessary

---

.travis.yml
kind-config.yaml

This upgrades our Travis CI script to use the latest version of Kind ([v0.4.0](https://github.com/kubernetes-sigs/kind/releases/tag/v0.4.0)).
As part of this upgrade, we also need to update our kind config to no longer use the `kind.sigs.k8s.io/v1alpha2` API as that was removed in this release. The new API no longer supports the `Config` type, and instead it should be `Cluster`. The config has been updated according to the changes in the [example kind config](https://raw.githubusercontent.com/kubernetes-sigs/kind/master/site/content/docs/user/kind-example-config.yaml).

Upgrade kind to v0.4.0

---

cmd/sonobuoy/app/e2e.go
pkg/client/e2e.go
pkg/client/e2e_test.go

This reintroduces the `e2e --rerun-failed` behaviour which had been
accidentally removed as part of a refactor. As part of reintroducing this
behaviour, it was noticed that the generated rergex for running specific
tests was invalid and would cause a panic when running ginkgo. In the
generated regex, we were double escaping `[]` characters. This doesn't
seem to be necessary as we do not double escape these characters for
other regexes (e.g. [`defaultSkipList`](https://github.com/heptio/sonobuoy/blob/master/pkg/client/mode.go#L42)).
- Fixes #797 
This behaviour was removed in [#315](https://github.com/heptio/sonobuoy/pull/315/files#diff-f6f1cbdfc63048c2340177ccd708d6b6L108). I have …

Ensure only failed tests are run with --rerun-failed

---

cmd/sonobuoy/app/worker.go
pkg/client/e2e.go
pkg/client/e2e_test.go
pkg/client/results/e2e/consts.go
pkg/client/results/reader.go
pkg/plugin/aggregation/aggregator.go
pkg/plugin/aggregation/aggregator_test.go
pkg/plugin/aggregation/handler.go
pkg/plugin/aggregation/handler_test.go
pkg/plugin/aggregation/run_test.go
pkg/plugin/driver/job/job.go
pkg/plugin/driver/utils/utils.go
pkg/plugin/interface.go
pkg/worker/request.go
pkg/worker/request_test.go
pkg/worker/worker.go
pkg/worker/worker_test.go
test/integration/stress_test.go

If there is a job returning results it currently goes into the
tarball at plugins/name/results/<files> but this is different
from daemonset results which have an extra directory stating
the node name (plugins/name/node/results/<files>).
To prepare for consistent handling of results, it would be preferred
that these have the same layouts so we added a new level for jobs:
"global" so a job plugin results go to plugins/name/global/results.
In addition, if a single file was uploaded as results, it was handled
in a unique way. Instead of being put into the directories listed above,
the same path would refer, instead, to a file. The contents of which
were the result.
It would be much preferred to preserve the folder structure and the
filename being …

Preserve single file result names and keep job/ds depth the same

---

pkg/plugin/aggregation/run_test.go
pkg/plugin/driver/base.go
pkg/plugin/driver/base_test.go
pkg/plugin/driver/daemonset/daemonset.go
pkg/plugin/driver/daemonset/daemonset_test.go
pkg/plugin/driver/job/job.go
pkg/plugin/driver/job/job_test.go
pkg/plugin/interface.go
pkg/plugin/loader/loader.go
pkg/plugin/loader/loader_test.go
pkg/plugin/manifest/manifest.go

The type plugin.Definition completely duplicates fields that exist
inside of manifest.Manifest and adds nothing new. Though I prefer
the name plugin.Definition, the users currently use the manifest.Manifest
object locally and expect the nested sonobuoy-config object so we
needed to keep that in order to not break existing plugins. In addition,
the plugin.Definition type was missing the Driver field, so the server
was actually losing that data when using that type.
This change should have no impact other than clarifying the landscape
of types on the backend.
Helps facilitate #306
```
NONE
```

Remove plugin.Definition

---

pkg/client/retrieve.go
pkg/discovery/discovery.go
pkg/plugin/aggregation/status.go
pkg/plugin/aggregation/update.go
pkg/plugin/aggregation/update_test.go

Previously the sonobuoy pod name was stored in a global variable and was
updated before it was used. Now, instead of updating the global variable
the function that determines the pod name returns it instead.
```
NONE
```

Remove use of global sonobuoy pod name

---

pkg/client/preflight.go
pkg/client/preflight_test.go

Instead of "blocking" users from using Sonobuoy with newer Kubernetes
releases with failed preflight checks, output a warning instead and
continue. This error has confused a number of users in the period
between a new Kubernetes release and the corresponding Sonobuoy
release.
Also update the error message for the minimum supported version to be
more consistent with the warning message.
- Fixes #814
```
Sonobuoy will no longer produce an error if the Kubernetes server version is greater than the maximum supported version and will instead provide a warning.
```

Change max supported version error to warning

---

pkg/client/delete.go
pkg/client/run.go
pkg/config/config.go
pkg/plugin/manifest/serializer.go

This includes a small number of changes to use
`const` where we previously using `var` or literals.
- Part of #293
There are definitely more places that could have been
updated, particularly where generating the manifests 
and plugins, however given that there may be significant
changes there with #809, I haven't gone further with that.
```
NONE
```

Update some values to use consts

---

pkg/client/results/processing.go
pkg/client/results/processing_test.go
pkg/client/results/testdata/mockResults/plugins/job-default-01/job-default-01.golden.json
pkg/client/results/testdata/mockResults/plugins/job-default-01/results/global/output.xml
pkg/client/results/testdata/mockResults/plugins/job-default-01/results/global/output2-ignored.xml
pkg/client/results/testdata/mockResults/plugins/job-default-02/job-default-02.golden.json
pkg/client/results/testdata/mockResults/plugins/job-default-02/results/global/output.xml
pkg/client/results/testdata/mockResults/plugins/job-default-02/results/global/output2.xml

When unset (or invalid), currently no post-processing is done which
means that users won't find the sonobuoy_results.yaml file.
By defaulting to 'raw' we make users immediately get a benefit from
the post-processing regardless of if they take extra steps to
customize the type/output.
Fixes #820
```
Post-processing defaults to ResultFormat=raw if unset or invalid in order to ensure users gain the benefit of the post-processing and "sonobuoy results" command.
```

Default to ResultFormat=raw if unset

---

scripts/sync_readme.sh
site/docs/master/README.md
travis-ci.sh

The README for the master version of the docs and in the root
of the repo (used by Github) should always be in sync but
require minor changes due to different relative locations of
resources and links.
Also added this script as part of our CI to ensure that the two
files don't drift.
Fixes #772
Also found that there was drift; the master docs had a link to the page about `wait` functionality, but the root readme did not. The link wasn't actually used/needed so I removed it.
```
NONE
```

Sync master/root README.md and provide a script to do this

---

Makefile

We used docker-credential-gcr only once we moved to Jenkins and
it was available on the agents already. This change moves back
to using gcloud auth like it was when we originally published
images via Travis.
Related to #808 
Unable to test this on non-master branches since creds are protected. Will have to merge and iterate.
```
NONE
```

Use gcloud auth instead of docker-credential-gcr

---

cmd/sonobuoy/app/status.go
cmd/sonobuoy/app/status_test.go
pkg/discovery/discovery.go
pkg/discovery/discovery_test.go
pkg/plugin/aggregation/status.go

- Fixes #819 
Example output as of now:
```
"sonobuoy.hept.io/status": "{\"plugins\":[{\"plugin\":\"e2e\",\"node\":\"global\",\"status\":\"complete\",\"result-status\":\"passed\",\"result-counts\":{\"passed\":1,\"skipped\":3584}},{\"plugin\":\"systemd-logs\",\"node\":\"kind-control-plane\",\"status\":\"complete\",\"result-status\":\"passed\",\"result-counts\":{\"passed\":1}}],\"status\":\"complete\",\"tar-info\":{\"name\":\"201908081539_sonobuoy_e3a5f742-7cb2-490e-b0ee-91c6e2c8decb.tar.gz\",\"created\":\"2019-08-08T15:39:45.1724467Z\",\"sha256\":\"bbf3d5e43fe26e101d6c10b0a829ce94e6b2954366a46775172c0696793ce20b\",\"size\":601067}}"
```
TODO:
```release-note
Added …
```

Add results info to the status annotation and status cmd output

---

cmd/sonobuoy/app/args.go
cmd/sonobuoy/app/gen.go
cmd/sonobuoy/app/gen_plugin_def.go
cmd/sonobuoy/app/gen_plugin_def_test.go
cmd/sonobuoy/app/testdata/pluginDef-default-podspec.golden
pkg/client/gen.go
pkg/client/gen_test.go
pkg/client/interfaces.go
pkg/client/testdata/default-pod-spec.golden
pkg/client/testdata/use-existing-pod-spec.golden
pkg/plugin/driver/base.go
pkg/plugin/driver/daemonset/daemonset.go
pkg/plugin/driver/daemonset/daemonset_test.go
pkg/plugin/driver/job/job.go
pkg/plugin/driver/job/job_test.go
pkg/plugin/manifest/manifest.go
pkg/plugin/manifest/serializer.go

This change introduces the ability to override PodSpec options for
plugins. A new flag `--show-default-podspec` has been added to the
`gen` and `gen plugin` commands. When used, Sonobuoy will include the
default PodSpec options for the given plugin driver in the resulting
yaml. This allows users to change these values or they can provide their
own. If one is provided in the plugin definition, Sonobuoy will use that
as is, otherwise it will use the default.
- Fixes #809 
```
Sonobuoy now includes the option to edit the PodSpec used when running plugins. Users can provide their own PodSpec or adapt the default …
```

Add ability to override pod spec options

---

pkg/client/results/processing.go
pkg/client/results/processing_test.go

In the case where the e2e plugin reported results (a tarball) but
it did not contain an xml file of junit results we want to be sure
to NOT count this as a success.
It may be reasonable to consider this a failure but I think it is
more generic/safe to just report it as unknown and users can
handle that case differently.
Also, I found another bug which was causing daemonsets to not
properly be bubbling up their results.
Fixes #840
```
Fixes a bug which caused `sonobuoy results` to report success if no results were processed at all. Modified this case to return 'unknown' instead.
```

Ensure a plugin isn't reported as passed if no results were read

---

pkg/discovery/queries.go

This got removed in a recent PR but should not have.
When querying namespaced resources you need the field selector
set. This is not something that can easily be tested in unit tests
since that logic happens on the server-side and mocks would not
hit that code.
Fixes #839
Removed here: https://github.com/heptio/sonobuoy/commit/8380685d55c7f41c3b81cc26811315dfb0859650#diff-799ef0bfefbd18913fd0fa8a3679e9e0L170-L172
I'd like to have a think about how we want to test some of these things. We need them to be part of our integration suite: run sonobuoy against the kind cluster, inspect the results. I don't want it to be a long set of bash scripts though.
Probably, we will want to add …

Ensure we filter resources by namespace

---

site/docs/v0.13.0/enhancements/streamlined-templates.md
site/docs/v0.14.0/enhancements/streamlined-templates.md
site/docs/v0.14.1/enhancements/streamlined-templates.md
site/docs/v0.14.2/enhancements/streamlined-templates.md
site/docs/v0.14.3/enhancements/streamlined-templates.md
site/index.html

Markdown docs that tried to show go template style code like
`{{ .Foo }}` would cause liquid syntax warnings in netlify.
We always just assumed they were warnings but it actually did fail
to parse those sections so those pages are rendered incorrectly.
That is not too serious since in general we dont link to those
but it causes it to be hard to see _real_ problems in the netlify
logs and also, if you go to the page manually, shows the wrong
data.
This resolves that issue by wrapping the sections in question with
tags to make it treat those sections as 'raw' data.
Fixes #775
https://github.com/Shopify/liquid/issues/927
```
NONE
```

Modify some old docs to avoid liquid syntax warnings

---

pkg/client/retrieve.go
pkg/discovery/discovery.go
pkg/plugin/aggregation/run.go
pkg/plugin/aggregation/run_test.go
pkg/plugin/aggregation/status.go
pkg/plugin/aggregation/update.go
pkg/plugin/aggregation/update_test.go
pkg/plugin/driver/daemonset/daemonset.go
pkg/plugin/driver/daemonset/daemonset_test.go
pkg/plugin/driver/job/job.go
pkg/plugin/driver/job/job_test.go
pkg/plugin/interface.go

When creating Pod or DaemonSet resources when running plugins, we didn't
mark them as owned by the Sonobuoy aggregator pod. This meant that if
the aggregator pod was deleted, the resources created by that pod would
be orphaned and would have to be deleted manually. This change sets the
OwnerReference for all resources to be the Sonobuoy aggregator pod so
that when the aggregator is deleted, all child resources are also
deleted.
- Fixes #818 
```
Sonobuoy now sets the `OwnerReference` on all Pod and DaemonSet resources that are created when running plugins. This means that if the main aggregator pod is deleted, all resources created by that pod …
```

Set OwnerReference on Plugin resources

---

pkg/client/results/processing_test.go
pkg/client/results/testdata/mockResults/plugins/ds-junit-01/ds-junit-01.golden.json
pkg/client/results/testdata/mockResults/plugins/ds-junit-02/ds-junit-02.golden.json
pkg/client/results/testdata/mockResults/plugins/ds-junit-03/ds-junit-03.golden.json
pkg/client/results/testdata/mockResults/plugins/ds-raw-01/ds-raw-01.golden.json
pkg/client/results/testdata/mockResults/plugins/ds-raw-02/ds-raw-02.golden.json
pkg/client/results/testdata/mockResults/plugins/ds-raw-03/ds-raw-03.golden.json
pkg/client/results/testdata/mockResults/plugins/job-default-01/job-default-01.golden.json
pkg/client/results/testdata/mockResults/plugins/job-default-02/job-default-02.golden.json
pkg/client/results/testdata/mockResults/plugins/job-junit-01/job-junit-01.golden.json
pkg/client/results/testdata/mockResults/plugins/job-junit-02/job-junit-02.golden.json
pkg/client/results/testdata/mockResults/plugins/job-junit-03/job-junit-03.golden.json
pkg/client/results/testdata/mockResults/plugins/job-raw-01/job-raw-01.golden.json
pkg/client/results/testdata/mockResults/plugins/job-raw-02/job-raw-02.golden.json
pkg/client/results/testdata/mockResults/plugins/job-raw-03/job-raw-03.golden.json

For large JSON objects stored as goldenfiles, identifying
changes is difficult when it is one large line due to the
fact that a single character change shows the entire object
as the 1 line diff.
This change makes those tests use MarshalIndent so the lines
are split up and sets the indent to 0 so that if we change the
nesting, the changes don't cascade to the rest of the file
simply due to indentation changes (which dont change the
object once unmarshalled).
Fixes #855 
Only the first commit is going to be merged; when you give me the 👍 I'll remove the second commit. The second commit is just to show what diffs in the future would look like. In those cases, I wrapped every test …

Easy diff golden files

---

site/docs/master/release.md

Release process was recently tweaked and the
docs needed to be updated to reflect that and
other lessons learned lately.

Update release docs for new build flow

---

site/docs/master/plugins.md
site/docs/v0.15.0/plugins.md
site/docs/v0.15.1/plugins.md
site/docs/v0.15.2/plugins.md
site/docs/v0.15.3/plugins.md

Conformance image is now maintained upstream and not in the
heptio/kube-conformance repo; fixed a reference to this.
In addition, some links to examples were in a format that would
link the docs between github *.md files but will not work on
the docs site. Updated those since the docs site is the primary
way these would be consumed.
Fixes #863

Fix broken links and reference to conformance image

---

pkg/client/results/processing.go
pkg/client/results/processing_test.go

When doing post processing if a plugin (or file) results
in an 'unknown' status, it should bubble up according
to the following rules:
- if any failures exist, failure bubbles up
- if any unknowns exist (and no failures), unknown bubbles up
- pass otherwise
Fixes #848
```
When looking at the results of plugins, Sonobuoy will now bubble up unknown values. If one result is unknown and others pass, the aggregate is unknown. If one result is unknown and any others failure, the aggregate result is still failure.
```

Bubble up unknown results just like failures

---

cmd/sonobuoy/app/worker.go
pkg/plugin/aggregation/handler.go
pkg/plugin/driver/base.go
pkg/plugin/driver/daemonset/daemonset.go
pkg/plugin/driver/job/job.go

In preparation of supporting status updates, I want to clarify
the meaning of the MASTER_URL env var on the worker.
Up until now the only URL of importance was the results URL so
that is what the MASTER_URL was set to. Soon, we will have results
and status updates, so it makes sense to have the MASTER_URL simply
be the hostname and add the path on the fly depending on which
endpoint we are trying to hit.
ref #735
```
MASTER_URL set on the Sonobuoy worker container now refers to just `https://<hostname>` instead of the full results URL in order to more easily support manipulating the path used. This should have no impact on users since this is just a value used internally.
```

Adjust MASTER_URL to be just the hostname

---

cmd/sonobuoy/app/logs.go
pkg/client/interfaces.go
pkg/client/logs.go
pkg/client/logs_test.go
pkg/plugin/driver/daemonset/daemonset.go
pkg/plugin/driver/daemonset/daemonset_test.go
pkg/plugin/driver/job/job.go
pkg/plugin/driver/job/job_test.go

Add a new flag to the `logs` command to show the logs only for a
specific plugin. If not provided, or no pods are found for the plugin,
default to showing all logs.
We didn't have a way to uniquely identify pods for a plugin, so this
change adds a new label when creating Pods and DaemonSets which can
be used to filter the pods. This means that the flag will not work
for older versions of Sonobuoy, but it will still default to showing
all logs which was the original behaviour.
- Fixes #702 
```
Sonobuoy can now show only the logs for a specific plugin by using the flag `--plugin <plugin_name>` when using the logs command.
```

Show logs for a specific plugin

---

pkg/client/logs.go
pkg/client/logs_test.go

Don't attempt to stream logs from containers until they are `Running`
- Fixes 
```
Improves the `sonobuoy logs -f` command by waiting until containers are running to stream logs instead of failing outright and discontinuing logs from that container.
```

Check for container running before following logs

---

cmd/sonobuoy/app/testdata/pluginDef-default-podspec.golden
pkg/client/testdata/default-plugins-via-nil-selection.golden
pkg/client/testdata/default-pod-spec.golden
pkg/client/testdata/default.golden
pkg/client/testdata/e2e-default.golden
pkg/client/testdata/envoverrides.golden
pkg/client/testdata/imagePullSecrets.golden
pkg/client/testdata/manual-custom-plugin-plus-e2e.golden
pkg/client/testdata/manual-custom-plugin-plus-systemd.golden
pkg/client/testdata/manual-custom-plugin.golden
pkg/client/testdata/manual-e2e.golden
pkg/client/testdata/no-plugins-via-selection.golden
pkg/client/testdata/plugins-and-pluginSelection.golden
pkg/client/testdata/ssh.golden
pkg/client/testdata/systemd-logs-default.golden
pkg/client/testdata/use-existing-pod-spec.golden
pkg/plugin/driver/base.go
pkg/plugin/driver/job/job_test.go
pkg/templates/manifest.go

A new conformance test in v1.16 will add a taint to a node which
can impact the sonobuoy aggregator pod as well as the e2e pod.
This change adds the toleration to both the default job podspec
and the aggregator. The default daemonset podspec already tolerates
all taints.
Fixes #876
I created a v1.16 cluster which may not be strictly necessary. You may just need to target the newer tests:
```
sonobuoy run --e2e-focus "removing taint cancels eviction" --kube-conformance-image-version=v1.16.0-rc.2 --sonobuoy-image schnake/sonobuoy:testTaint
```
```
Added a new toleration to jobs plugins and the Sonobuoy aggregator in order to avoid disruptive effects of some E2E …
```

Add a disruptive taint to list of default tolerations

---

site/_posts/2019-09-16-customizing-plugin-podspecs.md

I submitted this post with a future date of September 16 and thought it
would be visible on the Sonobuoy website on that date. Checking the
website this morning, this post is not visible so it didn't work as
expected.
To retrigger the publishing of the post, this change just includes a
minor change that does not impact the content or style (removing an
extra blank line).

Re-trigger custom podspec blog publishing

---

pkg/client/mode.go

This was a mode based on a closed-source image and not generally
available. No need to support it here, especially with how easy
it is to create/use custom plugins now.
Ref #872

Remove 'extended' mode

---

cmd/sonobuoy/app/args.go
cmd/sonobuoy/app/args_test.go
cmd/sonobuoy/app/gen_test.go
pkg/client/defaults.go
pkg/client/mode.go

With K8s v1.16, disruptive tests may not be part of the conformance
suite. As a result, we need to ensure that user workloads are
protected by default while still allowing for CNCF certification
test runs.
In this PR we:
- rename the default `conformance` mode to be `non-disruptive-conformance`
and modified the skip list appropriately.
- added a `certified-conformance` mode which does not provide a skip list
and will run even the disruptive tests
- tweaked the naming to use lower case values by default to be more
consistent with our other flags/naming
Fixes #877
Fixes #875
I could have written the skip list in a slightly different way, naming the tests individually, but instead …

Add certified conformance mode and non-disruptive-conformance mode

---

scripts/update_docs.sh

This script was written to consider the root README as the source
of truth but I think that was before we realized that the docs
for the site have slightly different linking requirements.
As a result, the appropriate place to take the README from is the
master docs.
Fixes #887
To test this, I'd do the following:
- checkout this branch
- run the script to generate the 'new' docs for a phony version: `./scripts/update_docs.sh v0.15.999`
- commit the change locally (so we can look at the diff later)
- add back the line I removed
- run the same command again `./scripts/update_docs.sh v0.15.999`
- run `git diff` to look at the difference.
You'll see some redundant things (it adds to …

Links in new docs script

---

.travis.yml
Makefile
test/integration/sonobuoy_integration_test.go

This adds a new package, `integration`, which is the starting point
for adding integration testing for Sonobuoy. The package only contains
one test so far which runs `sonobuoy version` and checks that all fields
in the output from `version` are non-empty.
To separate these tests, a new Makefile target has been added which
sets the appropriate flags for running these tests. They are currently
run conditionally with the tag `integration` under the assumption that
as this package grows, we may not want to run these tests every time.
- Part of #668 
You can verify this test by building the sonobuoy executable with your
local go toolchain then running it:
```
go build
go test …
```

Add integration test to check version information

---

Gopkg.toml

This change removes the unused dependency
`k8s.io/apiextensions-apiserver` from Gopkg.toml which was causing a
warning when running `dep ensure`.
This package was no longer needed after #689 and the package was
removed from `vendor/` in #739.

Remove unused dependency from Gopkg.toml

---

.travis.yml
Makefile
travis-ci.sh

Instead of placing kind and dep in the working directory for
the Travis CI build, place them in a location which is in the 
PATH so they can be easily used elsewhere.
It also allows us to fix the `deploy_kind` target in our Makefile
which assumed that kind was in the current directory.

Add kind and dep to PATH in Travis

---

cmd/sonobuoy/app/gen_plugin_def.go

When creating a plugin, one of the most common things you may
want to do is leverage the new result processing capabilities by
specifying if the results should be treated as raw files or as
structured junit (and eventually other formats).
This PR adds the new flag; no testing updates were required
since this does not change default behavior and any tests would
really just test the fact that the flag was added at all, being
trivial.
Related to #668 
```
Added a new flag `--format` to the `sonobuoy gen plugin` command which allows you to specify if the plugin generates structured junit results. Defaults to `raw` meaning no structure is assumed.
```

Adds the results format as a flag parameter for gen plugin

---

cmd/sonobuoy/app/results.go
cmd/sonobuoy/app/results_test.go
pkg/client/results/reader.go
pkg/discovery/discovery.go

If given a tarball, there is not a way to detect which plugins
were actually run without opening it up first. This means that the
`sonobuoy results` command is less useful since you have to have
preexisting knowledge about the tarball/run. You'd also have to
manually execute the command numerous times if you want all the
summaries of the plugins.
This change:
-  makes the default value for the `--plugin` flag the
empty string
- when a string value is given, it will print a single report
like the existing behavior
- when the default, empty string is used, we will list the report
for each plugin
- adds a new file, meta/info.json which will contain the list of
plugins that were actually run so that it is easier to grab this
list (rather than more …

Prints all plugins when invoking `sonobuoy results` by default

---

cmd/sonobuoy/app/gen.go
cmd/sonobuoy/app/gen_test.go
cmd/sonobuoy/app/pluginList.go
cmd/sonobuoy/app/pluginList_test.go
cmd/sonobuoy/app/testdata/sonobuoy.conf
cmd/sonobuoy/app/testdata/testPluginDir/plugin1.yaml
cmd/sonobuoy/app/testdata/testPluginDir/plugin2.yaml
cmd/sonobuoy/app/testdata/testPluginDir/pluginNotYAML.ext

If someone specifies `sonobuoy run|gen --plugin X` then X ought to
be allowed to be either a single plugin file or a directory of plugins.
To avoid dropping errors intentionally or processing lots of unnecessary
files, when processing a directory, we only consider *.yaml files. We
also do not recurse deeper into the directory.
Fixes #906
This entire diff is almost just test updates. I can split it out so that it is more clear if you want.
I originally wasn't going to have tests for this since there are no tests for flags->GenConfig generation. However I decided that it should be covered and the test was _almost_ doing that anyways.
However, I found a bug when making the test so I …

Allow the --plugin flag to specify a directory of plugins

---

.travis.yml
Makefile
scripts/run_integration_tests.sh
test/integration/sonobuoy_integration_test.go
travis-ci.sh

This change adds a simple test and mostly provides scaffolding to be
able to write further tests using the changes introduced in #907.
It adds a new script `run_integration_tests.sh` which creates a separate
cluster if necessary and then runs the tests on it.

Add a small test which runs a basic plugin

---

pkg/client/gen.go
pkg/client/gen_test.go
pkg/client/testdata/default-plugins-via-nil-selection.golden
pkg/client/testdata/default-pod-spec.golden
pkg/client/testdata/default.golden
pkg/client/testdata/e2e-default.golden
pkg/client/testdata/goRunnerRemoved.golden
pkg/client/testdata/imagePullSecrets.golden
pkg/client/testdata/manual-custom-plugin-plus-e2e.golden
pkg/client/testdata/manual-e2e.golden
pkg/client/testdata/ssh.golden

In Kubernetes 1.16.0 a problem in the bash runner of the conformance
tests caused the plugin to fail to report results whenever a test
failure occured.
This problem does not impact the golang-based runner which was
introduced also in Kubernetes 1.16.0. By default we would like to use
this feature as a result. It is a new feature but has been shown
so far to be functional and an improvement over the bash-based
runner (e.g. like this issue in general).
Users of Sonobuoy v0.16.0 should update to a version which utilizes
this env var by default, but they can also specify
--plugin-env e2e.E2E_USE_GO_RUNNER=true to workaround the issue.
If users of new versions of Sonobuoy wish to NOT use the go runner
they can also set --plugin-env e2e.E2E_USE_GO_RUNNER …

Default to using the golang-based conformance runner

---

README.md
site/_data/master-toc.yml
site/_data/v0-16-0toc.yml
site/docs/master/README.md

A recent issue made me take a look at our docs and I noticed that
we were still referencing the `e2e` command instead of the
`results` command. It was actually hard to find a link to that page
which should be more visible.
N/A
N/A
```
NONE
```

Tweak readme with info about results.

---

Gopkg.lock
cmd/sonobuoy/app/args.go
cmd/sonobuoy/app/run.go
pkg/client/interfaces.go
pkg/client/run.go
pkg/client/run_test.go

Often a user wants to use `sonbouoy gen` to generate some YAML and
then modify it using tools like jq or yq. We even have this workflow
documented and the user has to, end the end, pipe the data into
`kubectl apply -f`.
`sonobuoy run` is just a shorthand for `sonobuoy gen` + execute with
wait logic; it makes sense to allow loading a file or piping the data
from stdin.
This PR:
- adds a --file, -f flag to `sonobuoy run`
- if the value is `-` it will load from stdin, erroring if it is not
connected to a terminal.
It does not add a unit test for this since the `sonobuoy run` logic
is difficult to test in a unit test since it wants to talk to a real cluster.
We may consider adding this to integration tests but it is mostly just input
transformation and …

Allow piping input to sonobuoy run

---

site/README-JEKYLL.md
site/_includes/head-docs.html
site/css/custom-sonobuoy.css

Will not be linked to the docs site but will be accessible by URL.
Just useful for devs who may have questions about format.

Fix blockquote rendering

---

.travis.yml
Makefile
cmd/sonobuoy/app/gen_test.go
kind-config.yaml
pkg/client/testdata/default-plugins-via-nil-selection.golden
pkg/client/testdata/default.golden
pkg/client/testdata/e2e-default.golden
pkg/client/testdata/no-plugins-via-selection.golden
pkg/client/testdata/plugins-and-pluginSelection.golden
pkg/client/testdata/systemd-logs-default.golden
pkg/config/config.go
site/docs/master/release.md

New Dockerhub org for sonobuoy so we will start moving our
image publishing there. As of now we do not have our main images
published there (another PR will do that) but I've manually
built/pushed kind-node:v1.16.0 and so we can use it in our CI.
Fixes #913
```
NONE
```

Update our registry to dockerhub and use our latest kind-node

---

Makefile
pkg/client/run.go
test/integration/sonobuoy_integration_test.go

When using a manifest from a file and the `--wait` flag with `run`, a
segfault would happen because the value is retrieved from the
`config.Config` which is part of the `GenConfig` within the `RunConfig`.
When using a file, this config is nil, so an attempt to retrieve the
namespace value resulted in a segfault. Instead, we can capture the
namespace from the objects within the manifest file when they are being
created by the Kubernetes client.
- Fixes #929
I've written added an integration level test to check this and confirmed that the segfault exists before the change and is fixed by it.
```
Fixed a bug …
```

Use created namespace name during `run --wait`

---

pkg/client/results/processing.go
pkg/client/results/processing_test.go

If a node isn't marked with a status, it should be treated as
being unknown and bubble up accordingly.
Fixes #900
```
Fixed a bug where some plugins may have reported a final status which was empty to `sonobuoy status` or `sonobuoy results`. These are now treated as "unknown".
```

Process all nodes and treat empty status as unknown

---

pkg/client/results/processing.go
pkg/client/results/processing_test.go
pkg/client/results/reader.go
pkg/client/results/testdata/mockResults/plugins/ds-errors-01/ds-errors-01.golden.json
pkg/client/results/testdata/mockResults/plugins/ds-errors-01/errors/node1/errors.json
pkg/client/results/testdata/mockResults/plugins/ds-errors-01/results/node2/output.xml
pkg/client/results/testdata/mockResults/plugins/ds-errors-02/ds-errors-02.golden.json
pkg/client/results/testdata/mockResults/plugins/ds-errors-02/errors/node1/errors.json
pkg/client/results/testdata/mockResults/plugins/ds-errors-02/errors/node2/errors.json
pkg/client/results/testdata/mockResults/plugins/job-errors/errors/errors.json
pkg/client/results/testdata/mockResults/plugins/job-errors/job-errors.golden.json
pkg/discovery/discovery.go

Whenever the aggregator itself deems that a plugin has failed,
(e.g. pods didnt start, timeouts, etc) then it writes its results
into an errors directory. This should be considered when doing
results aggregation so that they can be resulted as failures.
Otherwise, the plugin is just reported as having 0 results and
having an unknown status even though Sonobuoy may have been the one
to mark it as failure internally.
Related to #883
Fixes #897
```
When inspecting plugin results (for reporting via `sonobuoy status` and `sonobuoy results`) errors saved in the `<plugin>/errors` directory which are reported by Sonobuoy itself are now considered. This should help make …
```

Results aggregation should consider the errors directory

---

README.md
site/docs/master/README.md

Go get has a number of issues with it since it requires go, grabs
master instead of a release, builds using the local go settings/version,
etc.
We'd like to just show people how to download a release in a terminal.
Fixes #941
```
NONE
```

Update README to download release instead of go get

---

.circleci/config.yml
scripts/ci/check_e2e_tarball.sh
scripts/ci/check_go_modules.sh
scripts/ci/check_readme_in_sync.sh

This initial config replicates some of the steps from our TravisCI
config. It introduces a new workflow that contains 3 jobs. It currently
only handles the steps that take place on PR branches:
* Checking that the READMEs are in sync
* Checking the go module state
* Running unit, stress, integration tests and a single Sonobuoy run
It does not yet handle image pushing. That will be addressed in a later
PR.

Add initial CircleCI config

---

.circleci/config.yml
scripts/ci/publish.sh

- Moves/updates the travis deploy script to work on circleCI.
- Added DOCKERHUB_TOKEN via web UI to circleCI
- runs publishing of images on master branch and on tags like v.*
- minor change to naming to clarify job purposes
Ref: #926
I tried to use circleCI on my own repo to show this behavior to some extent. You can see here: https://circleci.com/workflow-run/9fdeb6cc-04ae-4e11-9173-bc2f06c14f40 that the publishing waits for the tests to pass. In addition, you can see https://circleci.com/workflow-run/9a9a49a3-5279-40ab-8638-9803a92063e1 doesn't show that the publishing would have occurred at all since it wasn't on the master branch.
```
NONE
```

Move image pushing into CircleCI

---

site/_data/shortlinks.yml
site/docs/master/release.md

We recently moved our CI to CircleCI and our image pushing to Docker
Hub. This updates our docs to reference these new systems.
Also, this removes the link from the side bar as it's only really useful
for the development team.

Update release process docs to reference new systems

---

.circleci/config.yml

Our latest release didnt trigger a tagged release in circleCI; I think this was the cause.

Adjust our CircleCI to list tags on required job

---

.circleci/config.yml
scripts/ci/publish.sh

Previously the publishing step didn't have the binary to check
the version as it did before.
Builds the binary only since goreleaser and the image pushing logic
will build the other components as needed.

Fixing up CI scripts to publish correctly

---

scripts/ci/publish.sh

When the CIRCLE_TAG is set, the branch isnt which leads to this trying to use an empty tag.

Don't set branch just let it be calculated

---

scripts/update_docs.sh

Without this update, the config.yml doesnt get updated which
cases the versioned docs to not be formatted properly.

Update github org in one of our scripts

---

pkg/client/gen.go
pkg/client/testdata/default-plugins-via-nil-selection.golden
pkg/client/testdata/default-pod-spec.golden
pkg/client/testdata/default.golden
pkg/client/testdata/manual-custom-plugin-plus-systemd.golden
pkg/client/testdata/systemd-logs-default.golden

We currently sleep for 1h after the logs are gathered but some
test runs take multiple hours which leads to this plugin getting
restarted and trying to resubmit logs. This causes confusing messages
in the logs since the original plugin pod is gone and the only one that
exists gets a 409 error from submitting duplicate results.
Fixes #970
Easy to test with our new run-from-stdin capability:
```
go install
sonobuoy gen|sed 's/3600/2/'|sonobuoy run -f -
```
Just a client-side change so no image pushing necessary.
```
Fixed an issue where the systemd-logs plugin would restart while the e2e tests ran for longer than 1h. This led to confusing messages in the logs.
```

Sleep forever after systemd logs plugin finishes

---

pkg/plugin/driver/base.go
pkg/plugin/driver/base_test.go
pkg/plugin/driver/daemonset/daemonset.go
pkg/plugin/driver/job/job.go

We previously modified plugin Pods and DaemonSets to be owned by the
main Sonobuoy pod. When running plugins, we also create a secret for the
TLS certificate used for communication between plugins and the
aggregator pod. This change adds an OwnerReference to this secret so
that it is cleaned up if the main Sonobuoy aggregator pod is deleted.
Aside from unit testing, I tested this manually by checking that the secret exists before deleting the main Sonobuoy pod, and confirming it is deleted after that pod is deleted.
```
$ kubectl get secrets -n sonobuoy
NAME                                   TYPE                                  DATA   AGE
default-token-r2qd7 …
```

Set OwnerReference on plugin TLS Secret

---

site/_data/shortlinks.yml

This adds `e2eplugin` to the shortlinks so that this page can be
accessed with a URL that does not include a specific version and fixes
the broken link in the main repo README.

Fix broken e2eplugin link

---

pkg/image/imageversion.go
pkg/image/imageversion_test.go

Upstream publishes prerelease images so there is no need to throw
that info away. It is a remnant of Heptio publishing their own
images.
In addition, if we're using that info we dont need to warn about
the existence of prerelease info and never really needed to warn
about the metadata on the version. As a result we can remove that
entire warning check/log.
Fixes #976
Fixes #977
```
Sonobuoy will now utilize the prerelease info from the server version when looking up the conformance image. This means that if your cluster is version v1.17.0-beta.0 it will look up that exact version (which the upstream publishes currently). It continues to ignore metadata (e.g. for …
```

Use prerelease info when looking up conformance image

---

cmd/sonobuoy/app/args.go
cmd/sonobuoy/app/e2e.go
cmd/sonobuoy/app/gen.go
cmd/sonobuoy/app/run.go
pkg/client/interfaces.go
pkg/client/preflight.go
pkg/client/preflight_test.go
pkg/config/config.go

The preflight checks for Sonobuoy assume the namespace and labels of the
DNS pods. Although the preflight checks can be skipped, some users may
want to still run these checks and ensure that they pass before testing.
To allow this, this change introduces two new flags that are applied to
the `PreflightConfig` so that the namespace and labels to use for
finding the DNS pods can be configured.
The two new flags are: `--dns-namespace` and `--dns-pod-labels`.
The default values are the values that were previously being used so
this does not impact existing users.
- Fixes #975 
I've verified that this change works with an OpenShift …

Allow DNS pod selectors to be configured

---

cmd/sonobuoy/app/args.go
cmd/sonobuoy/app/pluginList.go
cmd/sonobuoy/app/pluginList_test.go

We currently allow loading plugins from the local file system
but for sharing of plugins it makes sense to allow users to
specify a URL.
Fixes #986
```
The `--plugin` flag now supports URLs in addition to paths to local files or directories.
```

Allow plugins to be specified via a URL

---

pkg/plugin/driver/daemonset/daemonset.go
pkg/plugin/driver/daemonset/daemonset_test.go

For daemonsets, node affinity can be set to limit/select the nodes
which the daemonset will run on. Since this is a native k8s feature
we should support it.
However, we use 'node-plugin' as a key in a few places which need
to understand that not every node will be considered.
The upstream logic for this node selection is in the core scheduling
packages and not readily consumable as a module. As a result, the
most reasonable path forward is to implement a small bit of the
desired functionality on our end.
For now, we just care about the RequiredDuringSchedulingIgnoredDuringExecution
field and only for node labels. This allows picking out nodes based on
labels that may satisfy most use cases.
Fixes #988
**Special notes …

Allow daemonset plugins running on subset of nodes

---

site/_posts/2019-11-18-cis-benchmark-plugin.md

This adds the CIS Benchmark plugin blog post.
Signed-off-by: Jonas Rosland <jrosland@vmware.com>

Add CIS Benchmark plugin blog post

---

.goreleaser.yml

Adjustment to our goreleaser configuration so that we publish the
- 32-bit Windows client
- 32-bit Linux client
- 64-bit Arm64 client
That means we now publish 6 clients; the above along with:
- 64-bit Windows
- 64-bit Linux
- 64-bit Darwin
I don't think the other combinations of goos/goarch make sense to publish.
Fixes #1005
I just locally did `GOOS=xyz GOARCH=abc go install` to ensure those clients all build.
There isn't a history of really supporting the 32bit clients but if this is the cost (a tiny update to the goreleaser) and an occasional ticket then I think it is fine to publish it to make consuming it easier.
```
Sonobuoy will now publish 32-bit Windows/Linux clients and arm64 clients on its Github release page.
```

Publish 32-bit and arm64 clients

---

go.sum
pkg/client/logs.go
pkg/client/logs_test.go

- Adds a method which adds a watch for new pods in the target namespace
- Removes fallback/retry logic which mutates the query from a specific
plugin to all plugins.
- Adds a ceiling for the max polling time when backing off due to a container
not being in a running state
- Adjusts tests as necessary
Fixes #703
A simple way to test this is to do:
```
sonobuoy run && sonobuoy logs -f
```
You'll now see that the e2e logs get streamed when the container is created; that would not happen with the older logic.
```
Sonobuoy will now begin tailing logs from new containers as they are created while running `sonobuoy logs -f`
```

Update to log logic in order to stream from new containers as created

---

pkg/client/gen.go
pkg/client/gen_internal_test.go
pkg/client/gen_test.go
pkg/client/testdata/e2e-progress-custom-port.golden
pkg/client/testdata/e2e-progress-vs-user-defined.golden
pkg/client/testdata/e2e-progress.golden

As of v1.17 the Kubernetes E2E test image will support progress
updates if the URL is specified.
Fixes #992 
Do the following to test:
```
$ go install && sonobuoy run --kube-conformance-image-version=v1.17.0-beta.2
```
It doesn't matter that your cluster may not be that version, since we are targeting that version of the image it will work. Likewise, you can do `sonobuoy gen` with that same option to see the YAML as well.
After starting the run, just poll against `sonobuoy status --json | jq` to confirm that you're getting progress updates.
Note: This will _not_ work if you are specifying the exact image via digest, e.g. `gcr.io/google-containers/conformance@sha256:8f55d97d42690532e44068b6db98051bc3782c916987cff8db3d43447b09a94e` . I think this is …

Default to enableing progress updates from E2E plugin

---

site/docs/master/e2eplugin.md

Signed-off-by: Zhecheng Li <lzhecheng@vmware.com>
There is a typo in e2eplugin page.
- Fixes #
```
release-note
```

Fix typo in e2eplugin page

---

cmd/sonobuoy/app/gen_image_repo_config.go
cmd/sonobuoy/app/root.go
pkg/image/manifest.go
pkg/image/manifest_test.go

This adds the subcommand `default-image-config` to `gen` to output the
default image registry config used with the `images` and `run` commands.
It will generate the config based on the version of Kubernetes that is
configured for use.
This simplifies the process for users as the registries for the E2E
tests differ for different versions of Kubernetes.
- Fixes #1010
I included some tests for checking that the version verification worked however I didn't write tests to check the resulting registry lists as these seemed to just duplicate the code. I'm happy to add them though if it seems worth it.
```
Sonobuoy …
```

Add command to output default image registry config

---

site/docs/master/airgap.md

This change adds more instructions on how to run Sonobuoy in airgapped
environments. The documentation was previously missing details such as
how to use the `images` command, the fact that different versions of
Kubernetes use different image repositories, and used outdated
instructions for running custom Sonobuoy manifests.
This page now breaks down what is required for each plugin and includes
more explicit step by step details.
- Fixes #1021 
This PR references the new command `gen default-image-config` which is proposed in #1022.

Improve documentation for airgapped environments

---

README.md
site/_includes/footer.html
site/_includes/head-docs.html
site/_includes/site-header.html
site/_scss/_styles.scss
site/_scss/site/objects/_card.scss
site/_scss/site/objects/_post.scss
site/_scss/site/objects/_section.scss
site/_scss/site/settings/_custom-sonobuoy.scss
site/_scss/site/settings/_variables.scss
site/docs/master/README.md
site/docs/v0.14.0/README.md
site/docs/v0.14.1/README.md
site/docs/v0.14.2/README.md
site/docs/v0.14.3/README.md
site/docs/v0.15.0/README.md
site/docs/v0.15.1/README.md
site/docs/v0.15.2/README.md
site/docs/v0.15.3/README.md
site/docs/v0.15.4/README.md
site/docs/v0.16.0/README.md
site/docs/v0.16.1/README.md
site/docs/v0.16.2/README.md
site/docs/v0.16.3/README.md
site/docs/v0.16.4/README.md
site/resources.md

Fixes: #1016
Updates to site colours to align with VMware branding and improve contrast rations for site accessibility.
Update to youtube plugin for that it can will insert an iframes title as well. New usage of liquid template `{% youtube "<title>" %}
Updates to links to provide link text
Updates to images to add alt text.
Accessibility changes assist people visiting the site with visual impairments and improve the function of text to speech tools such as Jaws.
Change includes moving custom-site/css/sonobouy.css to /site/_scss/settings/ for configuration consistency.
Signed-off-by: Brett Johnson <brett@sdbrett.com>
- Fixes #
```
release-note
```

Improve site accessibility score

---

site/_posts/2019-11-18-cis-benchmark-plugin.md

Originally published with a temporary image; now using upstream.
Clarified that the post has been changed and why.

Update blog post about kube-bench image

---

site/_data/shortlinks.yml

This adds the FAQ page to the shortlinks so that it can be accessed
without needing to specify a version in the URL.

Add FAQ to shortlinks

---

pkg/client/results/junit.go
pkg/client/results/processing_test.go
pkg/client/results/testdata/mockResults/plugins/job-junit-falsepositive/job-junit-falsepositive.golden.json
pkg/client/results/testdata/mockResults/plugins/job-junit-falsepositive/results/global/output.xml

If the test fails to run properly we need to record it as a failure
for our purposes.
Fixes #1025
Unit test covers the failure in the originating issue.
```
Fixed an issue where the <error ... > field of JUnit test cases was not parsed. These now get reported via Sonobuoy as failures.
```

Process JUnit error field

---

cmd/sonobuoy/app/results.go
pkg/client/results/processing.go
pkg/discovery/discovery.go
pkg/discovery/discovery_test.go

The bug would cause only one of the plugin/node values in the
`sonobuoy status --json` output to be updated and it would include
all the results for all nodes.
Instead, we want each plugin/node value in that list to report its
own values for passed/failed.
Fixes #1001
```
Fixed bug which caused daemonset plugins' status to not be updated with results properly.
```

Fix bug which caused daemonset status to not be updated with results

---

pkg/plugin/driver/daemonset/daemonset.go
pkg/plugin/driver/job/job.go
pkg/plugin/driver/job/job_test.go

The aggregator server has a monitoring routine for each plugin. Part
of that is to poll the API server to check the pod status. Currently
job plugins will abort and be marked as failed if we have our API
query fail.
This is different than the daemonset plugins which are just blindly
tolerant of the errors.
This change makes the job plugins tolerant in the same way. This is
because we know in general that the API server was working since
the aggregator pod is running already. There are lots of transient
errors that could take place, even the API server could go down and
be brought up. None of that should cause the plugin to become a
hard failure.
Fixes #1043
This was originally …

Do not fail jobs if we can't query the API server while running

---

pkg/client/results/junit.go
pkg/client/results/processing.go
pkg/client/results/testdata/mockResults/plugins/ds-errors-01/ds-errors-01.golden.json
pkg/client/results/testdata/mockResults/plugins/ds-errors-02/ds-errors-02.golden.json
pkg/client/results/testdata/mockResults/plugins/ds-junit-01/ds-junit-01.golden.json
pkg/client/results/testdata/mockResults/plugins/ds-junit-02/ds-junit-02.golden.json
pkg/client/results/testdata/mockResults/plugins/ds-junit-03/ds-junit-03.golden.json
pkg/client/results/testdata/mockResults/plugins/ds-raw-01/ds-raw-01.golden.json
pkg/client/results/testdata/mockResults/plugins/ds-raw-02/ds-raw-02.golden.json
pkg/client/results/testdata/mockResults/plugins/ds-raw-03/ds-raw-03.golden.json
pkg/client/results/testdata/mockResults/plugins/job-complex-err/job-complex-err.golden.json
pkg/client/results/testdata/mockResults/plugins/job-default-01/job-default-01.golden.json
pkg/client/results/testdata/mockResults/plugins/job-default-02/job-default-02.golden.json
pkg/client/results/testdata/mockResults/plugins/job-errors/job-errors.golden.json
pkg/client/results/testdata/mockResults/plugins/job-junit-01/job-junit-01.golden.json
pkg/client/results/testdata/mockResults/plugins/job-junit-02/job-junit-02.golden.json
pkg/client/results/testdata/mockResults/plugins/job-junit-03/job-junit-03.golden.json
pkg/client/results/testdata/mockResults/plugins/job-junit-falsepositive/job-junit-falsepositive.golden.json
pkg/client/results/testdata/mockResults/plugins/job-raw-01/job-raw-01.golden.json
pkg/client/results/testdata/mockResults/plugins/job-raw-02/job-raw-02.golden.json
pkg/client/results/testdata/mockResults/plugins/job-raw-03/job-raw-03.golden.json
pkg/client/results/testdata/mockResults/plugins/job-timeout/job-timeout.golden.json

If you look at the sonobuoy_results.yaml it can be a bit confusing
understanding the tree structure and what each node in that tree means.
This adds some extra metadata to certain Items (plugin summary, nodes,
and files) in order to make the raw file more comprehensible and
potentially aid in other processing.
Fixes #1047
```
Adds additional metadata into the sonobuoy_results.yaml file to help indicate what each node in the tree represents.
```

Tag Items with metadata about the type if item (e.g. node/file/etc)

---

cmd/sonobuoy/app/gen.go
cmd/sonobuoy/app/gen_plugin_def.go
cmd/sonobuoy/app/root.go
pkg/client/gen.go
pkg/plugin/manifest/helper/helper.go

We have the `sonobuoy gen` command which prints a lot of
different types of resources and `sonobuoy gen plugin` which
prints custom plugin definitions. Sometimes it would be helpful
to be able to print the default e2e or sytemdlogs plugin definitions
so that they can be tweaked.
Added two commands `sonobuoy gen plugins e2e` and
`sonobuoy gen plugins systemd-logs` which does this.
Minor tweak to code organization to improve code reuse.
Fixes #991
These were just printing some data by hitting a code path that was already being used/tested. I didn't add any new tests for this code. Let me know if you want to add some basic one.
```
Adds two subcommands (e2e and …
```

Adds commands to print default plugin definitions

---

pkg/plugin/aggregation/status.go

The GetStatus function assumed that any error when getting a namespace
was due to that namespace not existing. Instead state that it was an
error when getting the namespace.
- Fixes #1055

Improve error message from GetStatus

---

cmd/sonobuoy/app/images.go
pkg/image/image.go
pkg/image/images_test.go
pkg/image/manifest.go
pkg/image/manifest_test.go

The existing client for handling plugin images assumed that the images
were for the e2e plugin. We are trying to add support for other images
so we need to make the image client more generic. This change refactors
the image client to deal with image names rather than the internal
Kubernetes image `Config` type.
- Part of #1028 
Creating this as a Draft PR for now to check coverage/tests

Refactor image client to not be E2E specific

---

cmd/sonobuoy/app/args.go
cmd/sonobuoy/app/run.go
cmd/sonobuoy/app/run_test.go

If using the --file option for `sonobuoy run` they shouldn't also
try and set other options.
This is because we are not able to take the file output and turn
that into a genConfig object which can be merged with the other
command line options.
When in the expanded file format, we are unsure if which parts
should be merged/how.
These are meant to be exclusive options.
Fixes #1027
```
Added an error message to clarify that users should not specify other customization flags when trying to use `sonobuoy run --file`. You are able to provide the kubeconfig and context flags as those are still used to connect to the cluster though.
```

Clarify that users shouldn't provide more options when running a file

---

cmd/sonobuoy/app/args.go
cmd/sonobuoy/app/gen.go
cmd/sonobuoy/app/gen_test.go
cmd/sonobuoy/app/images.go
cmd/sonobuoy/app/images_test.go
pkg/image/docker_client.go
pkg/image/docker_client_test.go
pkg/image/dryrun_client.go
pkg/image/image.go
pkg/image/manifest.go
pkg/image/manifest_test.go

This changes adds support for pulling the Sonobuoy worker image, the
systemd-logs image and the Kubernetes conformance image in addition to
the images required for the e2e plugin.
The individual images to pull cannot be configured. Only the default
version for the cluster will be pulled. The images can only be pushed to
one registry which is specified with the new flags `--custom-registry`.
This currently only works for the default built in plugins. A follow up
change will be made to apply the same approach to any image in a plugin
definition.
- Fixes #1028 
- Fixes #1059 
I've tested the new commands for this manually. I ran …

Add support for pulling and pushing all images

---

.goreleaser.yml

https://github.com/goreleaser/goreleaser/commit/8defb77b0eea3d775b016b32f8d5f91890e4e1a7#diff-6bc8131dff9242f298c3811fada0c174L180-L196 removed the archive field and it needs updated for the release.

Update goreleaser to remove deprecated field

---

cmd/sonobuoy/app/args.go

The flag was mistakenly named `systemd-logs-flag` when it should have
been `systemd-logs-image`. The existing flag has been left in place but
has been marked as hidden and deprecated. It will continue to work but
will not appear in the help/usage.
```
The flag for specifying the image for `systemd-logs` plugin has been renamed from `systemd-logs-flag` to `systemd-logs-image`. The previous flag, `systemd-logs-flag`, is now deprecated and will be removed in a future release.
```

Fix flag name for systemd-logs image

---

cmd/sonobuoy/app/worker.go
pkg/client/retrieve.go
pkg/worker/worker_test.go

There may be more of these situations lurking around, but as we
try to support Windows nodes we need to make sure that we are using
filepath unless we know we need forward slashes (like in URLs).
This changes a few calls to path.XYZ to filepath.XYZ and updates some
tests in the same way.
xref #732
```
N/A
```

Use filepath instead of path when possible

---

pkg/config/config.go

The image is now published to the sonobuoy repo on dockerhub.
In addition, the plugin code is now at github.com/vmware-tanzu/sonobuoy-plugins
Image is already there; you can test this manually with `gen` but if you run it, remember that you have to specify the sonobuoy aggregator command manually since as of now it will be left blank, run the run_master script, and exit early w/o being able to download results.
```
Updates the location for the systemd-logs image (now on DockerHub under the sonobuoy organization)
```

Update to use latest systemd-logs image

---

.circleci/config.yml
Makefile
scripts/ci/publish.sh
test/integration/sonobuoy_integration_test.go

As a precursor to supporting Windows builds, I'm separating out
more parts of our build in CircleCI.
Major changes:
- unit tests in parallel with other build steps
- separate building the binaries, building the images, and running
integration tests
- using workspaces to persist binaries/images across jobs
Total time to run the workflow decreased by about 3m (30%) since
the unit tests were no longer on the critical path.

Decouple building binaries from images 

---

pkg/image/v1.13.go

**What this PR does / why we need it**: 1.13 e2e tests need resource-consumer:1.4, not resource-consumer:1.5. https://github.com/kubernetes/kubernetes/blob/release-1.13/test/utils/image/manifest.go#L131
- Fixes #
```
NONE
```

Fix 1.13 resource-consumer image tag

---

cmd/sonobuoy/app/args.go
cmd/sonobuoy/app/images.go

If the cluster the user wants to get images for is not available
at the time (preparing images ahead of time, for a coworker, etc)
then the user needs a way to specify the version rather than relying
on the autodetection.
This change also causes the images from `sonobuoy images` to be printed
in a sorted order for consistency.
Fixes #1082
```
Adds a kubernetes-version flag to the images subcommands to allow manual specification instead of auto-detection of cluster version.
```

Add kubernetes-version flag to images subcommands

---

.circleci/config.yml
DockerfileWindows
Makefile
cmd/sonobuoy/app/args.go
cmd/sonobuoy/app/gen.go
cmd/sonobuoy/app/node_selector.go
cmd/sonobuoy/app/node_selector_test.go
cmd/sonobuoy/app/retrieve.go
examples/plugins/windows-plugin/Dockerfile
examples/plugins/windows-plugin/README.md
examples/plugins/windows-plugin/plugin.yaml
examples/plugins/windows-plugin/run.ps1
manifest_spec.yaml.tmpl
pkg/client/gen.go
pkg/client/gen_test.go
pkg/client/interfaces.go
pkg/client/retrieve.go
pkg/client/testdata/multiple-node-selector.golden
pkg/client/testdata/single-node-selector.golden
pkg/templates/manifest.go
pkg/worker/worker.go
scripts/ci/publish.sh
site/docs/master/release.md

Currently in a beta state, we are experimenting with building
Windows images so that Sonobuoy can be run on Windows nodes.
This change stops short of adding the Windows build to CI
while we figure out some of the last technical problems there.
Changes include:
- Utilizing circleci workspaces to load/store docker images across stages
- Adds a Windows sample plugin
- Updates the makefile to support building windows images and cleans up some of the makefile structure to build the binaries as appropriate
- Updates the makefile to build/push images for windows only if PUSH_WINDOWS=true
- Updates the way the manifest-tool is invoked to use a template instead of the command line options (which provides more flexibility)
- Adds a flag …

Increase compatibility for  building of Windows images

---

.gitignore
Makefile

Uncommented something that was just for local testing and added a file to the gitignore.

Minor tweak after last commit

---

.circleci/config.yml

Our CI is failing because we are not attaching the workspace where the
Docker images were built before attempting to load them. This change
attaches the workspace before attempting to load the images as we do in
the integration test step.

Attach workspace before loading docker images

---

cmd/sonobuoy/app/args.go

In #1066, we deprecated this flag with the intention of removing it in
the 0.18.0 release. Given that we are about to release this version,
this flag is now being removed.
- Fixes #1067 
```
Remove the deprecated `--systemd-logs-flag` flag. `--systemd-logs-image` should be used instead.
```

Remove deprecated --systemd-logs-flag flag

---

.circleci/config.yml

[When building the Sonobuoy images, we build images for multiple targets.
We push them in a separate step from where they were built so they need
to be persisted to the workspace. We were previously only persisting the
sonobuoy/sonobuoy tagged images, not the sonobuoy/sonobuoy-ARCH images.
This was causing CI failures as the image pushing step was trying to
push images for different architectures that did not exist locally.

Persist images for all targets

---

Makefile

When calling the `push_manifest` target, we were passing `VERSION` to
use for the image tag, however it wasn't being used. Instead we using
the `IMAGE_VERSION` which was defined outside the target and was the tag
for an image that hadn't been pushed. This modifies the `gen_manifest`
target to use the passed `VERSION` value.
This also updates our Makefile to get the latest version of
manifest-tool.

Use passed VERSION when generating image manifest

---

README.md
site/docs/master/README.md

Our installation instructions included a command to download and extract
a release tarball from GitHub. This command assumed the presence of
`$HOME/bin` which not all users had. It also assumed that users will be
downloading an `amd64` release.
Now that we are supporting many more platforms and architectures, it is
simpler to leave it up to the user to select the release they want and
extract it to their desired location.
Also, due to the increased changes to the platforms we support, and the
new workflows for building images for those targets, we don't recommend
building from source so remove that as a suggestion.
- Fixes #980

Simplify installation instructions

---

kind-config.yaml

This step was missing from the PR for the v0.18.0 release (#1101).

Use v1.18.0 kind image

---

.circleci/config.yml

As stated in the [CircleCI docs](https://circleci.com/docs/2.0/configuration-reference/#tags), if a job has a tag filter, all dependent jobs
must have the same tag filter. Given that the `publish_images` job
depends on all the other jobs, these must also have the same tag filter.

Ensure all CI steps are run for tags

---

Makefile

We were building windows images with the name `windows` but attempting
to push images with only `win` in the name.
Also, we can't build windows and linux images in the same docker context
so don't attempt to push linux images if pushing windows images.

Ensure consistent windows image names

---

pkg/image/manifest.go

The `PromoterE2eRegistry` wasn't set correctly which
resulted in an invalid image in the E2E images list.

Fix missing registry for E2E test image

---

pkg/plugin/driver/utils/utils.go
pkg/plugin/driver/utils/utils_test.go

We found a crash when ran sonobuoy in serverless kubernetes cluster, see below error log.
In serverless kubernetes cluster, pod may need 10s to start after creation, before container start, pod.Status.StartTime is nil.
NAME                                READY   STATUS    RESTARTS   AGE
sonobuoy                            0/1     Error     0          4h57m
sonobuoy-e2e-job-61031ae7baac48e1   2/2     Running   0          4h57m
time="2020-04-20T02:49:23Z" level=info msg="Starting aggregation server" address=0.0.0.0 port=8080
time="2020-04-20T02:49:23Z" level=info msg="Starting annotation update routine"
time="2020-04-20T02:49:23Z" level=info msg="Running plugin" plugin=e2e
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation …

fix crash when run sonobuoy in serverless kubernetes cluster

---

.circleci/config.yml
scripts/run_integration_tests.sh
site/docs/master/release.md

This upgrades our use of Kind in CI to the latest version. A recent
version of Kind introduced merging of kubeconfigs and separate
kubeconfigs are no longer written. The kind command
`get kubeconfig-path` has been deprecated so any usage of it has
been removed. The context is be updated to use the newly created
cluster. Some of our docs which reference this deprecated command
have also been updated.

Upgrade to Kind 0.7.0

---

.circleci/config.yml
Makefile
go.mod
test/integration/testImage/Dockerfile
test/integration/testImage/src/go.mod

Update our base images, go.mod files, and CircleCI config
to use the latest version of Go.

Upgrade to Go 1.14

---

.circleci/config.yml

We're seeing frequent failures when attempting to create a kind
cluster in our CircleCI scripts. This increases the verbosity when
running kind to help debug the issue.

Add verbose flag when creating kind cluster

---

site/docs/master/plugins.md
site/docs/master/results.md

We added support for the `manual` results type in #1090.
That PR did not include documentation for this new type. This
change adds some documentation on the details of the new
result type and how to use it.

Add documentation for manual results type

---

site/_contributors/01-john-schnake.md
site/_contributors/02-bridget-mcerlean.md
site/_contributors/02-steve-sloka.md
site/_contributors/03-tim-hinderliter.md
site/_contributors/04-michael-michael.md
site/_includes/contributors.html

This will change the non-relevant links for each team member to proper links to GitHub user pages.
- Fixes #
```
release-note
```

Add GitHub links to team member list

---

cmd/sonobuoy/app/args_test.go
pkg/client/mode.go

The original implementation for enabling parallel running of tests was
added when ginkgo expected a numeric value for the number of nodes to
use when running in parallel. This is no longer needed as ginkgo can
detect the optimal number of nodes to use. The [script for running the
e2e tests](https://github.com/kubernetes/kubernetes/blob/v1.18.3/cluster/images/conformance/run_e2e.sh#L55-L61) now expects "true", "y" or "Y" to enable parallel testing.
This commmit changes the default value to "false". Although the previous
value would not have resulted in parallel testing being enabled, this
change helps users understand that the value provided should be boolean.
```
The default …
```

Change default value for E2E_PARALLEL

---

cmd/sonobuoy/app/args.go
pkg/client/delete.go
pkg/client/delete_test.go

Namespaces created by the E2E tests stopped using the `e2e-tests-`
prefix from Kubernetes 1.14 onwards. This meant that the `delete --all`
behaviour did not delete any orphaned E2E test namespaces.
This change adapts the heuristic used by Sonobuoy to find E2E namespaces
to instead look for the presence of the `e2e-framework` and `e2e-run`
labels.
- Fixes #1125
```
The `delete --all` command will now identify namespaces for deletion by checking for the presence of the `e2e-framework` and `e2e-run` labels instead of the `e2e-` name prefix.
```

Improve E2E namespace cleanup when using `delete --all`

---

cmd/sonobuoy/app/run.go
cmd/sonobuoy/app/run_test.go
site/docs/master/faq.md
site/docs/v0.16.5/faq.md
site/docs/v0.17.0/faq.md
site/docs/v0.17.1/faq.md
site/docs/v0.17.2/faq.md
site/docs/v0.18.0/faq.md
site/docs/v0.18.1/faq.md
site/docs/v0.18.2/faq.md
site/docs/v0.18.3/faq.md

Replace use of whitelist with allow/allow list

---

pkg/client/testdata/custom-systemd-logs-image.golden
pkg/client/testdata/default-plugins-via-nil-selection.golden
pkg/client/testdata/default-pod-spec.golden
pkg/client/testdata/default.golden
pkg/client/testdata/e2e-default.golden
pkg/client/testdata/e2e-progress-custom-port.golden
pkg/client/testdata/e2e-progress-vs-user-defined.golden
pkg/client/testdata/e2e-progress.golden
pkg/client/testdata/envoverrides.golden
pkg/client/testdata/goRunnerRemoved.golden
pkg/client/testdata/imagePullSecrets.golden
pkg/client/testdata/manual-custom-plugin-plus-e2e.golden
pkg/client/testdata/manual-custom-plugin-plus-systemd.golden
pkg/client/testdata/manual-custom-plugin.golden
pkg/client/testdata/manual-e2e.golden
pkg/client/testdata/multiple-node-selector.golden
pkg/client/testdata/no-plugins-via-selection.golden
pkg/client/testdata/plugins-and-pluginSelection.golden
pkg/client/testdata/single-node-selector.golden
pkg/client/testdata/ssh.golden
pkg/client/testdata/systemd-logs-default.golden
pkg/client/testdata/use-existing-pod-spec.golden
pkg/plugin/aggregation/update.go
pkg/plugin/aggregation/update_test.go
pkg/plugin/driver/daemonset/daemonset.go
pkg/plugin/driver/job/job.go
pkg/templates/manifest.go

We renamed the `master` command to `aggregator` in #847 (released in
v0.15.3). However, `master` was still being used in some of our
Kubernetes resource labels and names. We want to remove use of
insensitive language and as such use different labels for
identifying resources.
Now, any aggregator resources will have the label
`sonobuoy-component: aggregator` and plugin resources will have
`sonobuoy-component: plugin`. The existing label is still in place as it
was used to identify the aggregator pod (which is required most sonobuoy
commands once a run has started). Removing it now would prevent users
with older clients from using newer images, or querying the state of
runs started by newer clients. Instead, both labels will be applied
howeve the …

Deprecate use of "master" in resource labels and names

---

site/docs/v0.13.0/enhancements/v2-worker-aggregator.md
site/docs/v0.14.0/enhancements/v2-worker-aggregator.md
site/docs/v0.14.1/enhancements/v2-worker-aggregator.md
site/docs/v0.14.2/enhancements/v2-worker-aggregator.md
site/docs/v0.14.3/enhancements/v2-worker-aggregator.md

We updated our terminology to use "aggregator" instead of "master".
There were still a few uses in old unlinked docs, so they have also been
updated.
Note: There is still some usage of the term master referring to the
main branch of the repository, referencing Kubernetes taints, and
old code samples. These will remain for now.

Remove insensitive language from old docs

---

pkg/worker/config.go

The `LoadConfig` function for the worker was configured to be able to
load configuration data from a file. However, the [necessary viper
function](https://github.com/spf13/viper/blob/13df72109047b6ae9c907bce81e327265d6d8a9c/viper.go#L1325-L1354) to load and read the file was never called. This functionality
has not worked since the initial commit and so it doesn't seem
necessary. This is now being removed in favour of only configuring the
worker via environment variables.

Remove unused config file handling from worker

---

cmd/sonobuoy/app/worker.go
pkg/config/loader.go
pkg/plugin/driver/base.go
pkg/plugin/driver/base_test.go
pkg/plugin/interface.go
pkg/worker/config.go
pkg/worker/config_test.go

We renamed the `master` command to `aggregator` in #847 (released in
v0.15.3). However, we left some of the existing uses in place to prevent
backwards incompatibility. This change renames the `MasterURL` field in
`WorkerConfig` to `AggregatorURL` in keeping with our terminology
elsewhere. Worker containers are configured using environment variables.
This change renames the environment variable but also adds some
compatibility for the original environment variable to still be
processed.
It is possible for different image versions to be used for the
aggregator and the worker (although it would have to be explicitly set
in the generated manifest). This changes allows older versions of
Sonobuoy to be used as the aggregator image but does not allow …

Replace MasterURL with AggregatorURL in WorkerConfig

---

DockerfileWindows

The `master` alias for the `aggregator` command was removed in #1137,
however this alias was still in use in the Windows Dockerfile. Replace
the use of this with the new command name `aggregator`.

Replace use of master in Windows Dockerfile

---

cmd/sonobuoy/app/gen_test.go
pkg/config/config.go
site/docs/master/airgap.md
site/docs/master/faq.md

Sonobuoy was using `gcr.io/google-containers` as the registry to fetch
the conformance from. `k8s.gcr.io` used to point to this registry
however is now being switched to point to a community controlled
repository: `{asia,eu,us}.gcr.io/k8s-artifacts-prod`.
The repository `gcr.io/google-containers` is now entering a read-only
state and should not be used. Instead, we should use the vanity domain
`k8s.gcr.io`.
The previously used `google-containers` registry is still available for
old image versions so should not affect previous releases of Sonobuoy
that reference it explicitly. Those versions of Sonobuoy would only be
used with older Kubernetes versions where the corresponding conformance
image version will still exist in that registry.
Reference:
- …

Remove use of gcr.io/google-containers

---

.gitignore
site/Gemfile.lock

This update is to address CVE-2020-14001
https://github.com/advisories/GHSA-mqm2-cgpr-p4m6
The kramdown gem before 2.3.0 for Ruby processes the template option inside
Kramdown documents by default, which allows unintended read access
(such as template="/etc/passwd") or unintended embedded Ruby code execution
(such as a string that begins with template="string://<%= `).
NOTE: kramdown is used in Jekyll, GitLab Pages, GitHub Pages, and Thredded Forum.
- Fixes #
```
release-note
```

Update gem kramdown for site generation

---

site/docs/master/release.md
site/docs/master/sonobuoy-config.md

This fixes some of the formatting on the Sonobuoy config and Release
docs pages.

Fix formatting on docs pages

---

site/_plugin-list/06-cluster-inventory.md

This PR updates the plugin documentation to include the newly added cluster inventory plugin found here https://github.com/vmware-tanzu/sonobuoy-plugins/tree/master/cluster-inventory

Adding cluster inventory plugin documentation

---

pkg/image/manifest.go
pkg/image/manifest_test.go

This ensures that we are testing images which were overriden by custom
registry. Some registries are meant to be excluded from override.
See #1181 for details.
Signed-off-by: Wilson E. Husin <whusin@vmware.com>
Stabilizes unit tests flake
- Fixes #1181
-
```
NONE
```

Deterministic TagPair assertion of custom registry

---

.github/stale.yml

Signed-off-by: Wilson E. Husin <whusin@vmware.com>
Integrating StaleBot to manage abandoned issues
- Fixes #1177
None
```
NONE
```

Add StaleBot

---

.github/stale.yml

"wontfix" seems to imply more than "no activity", when we actually are
okay with reopening previously closed issues with no resolution
None
None
```
None
```

Use "stale" label for stale bot

---

.github/workflows/ci-test.yaml
Dockerfile
DockerfileWindows
Makefile
scripts/run_integration_tests.sh

Moving off Circle CI to have less service dependencies. End user / product should not be impacted.
Partially #1178
```
NONE
```

Circle CI tests migration to GitHub Actions

---

Dockerfile
Makefile
cmd/sonobuoy/app/root.go
cmd/sonobuoy/app/splat.go
pkg/client/retrieve.go
test/integration/testImage/Dockerfile
test/integration/testImage/yaml/ds-junit-passing-tar.yaml
test/integration/testImage/yaml/ds-manual.yaml
test/integration/testImage/yaml/ds-raw-passing-tar.yaml
test/integration/testImage/yaml/job-junit-passing-singlefile.yaml
test/integration/testImage/yaml/job-manual.yaml
test/integration/testImage/yaml/job-raw-singlefile.yaml
test/integration/testImage/yaml/manual-with-arbitrary-details.yaml

Use distroless container image for smaller size of deployment and less maintenance on potentially vulnerable programs which we do not use but included in Debian base container.
**Blockers**:
#1206
N/A
```
Sonobuoy aggregator pod is now built based on Distroless container
```

Use distroless images

---

Makefile
cmd/sonobuoy/app/retrieve.go
go.sum

Preparing for next release:
- Use `nonroot` Distroless
- Ensuring ARM64 images are built with Distroless as well
- Use go1.16
- Fix regression of missing datetime prefix on `sonobuoy retrieve`
None
```
Use go1.16 and nonroot Distroless for building images
```

Datetime regression fix and go1.16

---

pkg/buildinfo/version.go

The executable on github is correctly reporting v0.50.0 but not
master. So developer builds are incorrectly showing v0.20.0.

Bump sonobuoy version

---

go.sum
pkg/client/logs.go

When streaming logs, we previously watched a list of pods so that
we could identify when new ones were created and we would stream
their logs as well.
The problem is when the watcher breaks we do not automatically
retry the connection and a channel gets closed causing an infinite
loop which eats CPU.
This uses a RetryWatcher to solve the problem.
Fixes #1064
Thanks to @zubron for her excellent notes and POC branch which I barely had to modify :)
```
Sonobuoy no longers consumes 100% CPU when certain errors are encountered while streaming logs.
```

Avoid infinite loop when a following logs

---

pkg/image/imageversion.go
pkg/image/imageversion_test.go

Two builds with different metadata should refer to the same version.
As a result, we should just ignore the metadata in almost every case,
it is not relevent for choosing the e2e image.
Also, some API server versions reflect the cloud service (eks, gke,
etc). We need to continue to ignore those and choose just the basic
upstream image (e.g. 1.2.3-gke.2 should test against 1.2.3).
Fixes #1213
Fixes #1211
```
When detecting the API server version to determine which E2E tests to run, Sonobuoy ignores provider-specific "pre-release" values and build metadata.
```

E2E Image ignores metadata and provider build info

---

cmd/sonobuoy/app/args.go
cmd/sonobuoy/app/gen.go
cmd/sonobuoy/app/gen_test.go
cmd/sonobuoy/app/images.go
pkg/image/imageversion.go
pkg/image/imageversion_test.go

Special handling to identify the E2E image most recently pushed
for dev builds. Very helpful if you are developing recent features
or demoing them. Specify the --kube-conformance-image-version=latest
to get this behavior.
Fixes #1231
```
Test against the master branch of k8s by specifying the --kube-conformance-image-version=latest.
```

Add support for testing against the most recent dev E2E image

---

.github/workflows/ci-test.yaml

When pushing images you still need to checkout the
repo to get the script that does the pushing.
https://github.com/vmware-tanzu/sonobuoy/runs/2512840029?check_suite_focus=true
From the last PR reported it didnt have the build script. I had split out the push vs release after I had validated the other code so I didnt catch this.

Add a checkout step that was missed

---

site/themes/sonobuoy/layouts/index.redirects

Adds a new set of redirects so links like "docs/foo" go to
"docs/vLatest/foo".
Fixes #1232

Fix doc redirects

---

Makefile
pkg/backplane/ca/ca.go
scripts/build_funcs.sh

Use Subject Alternate Names fields instead.
Fixes: #1227

Don't use x509 common names

---

.github/workflows/ci-test.yaml
DockerfileWindows
scripts/build_funcs.sh

Adds windows builds for a number of OS versions to our CI pipeline.
Utilizes buildx and skopeo to build the windows images on the linux
runner and move them to dockerhub, then uses docker manifest to
create the manifest as usual.
In a quick reversal of a previous commit, we actually HAVE to put
all the images as "sonobuoy" and have the different arch/os use
different tags instead of different image names. This has to do with
how the manifest command looks up images and prevents issues wsuch as
"manifest not found" even though it does (as a differently named image
from the others).
Fixes #732
```
Windows images are now built and published alongside the Linux/amd64 and Linux/am64 versions.
```

Windows builds in CI

---

.github/workflows/ci-test.yaml

Just didn't catch this since it was in the push job, run only against master/tags.
Just confirmed this fix worked on my own fork though after merging: https://github.com/johnSchnake/sonobuoy/actions/runs/835797345

Removing unnecessary and incorrect load of testimage

---

DockerfileWindows
scripts/build_funcs.sh

This missing dll is required to run may containerized golang apps
since anything checking the current user via the os package
relies on this. It so happens that klog does this and so its common
for some dependency to end up with the issue.
We can continue to shift to klog/v2 which may fix the issue, but
it would could get hit via another import as well.
Fixes #1263

Add netapi32.dll to windows images

---

site/themes/sonobuoy/layouts/index.html

Linked to /posts/ instead of blog or just the post name itself. Probably just from the first iteration of the site.
Fixes #1261

Fix sonobuoy 101 link on site

---

go.mod
go.sum
pkg/client/results/reader.go
pkg/client/retrieve.go
pkg/discovery/discovery.go
pkg/discovery/queries.go
pkg/plugin/aggregation/aggregator_test.go
pkg/tarball/tarball.go
pkg/tarball/tarball_test.go
test/integration/testImage/src/tarResults.go

- When on the server side handling files, use filepath
- When loading files into the tarball, use path
- When on the clientside use filepath
- Use our own tar logic to avoid tarx and bugs with path/filepath
- Use splat on Windows as we do for linux. TODO (not on this PR): avoid reading entire tar into memory, for large runs that will cause an issue I'm pretty sure. Tarballs can get very big when you have 100 nodes and run tests for hours.

Fix multiple Windows tar issues 

---

site/themes/sonobuoy/assets/scss/_components.scss

The darkgrey was chosen, presumablu, because small bits
of code look good. However, in a large code block the background
is black and so the dark grey is nearly invisible.
Changing it to lightgrey or the like makes the blocks look good
but not the short snippets.
Rather than modify the blocks separately, removing this property
in general makes both look good in my opinion.

Remove coloring for codeblocks in blog

---

cmd/sonobuoy/app/gen_plugin_def.go
cmd/sonobuoy/app/gen_plugin_def_test.go
cmd/sonobuoy/app/testdata/pluginDef-nodeselector-default-podspec.golden
cmd/sonobuoy/app/testdata/pluginDef-nodeselector.golden
pkg/client/gen.go
pkg/client/testdata/default-plugins-via-nil-selection.golden
pkg/client/testdata/default-pod-spec.golden
pkg/client/testdata/default.golden
pkg/client/testdata/e2e-default.golden
pkg/client/testdata/e2e-progress-custom-port.golden
pkg/client/testdata/e2e-progress-vs-user-defined.golden
pkg/client/testdata/e2e-progress.golden
pkg/client/testdata/envoverrides.golden
pkg/client/testdata/goRunnerRemoved.golden
pkg/client/testdata/imagePullSecrets.golden
pkg/client/testdata/manual-custom-plugin-plus-e2e.golden
pkg/client/testdata/manual-e2e.golden
pkg/client/testdata/multiple-node-selector.golden
pkg/client/testdata/single-node-selector.golden
pkg/client/testdata/ssh.golden
pkg/plugin/driver/job/job.go

By default jobs can run on Linux nodes (thats fine) but
if we expect users to specify the node selectors for
Windows we should make it simple to add that bit.
Fixes #1275
```
Adds a new flag: sonobuoy gen plugin --node-selector foo=bar to facilitate creating windows plugins more easily.
```

Add node selector option when generating plugin spec

---

cmd/sonobuoy/app/testdata/pluginDef-default-podspec.golden
pkg/plugin/driver/base.go
pkg/plugin/driver/job/job.go
pkg/plugin/driver/job/job_test.go

The logic for this was previously broken, but when fixed, it
was found to actually be implemented incorrectly causing it to
overwrite the nodeSelector in all cases, not just when the podSpec
was empty.
Now it just updates the nodeSelector to linux boxes when there is
no podspec given by the user. If they want to specify a podspec to
force it to a different os (or any os) then they can do so.
Tests added to prevent this issue from regression.

Fix nodeSelector logic

---

cmd/sonobuoy/app/args.go
cmd/sonobuoy/app/retrieve.go
pkg/client/retrieve.go
test/integration/sonobuoy_integration_test.go

Adds a flag to sonobuoy extract which allows the user
to choose to download and extract the data in a single
command. This is ideal especially when worrying about if
someone on windows 1) can untar files easily 2) can be
sure that untar will end up being aware that the tarball
uses slash pathing and the client is on Windows.
Fixes #1277
```
Adds an --extract flag to sonobuoy retrieve command so that the results are downloaded and extracted in a single command.
```

Improve retrieve command with extraction option

---

pkg/buildinfo/version.go

Failed to actually bump the version in the last commit by accident.

Bump version

---

pkg/plugin/constants.go
pkg/plugin/driver/daemonset/daemonset.go
pkg/plugin/driver/job/job.go

When a plugin times out, users can sometimes be confused what they
should do next. Was there a real problem? Rerun?
At the very least we need to instruct them to check the logs and
see if they can find more clues.
- Fixes # 1152
```
Clarifies plugin timeout error message to instruct the user to check logs and that there are no results to view.
```

Expands timeout error message to try and clarify action

---

.github/workflows/ci-test.yaml

Waiting for the windows images to build each time when iterating
on tests/features is painful. We really only need the windows
images if we are sure things are passing and someone may actually
want to download/use/test the windows images.

Split windows and linux builds for speed

---

cmd/sonobuoy/app/gen_plugin_def.go
pkg/client/gen.go
pkg/client/gen_test.go
pkg/client/testdata/plugin-configmaps.golden
pkg/plugin/manifest/manifest.go
pkg/templates/gen.tmpl.yaml
scripts/build_funcs.sh
test/integration/sonobuoy_integration_test.go
test/integration/testImage/resources/junit-via-configmap.xml
test/integration/testImage/yaml/ds-junit-passing-tar.yaml
test/integration/testImage/yaml/ds-raw-passing-tar.yaml
test/integration/testImage/yaml/generate.sh
test/integration/testImage/yaml/job-junit-singlefile-configmap.yaml

The most common configuration option that we don't easily support is
a plugin specification that also includes config map info. By supporting
this we can easily support different deployment configurations without
specifying the entire `sonobuoy gen` yaml manually and sharing that.
This is particularly useful for specifying the kube-image-repo-list
as part of the plugin itself rather than as a command line option that
makes it harder to share.

Enables plugins to specify config map information

---

scripts/build_funcs.sh

The tests are simply getting longer in total; the 3m timeout
is not for individual tests but for the whole suite.
Using default of 10m and fixing an accidental filter on the tests.

Extend timeout and fix integration test invocation

---

.github/workflows/ci-test.yaml

Goreleaser needs 1.16 for embed pkg

---

pkg/client/gen.go
pkg/client/testdata/custom-systemd-logs-image.golden
pkg/client/testdata/default-plugins-via-nil-selection.golden
pkg/client/testdata/default-pod-spec.golden
pkg/client/testdata/default.golden
pkg/client/testdata/manual-custom-plugin-plus-systemd.golden
pkg/client/testdata/multiple-node-selector.golden
pkg/client/testdata/single-node-selector.golden
pkg/client/testdata/systemd-logs-default.golden
test/integration/testdata/gen-static.golden

The previous change which removed this sleep did also
ensure that the worker doesn't exit from errors so it doesn't
restart but the plugin container itself still exited and caused
a misleading pod status of CrashLoopBackOff.
That doesn't prevent anything for working but is confusing and
the sleep should be restored.
Fixes #1322
```
Fixes an issue where the default systemd-logs plugin command would cause the pod to enter the CrashLoopBackOff state. This bug did not prevet the plugin from submitting results properly.
```

Add sleep after systemd-logs again

---

cmd/sonobuoy/app/images.go
cmd/sonobuoy/app/images_test.go

The merging of kubernetes-version and kube-conformance-image-version
flags left the `sonobuoy images` command with improper resolution in
the default case.
There were previously no tests for this logic. This change fixes
the logic to resolve the new 'auto' default and tests this.
Fixes #1324
```
Fixes a bug where `sonobuoy images` failed unless `--kubernetes-version` was set (either to empty value or an explicit version).
```

Fix version resolution during image pulling

---

cmd/sonobuoy/app/status.go
cmd/sonobuoy/app/status_test.go
pkg/client/status.go
pkg/discovery/discovery.go
pkg/plugin/aggregation/status.go

Whenever we do not have an aggregation status, we can still
direct the user what to do next (usually debug with kubectl).
When possible, we should be able to tell them we can't pull the
image etc to shorten their cycles.
Fixes #1328
```
Improved output of `sonobuoy status` when the pod was not in the expected state to make it more clear how to proceed.
```

Add more descriptive status output

---

cmd/sonobuoy/app/gen.go
pkg/client/gen.go
pkg/client/gen_test.go
pkg/client/mode.go
pkg/client/testdata/default-plugins-via-selection.golden
pkg/client/testdata/e2e-default.golden
pkg/client/testdata/ssh.golden
pkg/client/testdata/systemd-logs-default.golden

- Mode will no longer remove systemd-logs when in quick mode. This
requires extra configuration code and provides little to no benefit
since the logs gathering plugin is so fast. Meanwhile, by removing it
we simplify the code in a way that makes upcoming changes regarding
e2e flags more simple.
- PluginSelection (the field in the config file) will continue
to be used for filtering which plugins are run on the server, but
will no longer be the appropriate place to list plugins in order to
run them. Modern sonobuoy code had simply been supporting this legacy
logic from when sonobuoy usually only ran our default plugins and
never had other fields to track them. To be clear: the CLI doesnt even use
the pluginSelection field typically; it was just the precursor to staticPlugins
and dynamic …

Simplify the way mode and plugin selection is processed

---

cmd/sonobuoy/app/images_test.go

The test naturally picks up on the local kubeconfig so we need
to intentionally set it to a "bad" value here.
Fixes #1345

Fix a unit test by avoiding local kubeconfig

---

cmd/sonobuoy/app/gen_plugin_def.go
pkg/client/gen.go
test/integration/testdata/gen-plugin-e2e-configmap.golden
test/integration/testdata/gen-plugin-e2e-kube-flag-still-works.golden
test/integration/testdata/gen-plugin-e2e.golden

- Adds a new method that allows us to easily reuse all the `gen`
logic and then just pull out the plugin we want.
- Removes the ability to specify configmaps to gen plugin e2e;
this seems like a trivial loss since I just added it in order
to achieve some other goal related to the windows plugins and
it never filled much of a real need.
This PR is meant to precede another related to how the k8s-version
flags are handled. In that PR, it broke the `gen plugin e2e` command
since this command wasn't really processing the plugin in the
same way that `gen` would.
```
Removed the ability to specify configmaps to `gen plugin e2e`. That was a very recent addition, had no obvious benefit, and was counter to the general intent of the `gen plugin e2e` command which was to present you …
```

Rework the gen plugin commands in order to reuse more code

---

cmd/sonobuoy/app/args.go
cmd/sonobuoy/app/gen.go
pkg/client/defaults.go
pkg/client/gen.go
pkg/client/gen_test.go
pkg/client/interfaces.go
pkg/client/interfaces_test.go
pkg/client/run.go
pkg/client/run_test.go

In an effort to generalize some features to more than just e2e,
I implemented a way to tie command line flags directly to plugins
which may be loaded at a later time.
In this case, we use the transformation logic along with the new
configmap handling for plugins to add a config map and env var
to the e2e plugin whenever the user provides the flag for a custom
e2e repo configuration.

Add generic plugin transformations and use for kube-repo-list

---

cmd/sonobuoy/app/root.go
pkg/errlog/errlog.go
pkg/image/docker/client.go

- Adds string flag to set log level for logrus
- Removes todo to update some of the logging to debug
- Marks debug flag as hidden/deprecated
- Marks klog flags as hidden
- If debug flag is set, simply sets the log level to debug.
Fixes #1189
```
Numerous logging flags. from klog have been marked as hidden to avoid clutter in the help menu. In addition, the --debug flag has been replaced with a --level flag that can be set to "debug" for the same effect as well as finer grain control over future logging.
```

Add configurable log levels for logrus

---

pkg/client/gen.go
pkg/client/gen_test.go
pkg/client/testdata/default-plugins-via-nil-selection.golden
pkg/client/testdata/default-plugins-via-selection.golden
pkg/client/testdata/default.golden
pkg/client/testdata/e2e-default.golden
pkg/client/testdata/imagePullPolicy-all-plugins.golden
pkg/client/testdata/multiple-node-selector.golden
pkg/client/testdata/plugin-configmaps.golden
pkg/client/testdata/single-node-selector.golden
pkg/client/testdata/systemd-logs-default.golden
test/integration/testdata/gen-variable-image.golden

Previously we applied imagePullPolicy to just the built in
plugins. This allowed users to specify the policy for each
plugin but made it inconvenient to change (had to manually
change the YAML) and inconsistent between our built-in
and custom plugins.
This applies the imagePullPolicy from the config to every
plugin. It occurs prior to the other plugin transformations
from flags, so if we do add something like a per-plugin
imagePullPolicy, it wouldn't interfere. I don't there will
be much demand for that though.
Related to #1315 
```
ImagePullPolicy will now be applied to all plugins run by Sonobuoy, not just our built-in e2e and systemd-logs plugins.
```

Apply ImagePullPolicy to all plugins not just built-in

---

pkg/plugin/aggregation/run_test.go
pkg/plugin/driver/base.go
pkg/plugin/interface.go
pkg/plugin/manifest/manifest.go

Adding description and sourceURL in order to
facilitate the plugin management.
Related to #1292
```
Plugins may now specify `sourceURL` and `description` fields in the `sonobuoy-config` of their plugin so that they are more self-documenting.
```

Add new fields to plugin manifests

---

cmd/sonobuoy/app/root.go
pkg/errlog/errlog.go

Previous implementation for custom log levels failed since it
used a string flag which never actually called the method
doing the logrus configuration.
Now we use a custom flag type which will call our own 'set' method
and has been demonstrated to work correctly.
Fixes #1189

Fix issue with custom log levels

---

pkg/tarball/tarball_test.go

Signed-off-by: Lars Lehtonen <lars.lehtonen@gmail.com>
This fixes a dropped test error.
```
release-note NONE
```

pkg/tarball: fix dropped test error

---

pkg/image/manifest.go

Adds GcEtcdRegistry with default `k8s.gcr.io` to command `sonobuoy gen default-image-config`.
This image is needed for this test and needs to be configured for air gapped environments.
Test: `Kubernetes e2e suite.[sig-api-machinery] Aggregator Should be able to support the 1.17 Sample API Server using the current Aggregator [Conformance]`
- Fixes #1359
```
release-note
```

add GcEtcdRegistry to GetDefaultImageRegistries for API server aggregator test

---

cmd/sonobuoy/app/pluginCache.go
cmd/sonobuoy/app/pluginCache_test.go
cmd/sonobuoy/app/root.go
go.mod
pkg/plugin/loader/loader.go
pkg/plugin/loader/loader_test.go
scripts/build_funcs.sh
test/integration/sonobuoy_integration_test.go
test/integration/testdata/plugin-delete-not-found.golden
test/integration/testdata/plugin-install-delete.golden
test/integration/testdata/plugin-install.golden
test/integration/testdata/plugin-list-good-bad.golden
test/integration/testdata/plugin-list.golden
test/integration/testdata/plugin-show-2.golden
test/integration/testdata/plugin-show-not-found.golden
test/integration/testdata/plugin-show-w-ext.golden
test/integration/testdata/plugin-show-wo-ext.golden
test/integration/testdata/plugins/bad-plugin.yaml
test/integration/testdata/plugins/good/hello-world.yaml
test/integration/testdata/plugins/good/hw-2.yaml

Adds a known location, ~/.sonobuoy or SONOBUOY_DIR env,
which stores plugin files (*.yaml). When running plugins this location is searched
first so that users can more easily call custom plugins from any location.
Adds:
- plugins list command
- plugin show command
- plugin install command
- plugin uninstall command
- tests for the above
Partially fixes: #1292

Adds plugin installation functionality

---

pkg/plugin/driver/utils/utils_test.go

Signed-off-by: Lars Lehtonen <lars.lehtonen@gmail.com>
This fixes multiple imports of `k8s.io/api/core/v1` in `pkg/plugin/driver/utils`.
```
NONE
```

pkg/plugin/driver/utils: fix multiple imports

---

cmd/sonobuoy/app/featureGates.go
cmd/sonobuoy/app/pluginCache.go
cmd/sonobuoy/app/pluginCache_test.go
cmd/sonobuoy/app/pluginList.go
test/integration/sonobuoy_integration_test.go
test/integration/testdata/plugin-loading-installed.golden
test/integration/testdata/plugin-loading-local.golden

Loads plugins from installation directory if feature enabled 
- Adds feature gates via env var
- Uses feature gate to make this new functionality optional
- If enabled, will search in the installation directory for
the plugin first before looking in the pwd
Fixes: vmware-tanzu#1292
```
Setting SONOBUOY_ALL_FEATURES or SONOBUOY_PLUGIN_INSTALLATION to `true` will enable sonobuoy to load plugins from the installation directory before looking in the pwd. It is expected that this will become the default behavior in the future.
```

Loads plugins from installation directory if feature enabled 

---

cmd/sonobuoy/app/args.go
cmd/sonobuoy/app/delete.go
cmd/sonobuoy/app/featureGates.go
cmd/sonobuoy/app/run.go
cmd/sonobuoy/app/status.go
cmd/sonobuoy/app/status_test.go
cmd/sonobuoy/app/testdata/expectedShowAll.golden
cmd/sonobuoy/app/testdata/expectedSummary.golden
cmd/sonobuoy/app/wait.go
go.mod
go.sum
pkg/client/delete.go
pkg/client/run.go

- Adds new wait-output mode "Progress" which outputs
details of the progress as the methods poll for completion.
- Modifies `sonobuoy status` to show progress if possible
- Adds a featuregate for making this the default behavior. This
sort of output seems like it would be greatly appreciated and most
wont care about the verbosity.
Partially fixes: #1170
```
Adds an experimental feature to show progress updates by default when using --wait flags instead of being silent. You can enable this by either specifying --wait-output=progress each time or setting the env vars SONOBUOY_PLUGIN_INSTALLATION=true or SONOBUOY_ALL_FEATURES=true.
```

Add progress output and feature gate it as default

---

pkg/client/results/junit_test.go

Signed-off-by: Lars Lehtonen <lars.lehtonen@gmail.com>
This fixes a dropped test error in `pkg/client/results`.
```
release-note NONE
```

pkg/client/results: fix dropped test error

---

cmd/sonobuoy/app/args.go
cmd/sonobuoy/app/retrieve.go
pkg/client/retrieve.go
pkg/client/retrieve_test.go

Allows the ability to specify the exact name of the file downloaded.
This helps script around this command in situations where you don't have
a shell to capture/manipulate it easily.
Fixes: #1361
```
You can now specify the exact filename of the tarball downloaded via `sonobuoy retrieve -f out.tar.gz`
```

Add filename flag for retrieve

---

cmd/sonobuoy/app/args.go
test/integration/sonobuoy_integration_test.go
test/integration/testdata/gen-issue-1375.golden

Previously used configs instead of config in path. Fixed typo
and added a test for this. However, it really only shows the env
var since the mount doesn't get created until the aggregator actually
creates the plugin pods.
Fixes #1375
```
Fixes a typo which caused e2e-repo-config to set the env var incorrectly
```

Fix typo causing e2e-repo-config to set env var to wrong value

---

cmd/sonobuoy/app/args.go
test/integration/sonobuoy_integration_test.go
test/integration/testdata/gen-config-then-flags.golden
test/integration/testdata/gen-issue-1375.golden
test/integration/testdata/gen-issue-1388.golden
test/integration/testdata/gen-no-uuid.golden
test/integration/testdata/gen-subfield-flags.golden

When the mode is set as certified conformance mode, the skip value
does not get properly reset and as a result skips the disruptive
tests.
Fixes: #1388

Fix regression regarding certified-conformance mode

---

README.md
site/content/docs/master/_index.md
site/content/docs/master/issue1388.md
site/content/docs/v0.53.1/_index.md
site/content/docs/v0.53.2/_index.md
site/content/docs/v0.53.2/issue1388.md

The docs have some special logic to try and redirect to the right
version of any given link. I've tried hardcoding the values for the
full URL but it isnt working for some reason. By just copying the file
into a few more places the links becomes much more simple.

Fix docs links for 1388 issue

---

.github/workflows/ci-test.yaml

Some CVEs were reported to us and were found with trivy. They
have a githubAction we can utilize to trivially add this to our
CI flow, adding to the security of the resulting product.
- Fixes #1384

Add vulnerability scanning to CI

---

cmd/sonobuoy/app/featureGates.go

Just a copy/paste bug. Typically I use SONOBUOY_ALL_FEATURES so I
hadn't seen this until now.

Fix feature gate name

---

pkg/plugin/aggregation/aggregator.go
pkg/plugin/aggregation/status.go
pkg/plugin/aggregation/status_test.go
pkg/plugin/aggregation/update_test.go

IF a test fails that indicates it fails, not Sonobuoy. I think the current
logic which labels the whole run as "failed" is incorrect now that the tool
has evolved to run more plugins.
Instead, the aggregator should only be marked failed if the aggregator itself
fails to get results and get them to the user.
Fixes #1414
```
A slight change to the meaning of the aggregators status values. It is now the case that even if a single (or all) the plugins fail, the aggregator itself is marked as `complete` since the aggregator status is seperate from the plugin results. The aggregator status continues to hold all the plugin status values which can be inspected if that is your goal. Typically, the aggregator status is simply used to determine if …
```

Adjust the logic for processing plugin results for aggregator status

---

cmd/sonobuoy/app/gen_plugin_def.go
cmd/sonobuoy/app/gen_plugin_def_test.go
cmd/sonobuoy/app/testdata/pluginDef-container.golden
cmd/sonobuoy/app/testdata/pluginDef-env.golden
pkg/client/interfaces.go
test/integration/sonobuoy_integration_test.go
test/integration/testdata/gen-nobadchars.golden
test/integration/testdata/gen-plugin-nobadchars.golden
test/integration/testdata/plugins/badpluginname.yaml

To avoid errors where/if users use capital letters or
special characters, I've added basic validation to the
logic and new tests. The regexp comes from k8s throwing
the error and has the RFC reference for clarity.
Fixes #1413
```
Plugin names must include only alphanumeric values and '.' or '-'. This is is in line with numerous objects requiring this naming scheme in Kubernetes and avoiding conflicts as we name objects related to those plugins.
```

Added validation to gen [plugin] for plugin name

---

pkg/discovery/pods.go
test/integration/sonobuoy_integration_test.go

The SelfLink value was being used as a UUID (I guess so it was
readable?) but has been deprecated and now always reads as empty.
This caused pod logs to not be gathered as expected.
Fixes #1415
```
Fixes a bug causing most pod logs (even in the sonobuoy namespace) to be queried at the end of the run despite logs indicating that they were.
```

Do not use deprecated SelfLink

---

cmd/sonobuoy/app/args.go
pkg/config/config.go

Without this you have to constantly change the flags depending
on the command and its verbose/painful. This will just be
a hidden little developer helper.

Adds easy way for devs to swap their own registry

---

pkg/client/delete.go
pkg/client/run.go
pkg/plugin/aggregation/handler.go

- tries to clarify that a creation/deletion refers to the API
request being issued, not completd
- disambiguate between progress requests and results requests
- add HTTP method when request is issued
- fix bug where subject.CommonName was used in logging when it
had been swapped for DNSNames in a previous PR
Fixes #1423
Fixes #1433
Fixes #1420
```
Improved clarity of a number of logging points to provide more (and more accurate) data to avoid confusion.
```

Improve various logging points on aggregator

---

pkg/discovery/queries.go
pkg/discovery/utils.go

It is a confusing waste of info and makes it much harder to look
at the output. In addition, it is not normally provided by kubectl
so users aren't even aware that it exists (I wasn't) and so it
makes the rest of the data seem more confusing than it needs to be.
Fixes #1428
You can use this command to test locally if you want:
```
sonobuoy run --mode=quick --sonobuoy-image=schnake/sonobuoy:devonly1632013611 --wait && sonobuoy retrieve -x nomanagedoutput
```
```
Removes managedfields from the query data since this is generally meaningless to any user, and very often mostly empty, nested fields that clog up the meaningful data.
```

Removed managed fields from query output

---

cmd/sonobuoy/app/featureGates.go
cmd/sonobuoy/app/featureGates_test.go
test/integration/sonobuoy_integration_test.go

Added logic so users can turn them off if it breaks
their logic in some way.
Fixes #1436
Fixes #1437
```
Two new experimental features have now been enabled by default:
- When running `sonobuoy run` or `sonobuoy delete` with the `--wait` flag, output is more verbose and shows you information about the ongoing process. It can be disabled by setting `SONOBUOY_WAIT_PROGRESS=false`
- New commands have been added to address plugin management. This allows you to store plugin configurations and reference them more easily, as opposed to always requiring a full path to the file or URL. It can be disabled by setting `SONOBUOY_PLUGIN_INSTALLATION=false`.
```

Default our experimental features to true

---

pkg/client/gen.go
pkg/client/gen_test.go
pkg/client/testdata/no-plugins-via-option.golden
pkg/config/config.go

To support the 0 plugins use case (uses sonobuoy for data
gathering only), this flag is the easiest and most clear approach.
Simply removes the plugins from the configuration before the
marshalling of the plugins. As a result, no plugins are put into
the configmap and none are available for loading on the aggregator
at run time.
- Fixes #1504 
```
Added a `SkipPlugins` option in the Sonobuoy config object which simplifies the situation when you may want to just run Sonobuoy for its data-gathering capability.
```

Add special config option to skip all plugins

---

cmd/sonobuoy/app/args.go
cmd/sonobuoy/app/retrieve.go
pkg/client/interfaces.go
pkg/client/retrieve.go

This allows us to debug/avoid one of the common bugs we've seen
lately related to poor handling of the aggregator results directory
and the config results directory.

Add flag for specifying the aggregator path to retrieve

---

.github/workflows/ci-lint.yaml

Multiple branches time out now and it wasn't clear if we really
wanted/needed the cache at all or if it caused more problems too.
- Extending timeout
- verbose mode
- disables cache

Add ci-lint options

---

cmd/sonobuoy/app/root.go
test/integration/sonobuoy_integration_test.go
test/integration/testdata/gen-mode-and-focus.golden
test/integration/testdata/gen-mode-and-rerun.golden

The rerun-failed flag also modifies the focus/skip fields and
so it can conflict if both are set. Warn users so they realize the
issue.
- Fixes #1515
```
Added warning if you specify rerun-failed along with other flags that modify the focus/skip of the e2e plugin.
```

Add more warnings for flag interactions

---

pkg/client/results/junit.go
pkg/client/results/junit_test.go

Working on a postprocessor to handle junit files and it would
be a shame to not be able to reuse whats here already.
I think just the types and unmarshal code is needed but this may extend
a bit if necessary to avoid too much copy/paste.
\

Export junitResults type

---

pkg/client/results/item.go
pkg/client/results/junit.go
pkg/client/results/junit_test.go

Working on a postprocessor to handle junit files and it would
be a shame to not be able to reuse whats here already.
I think just the types and unmarshal code is needed but this may extend
a bit if necessary to avoid too much copy/paste.
Field needed to be exported as well.

Export field

---

pkg/client/gen.go
test/integration/sonobuoy_integration_test.go
test/integration/testdata/gen-issue-1528.golden
test/integration/testdata/plugin-list.golden
test/integration/testdata/plugins/good/sidecar.yaml

If you are running two plugins but one has a sidecar and the other doesnt,
a bad re-use of an index caused an out of bounds reference.
- Fixes bug by renaming index in each case
- Adds test to prevent regression
Fixes #1528
```
Fixes a bug where `sonobuoy gen` would panic in some situations where plugins varied in whether or not they had sidecar containers.
```

Fix index bug in gen logic

---

pkg/client/gen.tmpl.yaml
pkg/client/testdata/aggregatorpermissions-noncluster-admin.golden
test/integration/testdata/gen-aggregator-permissions-namespaced.golden
test/integration/testdata/gen-config-no-flags.golden
test/integration/testdata/gen-config-then-flags.golden
test/integration/testdata/gen-issue-1375.golden
test/integration/testdata/gen-issue-1376.golden
test/integration/testdata/gen-issue-1388.golden
test/integration/testdata/gen-issue-1528.golden
test/integration/testdata/gen-mode-and-focus.golden
test/integration/testdata/gen-mode-and-rerun.golden
test/integration/testdata/gen-no-uuid.golden
test/integration/testdata/gen-plugin-renaming.golden
test/integration/testdata/gen-rerunfailed-works.golden
test/integration/testdata/gen-security-context-none.golden
test/integration/testdata/gen-static-only-e2e.golden
test/integration/testdata/gen-static.golden
test/integration/testdata/gen-subfield-flags.golden
test/integration/testdata/gen-variable-image.golden
test/integration/testdata/plugin-loading-installed.golden
test/integration/testdata/plugin-loading-local.golden

- do not create namespace
- namespace should be in metadata, not metadata.label
- in clusterAdmin mode, no need for namespace in metadata.label
- do not use non-resource URLs for namespaced role as they are not allowed
I think the template is too hard to read at this point and we should
translate it into code so it is easier to read, modify, and debug.
There are other issues with the run code itself that will cause the namespaced
permissions to fail, but this is the first step.
- Fixes #
```
release-note
```

Fix template for namespaced permissions

---

pkg/image/docker/client.go
pkg/image/docker_client.go
pkg/image/docker_client_test.go
pkg/image/dryrun_client.go
pkg/image/image.go

The entrypoint for the conformance image changed in
v1.22 which means that the way that we were invoking
the image with `--list-images` was not working correctly.
Instead, it would ignore that flag and still try and run
the kubeconformance (gorunner) which would start the tests.
- Fixes #1546
```
Fixed a bug which caused `sonobuoy images` to fail for Kubernetes v1.22+
```

Modify entrypoint for getting e2e test images

---

pkg/client/delete.go
pkg/client/gen.go
scripts/build_funcs.sh
test/integration/sonobuoy_integration_test.go
test/integration/testImage/Dockerfile
test/integration/testdata/gen-aggregator-permissions-namespaced.golden
test/integration/testdata/gen-config-no-flags.golden
test/integration/testdata/gen-config-then-flags.golden
test/integration/testdata/gen-issue-1375.golden
test/integration/testdata/gen-issue-1376.golden
test/integration/testdata/gen-issue-1388.golden
test/integration/testdata/gen-issue-1528.golden
test/integration/testdata/gen-mode-and-focus.golden
test/integration/testdata/gen-mode-and-rerun.golden
test/integration/testdata/gen-no-uuid.golden
test/integration/testdata/gen-plugin-renaming.golden
test/integration/testdata/gen-rerunfailed-works.golden
test/integration/testdata/gen-security-context-none.golden
test/integration/testdata/gen-static-only-e2e.golden
test/integration/testdata/gen-static.golden
test/integration/testdata/gen-subfield-flags.golden
test/integration/testdata/gen-variable-image.golden
test/integration/testdata/plugin-loading-installed.golden
test/integration/testdata/plugin-loading-local.golden

- label for namespace was expected, not to place it into that
namespace but to identify it as being related to that namespace's run.
- if DeleteAll is set, delete all regardless of namespace
- Fixes #1548 
```
Fixed a bug which caused cluster roles and bindings to not be deleted.
Modified the behavior of `sonobuoy delete --all` to include deleting all cluster roles related to any Sonobuoy run, regardless of namespace.
Added back a "namespace" label for ClusterRoles and ClusterRoleBindings in order to properly associate them with their Sonobuoy run.
```

Roles and bindings should have namespace label for deltion

---

site/content/docs/main/plugins.md

This makes that page, which is diverse and complicated, more
consumable.
Fixes #1556 

Add links to top of plugins page

---

site/content/docs/main/plugins.md
site/content/docs/main/results.md

This was added a few releases ago but never documented.
Just adding it into main and the next release docs will
start showing them.
Fixes #1555 

Add docs for result type gojson

---

pkg/client/delete.go
pkg/discovery/query.go
pkg/plugin/aggregation/run.go

Early in the run we gather nodes so that we know what results to expect
for the daemonsets. The new logic is:
- log a warning that this failed and indicate the daemonsets will not work
- since we dont have node names we dont know what results to expect/wait for
for daemonsets, so we just dont expect or wait for daemonsets at all
- when doing pod log queries, even though we cant query for all namespaces,
we know our current namespace and can query that if specified
- when doing resource queries, we likewise query those for the current
namespace
I think this should resolve the two issues below:
Fixes #1542 
Fixes #1470 
I am able to get runs started and even get some extra debug info like podlogs (for the test namespace) and API info for objects in that namespace too.

Continue with run even if unable to query nodes

---

pkg/client/gen.go
pkg/config/config.go
test/integration/sonobuoy_integration_test.go
test/integration/testdata/gen-aggregator-permissions-clusterRead.golden
test/integration/testdata/gen-aggregator-permissions-invalid.golden

Makes sense if we are going to allow customization of
aggregator permissions that we provide a few useful options.
In the originating ticket, the users wanted a strictly namespaced
permissions set.
It also makes sense, to offer a namespaced permission set that comes
with cluster reads. This allows us to run daemonsets (requires listing
nodes) and allows plugins to check things like kube-system pods.
In this permission mode, e2e tests will start (checks nodes are up
and kube-system pods are ready) but will fail since tests require that
namespaces get created (which it lacks permissions for).
```
Adds a `clusterRead` aggregator permission set which is effectively namespace admin plus cluster-wide read/list/watch. This allows cluster queries …
```

Add namespaced permissions with cluster read

---

cmd/sonobuoy/app/args.go
cmd/sonobuoy/app/images.go
cmd/sonobuoy/app/root.go
site/content/docs/main/airgap.md
test/integration/sonobuoy_integration_test.go
test/integration/testdata/gen-kube-test-repo.golden
test/integration/testdata/gen-rerunfailed-missing.golden
test/integration/testdata/gen-rerunfailed-no-failures.golden
test/integration/testdata/gen-rerunfailed-not-tarball.golden

Upstream e2e tests added a shortcut for overriding the
test image repos; you can now set a single env var and
all test images will assume that repo. Adding the flag
here since that should be useful for many.
- Fixes #1557 
```
Added a new --e2e-repo command which simplifies running in airgapped environments if you are using just a single registry.
```

Support KUBE_TEST_REPO

---

cmd/sonobuoy/app/args.go
cmd/sonobuoy/app/modes.go
cmd/sonobuoy/app/root.go
test/integration/sonobuoy_integration_test.go
test/integration/testdata/gen-rerunfailed-missing.golden
test/integration/testdata/gen-rerunfailed-no-failures.golden
test/integration/testdata/gen-rerunfailed-not-tarball.golden
test/integration/testdata/modes.golden

Add a way to list what modes are supported, their focus/skip/parallel
values, and their descriptions.
This expands the ability for Sonobuoy to self-document and allows us
to expand which modes are available so that different test sets can be
run.
- Fixes #1570
```
Added a new `sonobuoy modes` command which list available modes for the e2e plugin.
```

Add sonobuoy modes command

---

pkg/client/gen.go
test/integration/sonobuoy_integration_test.go
test/integration/testdata/gen-plugin-env-sonobuoy.golden

In a few situations we may want to set env vars on the
aggregator via the CLI. This is just a convenience change
but makes the plugin name `sonobuoy` reserved to avoid
an issue.
Fixes #1583 
```
Sonobuoy now allows you to set environment variables on the aggregator from the CLI via the existing `--plugin-env` flag using the reserved plugin name `sonobuoy`. For instance, `--plugin-env sonobuoy.KEY=val`.
```

Allow setting aggregator env vars via CLI

---

README.md
site/content/docs/main/_index.md
site/content/docs/main/aggregator-permissions.md

Adds documentation for `--aggregator-permissions` flag for `sonobuoy gen` command.
- Fixes #1569
```
none
```

added aggregator permissions doc

---

cmd/sonobuoy/app/modes.go
test/integration/testdata/gen-rerunfailed-missing.golden
test/integration/testdata/gen-rerunfailed-no-failures.golden
test/integration/testdata/gen-rerunfailed-not-tarball.golden
test/integration/testdata/modes.golden

The goal of this mode is to maximize coverage while minimizing
test time. I was able to get 257 tests in 334s.
This is just done from looking at old runs and sorting the tests
by time and avoiding running the slowest ones. We do not specify
the fastest ones because there are so many of them.
- Fixes #
```
release-note
```

Add conformance-lite mode

---

pkg/plugin/aggregation/aggregator_test.go
pkg/plugin/interface.go
pkg/plugin/interface_test.go

Failures should be included in totals but not
completed values (e.g. completed is non-failing
count only). This is based on the e2e plugin
implementation upstream. Best to be consistent
with that more than anything else since so many
different versions of that implementation already
exist.

Fix calculation for appending failures

---

site/content/posts/2019-05-15-Certifying-Kubernetes-with-Sonobuoy.md

Change the "custom plugin" link to point to sonobuoy.io/docs/plugins to resolve the 404 error
- Fixes #1602

Change the link "custom plugin"

---

pkg/client/gen.go
pkg/k8s/env.go
pkg/plugin/driver/base.go
pkg/plugin/driver/base_test.go
pkg/plugin/driver/daemonset/daemonset.go
pkg/plugin/driver/job/job.go

To allow users a way to specify env vars for the workers,
and therefore customize behavior, we copy the main set of
env vars from the plugin to the worker container. In the case
of conflicts, we prioritize our preset value to avoid breaking
the worker (e.g. if they try and override the address of the
aggregator).
```
The Sonobuoy worker (sidecar plugin) will now get have read-only access to all the env vars set for its corresponding plugin. This will enable some customization of worker behavior if needed to support other features.
```

Worker sidecars get plugin env vars

---

cmd/sonobuoy/app/version.go

Adds Go version and platform information to the version subcommand output
```
~/s/v/sonobuoy on 🌱 improve-version-subcommand (ddda7b1) [++(1)] on ⛵ dev () 
❯ GOOS=darwin GOARCH=arm64 go install
~/s/v/sonobuoy on 🌱 improve-version-subcommand (ddda7b1) [++(1)] on ⛵ dev () 
❯ sonobuoy version --kubeconfig ~/.kube/config
Sonobuoy Version: v0.56.0
MinimumKubeVersion: 1.17.0
MaximumKubeVersion: 1.99.99
GitSHA: 
GoVersion: go1.17.6
Platform: darwin/arm64
API Version:  v1.21.1
```
- Fixes None
None
```
Adds Go version and platform information to the version subcommand output
```

Improve version subcommand

---

.goreleaser.yml

New support in Go for this combination. No reason to not support it.
- Fixes #1614 
```
Add darwin/arm64 binary to release 
```

Add darwin/arm64 binary to release

---

cmd/sonobuoy/app/results.go
pkg/client/results/reader.go
pkg/client/results/reader_unix.go
pkg/client/results/reader_windows.go
pkg/discovery/logsummary.go
pkg/discovery/summary.go
pkg/discovery/summary_test.go

The code for the results reader was made to read the tarball without
opening it but it should also work on unzipped results. This allows
more reuse of the methods, a centralized place to put results structure
information, and will allow us to expand `results` to process an unzipped
directory as well.
- Fixes #1617

Modify reader code to work on unzipped results as well

---

cmd/sonobuoy/app/images.go
pkg/image/dryrun_client.go

`sonobuoy images` prints the image list, but there is no dry-run. This PR adds a `sonobuoy images list` command with dry-run flag.
- Related to #1605 and #1223
```
Add sonobuoy images list command
```

Add sonobuoy images list command

---

.github/workflows/ci-lint.yaml
cmd/sonobuoy/app/imagepullpolicy.go
cmd/sonobuoy/app/rbac.go
cmd/sonobuoy/app/wait.go
go.mod

Linter was complaining about requiring an update.
Updating it revealed issues with strings.Title which
have been fixed here.

Update linter and fix staticcheck issues

---

pkg/client/results/item.go
pkg/client/results/item_test.go

For processing results it can be useful to be able to
traverse the entire results tree. Rather than implement
this each time in projects, implementing it here.

Add function for walking item tree

---

pkg/client/gen.go

Currently when a configmap is defined in a plugin
it is only added to the main container and not the
sidecars. This adds it in the same fashion to the
others.
- Fixes #
```
release-note
```

Add configmaps to sidecars

---

pkg/client/results/gojson.go
pkg/client/results/junit.go
pkg/client/results/processing.go
pkg/client/results/raw.go

If we want any other plugin/library to be able to
translate files into the manual output, we need to
export the functions and types necessary.
- Fixes #1664

Export post processing

---

pkg/client/gen.go

Fix bug with sidecar mount. When we have a good post-processor
it will be easier to add tests for this.

Fix mount for sidecars

---

cmd/sonobuoy/app/images.go
pkg/image/docker/client.go
pkg/image/docker_client.go
pkg/image/docker_client_test.go
pkg/image/dryrun_client.go
pkg/image/image.go

This just passes env vars down the command to when we actually run
any images. This allows us to set KUBE_TEST_REPO as an env var
and see the images for which k8s will look for those images.
Fixes: #1678
```
KUBE_TEST_REPO can now be set when listing images, helping you get the proper tags for your images if you intend to utilize that feature.
```

Have 'images' commands respect env vars

---

cmd/sonobuoy/app/gen_plugin_def.go

Signed-off-by: DiptoChakrabarty <diptochuck123@gmail.com>
**What this PR does / why we need it**: adds a flag to set the url for a  plugin 
- Fixes #1648 
```
release-note
```

add url flag to set url for plugin

---

.github/workflows/ci-test.yaml

Otherwise failures in tests cause no artifacts, which is obviously a problem
when we want to investigate failures.
Fixes #1698

Always upload artifacts

---

cmd/sonobuoy/app/gen_plugin_def.go
cmd/sonobuoy/app/gen_plugin_def_test.go
cmd/sonobuoy/app/testdata/pluginDef-container.golden
cmd/sonobuoy/app/testdata/pluginDef-default-podspec.golden
cmd/sonobuoy/app/testdata/pluginDef-env.golden
cmd/sonobuoy/app/testdata/pluginDef-nodeselector-default-podspec.golden
cmd/sonobuoy/app/testdata/pluginDef-nodeselector.golden
cmd/sonobuoy/app/testdata/pluginDef-quotes.golden
cmd/sonobuoy/app/testdata/pluginDef-sonoconfig.golden
test/integration/testdata/gen-plugin-e2e-configmap.golden
test/integration/testdata/gen-plugin-e2e-kube-flag-still-works.golden
test/integration/testdata/gen-plugin-e2e.golden

A tiny bit of refactoring to ensure we hit that path and test it
as well.
Partially addresses: #1649
`sonobuoy gen plugin e2e` and `systemd-logs` still shows the mount because in order to get those it runs through the full `gen` process and applies the mount in the same way it does when sonobuoy consumes any other plugin.
Unnecessary but less of an issue IMO.

Remove empty resources from gen plugin

---

pkg/client/gen.go
pkg/discovery/discovery.go
test/integration/sonobuoy_integration_test.go
test/integration/testdata/issue1688.yaml

Issue #1688 would cause issues even if the old CLI was targeting
a new server. I've had multiple people this week report issues with
this so I wanted to resolve it and push a new release.
Added a new test to ensure we dont regress on this.
- Fixes #
```
release-note
```

Reconcile results directory and mount on server

---

pkg/plugin/driver/utils/utils.go
pkg/plugin/driver/utils/utils_test.go

This includes the image name which causes the errImagepull error to make the error message more meaningful
- Fixes #1707 
```
release-note
```

Include Image name in image pull error message

---

scripts/build_funcs.sh

Locally I reproduced the bug and was able to fix it by changing the
skopeo login to the $REGISTRY and not to the $DOCKERHUB_USER.
This begs the question: why did it work in the past? Unsure of the root
cause but this seemed to remedy it.
Also added debug info so that we can better diagnose the issue in the
future.
Fixes #1730

Fix skopeo login for image push issue

---

cmd/sonobuoy/app/args.go
test/integration/testdata/gen-rerunfailed-missing.golden
test/integration/testdata/gen-rerunfailed-no-failures.golden
test/integration/testdata/gen-rerunfailed-not-tarball.golden

Updates the help for the aggregator permissions flag to add the clusterRead value. Should have all of the correct permissions listed now.
- Fixes #1704

Add clusterRead to aggregator permissions help

---

scripts/build_funcs.sh

Download kubectl when testing locally (`update_local`), as it is done in `integration`.
- Fixes #1739

Download kubectl when testing locally

---

scripts/build_funcs.sh

The CI action in GitHub uses golangci-lint and so I
updated the build_func to do the same.
Discovered while working on a simple Makefile for new devs

Updates the lint function to be consistent with CI

---

cmd/sonobuoy/app/results.go
cmd/sonobuoy/app/results_test.go
go.mod
go.sum

*What this PR does / why we need it:*
Adds "readable" mode to the results command. Replaces \n with a new line and \t with a tab to make the output to stdio from the sonobuoy_results.yaml file more readable (dump mode does not do this).
Which issue(s) this PR fixes
Fixes https://github.com/vmware-tanzu/sonobuoy/issues/1628
*Special notes for your reviewer:*
Need to test the output of the command using readable mode. I was thinking we could have printSinglePlugin and printHealthSummary also return strings of what is printed to stdout to be used for testing, but that approach may be overkill for the sake of testing.

Add readable mode to results command

---

cmd/sonobuoy/app/get.go
cmd/sonobuoy/app/root.go

Adds a "get pods" command to fetch Sonobuoy worker pod names. Contains flags to specify namespace and plugin.
- Fixes #1713

Add command to get worker pod names

---

pkg/client/results/item.go
pkg/client/results/processing.go
pkg/client/results/processing_test.go
pkg/client/results/testdata/mockResults/plugins/ds-manual-02/ds-manual-02.golden.json
pkg/client/results/testdata/mockResults/plugins/ds-manual-03/ds-manual-03.golden.json
pkg/client/results/testdata/mockResults/plugins/ds-manual-04/ds-manual-04.golden.json
pkg/client/results/testdata/mockResults/plugins/ds-manual-arbitrary-details/ds-manual-arbitrary-details.golden.json
pkg/client/results/testdata/mockResults/plugins/job-manual-02/job-manual-02.golden.json
pkg/client/results/testdata/mockResults/plugins/job-manual-03/job-manual-03.golden.json
pkg/client/results/testdata/mockResults/plugins/job-manual-04/job-manual-04.golden.json
pkg/client/results/testdata/mockResults/plugins/job-manual-arbitrary-details/job-manual-arbitrary-details.golden.json
test/integration/sonobuoy_integration_test.go

- manual plugins now use the same code paths
- daemonsets use the same code paths
- if only known status values (pass/fail/etc) we use the same rules to
aggregate the values
- in all other cases we roll them up using values like "custom: 1, foo: 2"
This will be easier to debug, document, and utilize and it fixes 2 separate issues.
Fixes https://github.com/vmware-tanzu/sonobuoy/issues/1750
Fixes https://github.com/vmware-tanzu/sonobuoy/issues/1754

Simplify logic for status aggregation

---

pkg/plugin/aggregation/run.go
pkg/plugin/aggregation/run_test.go
pkg/plugin/driver/base.go
pkg/plugin/driver/daemonset/daemonset.go
pkg/plugin/driver/job/job.go
pkg/plugin/interface.go
pkg/plugin/manifest/manifest.go

Plugins should be able to run in a predetermined order. Adds order key to sonobuoy-config (lower number has a higher priority)
- Fixes #1684

Update plugin ordering to latest Sonobuoy version

---

cmd/sonobuoy/app/root.go
site/content/docs/main/e2eplugin.md
test/integration/sonobuoy_integration_test.go
test/integration/testdata/gen-issue-1376.golden
test/integration/testdata/gen-mode-and-focus.golden
test/integration/testdata/gen-mode-and-rerun.golden

- If mode/focus conflict, error instead of giving a warning since
there is no value in that use case.
- Modifies the docs a bit to mention this error mode
- expands docs regarding choosing tests to include the "e2e" command
Fixes #1767

Change warnings to errors for conflicting flags.

---

pkg/client/results/processing.go
pkg/client/results/processing_test.go
pkg/client/results/testdata/mockResults/plugins/ds-manual-01/ds-manual-01.golden.json
pkg/client/results/testdata/mockResults/plugins/ds-manual-04/ds-manual-04.golden.json
pkg/client/results/testdata/mockResults/plugins/job-manual-01/job-manual-01.golden.json
pkg/client/results/testdata/mockResults/plugins/job-manual-04/job-manual-04.golden.json
test/integration/testImage/yaml/job-manual.yaml

The processor doesnt just look for sonobuoy_results.yaml but all yaml
files. This makes it easier for plugin authors. Even with my experience
with the codebase I made this mistake and wasted 20m investigating it.
Fixes #1782

Manual all yaml

---

.github/workflows/k8sRelease.yaml

Alerts us to k8s releases in order to avoid long delays in
updating the e2e functionality.
Fixes #1793

Add K8s release check workflow

---

pkg/worker/worker.go
test/integration/sonobuoy_integration_test.go
test/integration/testImage/src/main.go
test/integration/testImage/src/singleFileResults.go
test/integration/testImage/yaml/generate.sh
test/integration/testImage/yaml/job-manual-directory.yaml

Current flow requires the plugin to tar up the results then
point to them. It would simplify things if we allowed pointing
to a directory and we do the tar process ourselves.
Fixes #1776

Allow worker to upload directory instead of file

---

cmd/sonobuoy/app/args.go
cmd/sonobuoy/app/gen.go
cmd/sonobuoy/app/run.go
pkg/client/interfaces.go
pkg/client/preflight.go
test/integration/testdata/gen-mode-and-focus.golden
test/integration/testdata/gen-mode-and-rerun.golden
test/integration/testdata/gen-rerunfailed-missing.golden
test/integration/testdata/gen-rerunfailed-no-failures.golden
test/integration/testdata/gen-rerunfailed-not-tarball.golden

Allow users to skip specific preflight checks using a new flag **skip-preflight-check**
The new flag was added since changing the flag type to string slice from bool requires an input value which would break any automation calling Sonobuoy from the CLI with --skip-preflight and no value.

Allow users to skip specific preflight checks

---

.github/workflows/ci-test.yaml

If the older go version is used, a go mod difference will be detected
and goreleaser will fail.
Fixes #1826

Update goversion for goreleaser

---

go.mod
go.sum

Update the net and text packages to resolve CVE-2022-27664  and CVE-2022-32149
Updated the image locally and tested using [trivy](https://github.com/aquasecurity/trivy) 
```bash
trivy fs go.mod
```

Fix for CVE-2022-27664 and CVE-2022-32149

---

site/content/docs/main/strategy.md

An update to the Sonobuoy strategy document examples. These examples are based on the use-cases for the OpenShift Provider Certification tool found below:
- Tool: https://github.com/redhat-openshift-ecosystem/provider-certification-tool
- Plugins: https://github.com/redhat-openshift-ecosystem/provider-certification-plugins
cc @mtulio @rvanderp3

Update strategy document examples

---

.github/workflows/k8sRelease.yaml

Signed-off-by: Dave Riddle <driddle@vmware.com>
Fixes our k8s issue check bot. With the recent syntax change to remove deprecation warnings, we ended up with an evaluation that would always return true.

Fix syntax error in k8s release workflow

---

README.md
site/content/docs/main/_index.md
site/content/plugins/list/02-end-to-end-testing.md

Signed-off-by: Jon Ji <jchenjun@vmware.com>
- Add missing instructions on how to install on MacOS with homebrew
- Fix broken link to kubernetes conformance image on plugin page

Add brew installation to README, fix broken plugin link

---

cmd/sonobuoy/app/delete.go
pkg/client/delete.go
pkg/client/interfaces.go

adds dry-run flag to the delete command, adds better printing of items to be deleted
- Fixes #1890 
```
adds a dry-run flag for the delete command + improved logging
```

add dry run delete

---

go.mod
scripts/build_funcs.sh
test/integration/testImage/Dockerfile
test/integration/testImage/src/go.mod

- Fixes #
```
updated Golang version to 1.21.4
```

update golang version

---

.github/workflows/ci-lint.yaml
.github/workflows/ci-test.yaml
pkg/client/gen.go
pkg/config/config.go
scripts/build_funcs.sh
test/integration/testImage/Dockerfile

Add support for injecting tolerations to sonobuoy pod
- Fixes #1973.
We can inject some tolerations to sonobuoy aggregator pod by adding trailing description into sonobuoy config json.
```json
{
"AggregatorTolerations": [
{
"effect": "NoSchedule",
"key": "key1",
"operator": "Equal",
"value": "value1"
},
{
"effect": "NoSchedule",
"key": "key2",
"operator": "Equal",
"value": "value2"
}
]
}
```
```
release-note
```

Add support for injecting tolerations to sonobuoy pod

---

.errcheck.list
.golangci.yaml

Got error with golangci lint https://github.com/vmware-tanzu/sonobuoy/actions/runs/13397812497/job/37421083123
Since the exclude keyword was removed  https://golangci-lint.run/usage/linters/#errcheck
- Fixes #
```
release-note
none
```

Update golangci errcheck config

---

.github/workflows/weekly-vulnerability-scan.yaml

**What this PR does / why we need it**: Adds a new GitHub workflow for weekly vulnerability scanning of Sonobuoy image. This helps us proactively identify security vulnerabilities before they become critical issues.
**Which issue(s) this PR fixes** : Addresses review comment by @lubronzhan https://github.com/vmware-tanzu/sonobuoy/pull/2012#issuecomment-2734339504
**Special notes for your reviewer**: Since manual workflow is enabled, the workflow will show up once merged in main
test run: https://github.com/farazkhawaja/sonobuoy/actions/runs/14548728237 -- tested on a older branch with vuln issues. _job fails when there is a vuln detected_

Add weekly linux vuln scan
